IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[c_Drug_Pack]') AND type in (N'U'))
DROP TABLE [c_Drug_Pack]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [c_Drug_Pack](
	[rxcui] [varchar](20) NOT NULL,
	[tty] [varchar](20) NULL,
	[descr] [varchar](1000) NULL,
	[valid_in] [varchar](100) NULL,
 CONSTRAINT [PK_Drug_Pack] PRIMARY KEY CLUSTERED 
(
	[rxcui] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
