set build_folder=C:\Users\tofft\EncounterPro\Builds\EncounterPRO-OS\EncounterPRO.OS.Client\%1

move /Y "Client\base\app_infrastructure.dll" %build_folder%
move /Y "Client\base\attribute.dll" %build_folder%
move /Y "Client\base\conversion.dll" %build_folder%
move /Y "Client\base\database_infrastructure.dll" %build_folder%
move /Y "Client\base\database_metadata.dll" %build_folder%
move /Y "Client\base\date_time.dll" %build_folder%
move /Y "Client\base\display_script.dll" %build_folder%
move /Y "Client\base\file.dll" %build_folder%
move /Y "Client\base\gui_basic.dll" %build_folder%
move /Y "Client\base\gui_specialized.dll" %build_folder%
move /Y "Client\base\image.dll" %build_folder%
move /Y "Client\base\menu.dll" %build_folder%
move /Y "Client\base\parameter.dll" %build_folder%
move /Y "Client\base\popup.dll" %build_folder%
move /Y "Client\base\pretty.dll" %build_folder%
move /Y "Client\base\printer.dll" %build_folder%
move /Y "Client\base\string.dll" %build_folder%
move /Y "Client\base\table_accessor.dll" %build_folder%
move /Y "Client\chart\chart_attachments.dll" %build_folder%
move /Y "Client\chart\chart_browser.dll" %build_folder%
move /Y "Client\chart\chart_drug_history.dll" %build_folder%
move /Y "Client\chart\chart_famhistory.dll" %build_folder%
move /Y "Client\chart\chart_graph.dll" %build_folder%
move /Y "Client\chart\chart_growth.dll" %build_folder%
move /Y "Client\chart\chart_healthmain.dll" %build_folder%
move /Y "Client\chart\chart_labs_tests.dll" %build_folder%
move /Y "Client\chart\chart_proc_history.dll" %build_folder%
move /Y "Client\chart\chart_soap.dll" %build_folder%
move /Y "Client\chart\chart_summary.dll" %build_folder%
move /Y "Client\chart\chart_vaccines.dll" %build_folder%
move /Y "Client\cpr.dll" %build_folder%
move /Y "Client\extension\ext_alert.dll" %build_folder%
move /Y "Client\extension\ext_attachments.dll" %build_folder%
move /Y "Client\extension\ext_billing.dll" %build_folder%
move /Y "Client\extension\ext_coding.dll" %build_folder%
move /Y "Client\extension\ext_msging.dll" %build_folder%
move /Y "Client\extension\ext_nomenclature.dll" %build_folder%
move /Y "Client\extension\ext_observation.dll" %build_folder%
move /Y "Client\extension\ext_pbreports.dll" %build_folder%
move /Y "Client\extension\ext_schedule.dll" %build_folder%
move /Y "Client\extension\ext_xml.dll" %build_folder%
move /Y "Client\server\server_services.dll" %build_folder%
move /Y "Client\service\config_object.dll" %build_folder%
move /Y "Client\service\configuration_tree.dll" %build_folder%
move /Y "Client\service\configure_actor.dll" %build_folder%
move /Y "Client\service\configure_assessment.dll" %build_folder%
move /Y "Client\service\configure_component.dll" %build_folder%
move /Y "Client\service\configure_drug.dll" %build_folder%
move /Y "Client\service\configure_observation.dll" %build_folder%
move /Y "Client\service\configure_treatment_type.dll" %build_folder%
move /Y "Client\service\configure_user.dll" %build_folder%
move /Y "Client\service\scheduled.dll" %build_folder%
move /Y "Client\service\svc_activity.dll" %build_folder%
move /Y "Client\service\svc_billing.dll" %build_folder%
move /Y "Client\service\svc_browser.dll" %build_folder%
move /Y "Client\service\svc_chart.dll" %build_folder%
move /Y "Client\service\svc_chart_encounter.dll" %build_folder%
move /Y "Client\service\svc_configuration.dll" %build_folder%
move /Y "Client\service\svc_epro_message.dll" %build_folder%
move /Y "Client\service\svc_epro_todo.dll" %build_folder%
move /Y "Client\service\svc_epro_workflow.dll" %build_folder%
move /Y "Client\service\svc_followup.dll" %build_folder%
move /Y "Client\service\svc_get_referral.dll" %build_folder%
move /Y "Client\service\svc_get_refills.dll" %build_folder%
move /Y "Client\service\svc_immunization.dll" %build_folder%
move /Y "Client\service\svc_material.dll" %build_folder%
move /Y "Client\service\svc_medication.dll" %build_folder%
move /Y "Client\service\svc_observations.dll" %build_folder%
move /Y "Client\service\svc_patient_message.dll" %build_folder%
move /Y "Client\service\svc_procedure.dll" %build_folder%
move /Y "Client\service\svc_report.dll" %build_folder%
move /Y "Client\service\svc_utility.dll" %build_folder%
move /Y "Client\shell\allergen.dll" %build_folder%
move /Y "Client\shell\attachment.dll" %build_folder%
move /Y "Client\shell\chart.dll" %build_folder%
move /Y "Client\shell\clinicaldatacache.dll" %build_folder%
move /Y "Client\shell\component_utility.dll" %build_folder%
move /Y "Client\shell\components.dll" %build_folder%
move /Y "Client\shell\consultant.dll" %build_folder%
move /Y "Client\shell\context.dll" %build_folder%
move /Y "Client\shell\contraindication.dll" %build_folder%
move /Y "Client\shell\document.dll" %build_folder%
move /Y "Client\shell\drug_administration.dll" %build_folder%
move /Y "Client\shell\encounter.dll" %build_folder%
move /Y "Client\shell\eproepiegateway.dll" %build_folder%
move /Y "Client\shell\evaluation_management.dll" %build_folder%
move /Y "Client\shell\health_management.dll" %build_folder%
move /Y "Client\shell\location.dll" %build_folder%
move /Y "Client\shell\maintenance.dll" %build_folder%
move /Y "Client\shell\observation_tree.dll" %build_folder%
move /Y "Client\shell\office.dll" %build_folder%
move /Y "Client\shell\patient.dll" %build_folder%
move /Y "Client\shell\patient_assessment.dll" %build_folder%
move /Y "Client\shell\patient_treatment.dll" %build_folder%
move /Y "Client\shell\patient_utility.dll" %build_folder%
move /Y "Client\shell\preference.dll" %build_folder%
move /Y "Client\shell\progress.dll" %build_folder%
move /Y "Client\shell\property.dll" %build_folder%
move /Y "Client\shell\room.dll" %build_folder%
move /Y "Client\shell\security.dll" %build_folder%
move /Y "Client\shell\shortlist.dll" %build_folder%
move /Y "Client\shell\specialty.dll" %build_folder%
move /Y "Client\shell\treatments.dll" %build_folder%
move /Y "Client\shell\workplan.dll" %build_folder%
move /Y "Client\shell\xml.dll" %build_folder%

REM move /Y "Client\dbmaint.dll" %build_folder%
REM move /Y "Client\eprodbmaint.exe" %build_folder%

move /Y "Client\encounterpro.os.client.exe" %build_folder%