
SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'c_Synonym') AND type in (N'U'))
DROP TABLE c_Synonym
GO

CREATE TABLE c_Synonym(
	term varchar(250) NOT NULL,
	term_type [varchar](30) NOT NULL,
	alternate [varchar](250) NOT NULL
 CONSTRAINT [PK_Synonym] PRIMARY KEY CLUSTERED 
(
	term_type ASC, term ASC, alternate ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

GRANT DELETE, INSERT, SELECT, UPDATE ON c_Synonym TO [cprsystem] AS [dbo]
GO

