DELETE FROM c_Synonym

INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('1-octacosanol', 'drug_ingredient', 'octacosanol')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('17-alpha-Hydroxyprogesterone', 'drug_ingredient', 'HYDROXYprogesterone caproate')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('4-Aminobenzoate', 'drug_ingredient', 'potassium aminobenzoate')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('4-Aminobenzoic Acid', 'drug_ingredient', 'aminobenzoic acid')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('4-Way', 'drug_ingredient', '4 Way')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('6-Aminocaproic Acid', 'drug_ingredient', 'aminocaproic acid')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Ala-Cort', 'drug_ingredient', 'Alacort')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Aminolevulinate', 'drug_ingredient', 'aminolevulinic acid HCl')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Aminosyn-HBC', 'drug_ingredient', 'Aminosyn HBC')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Aminosyn-PF', 'drug_ingredient', 'Aminosyn PF')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('andexanet alfa', 'drug_ingredient', 'coagulation factor Xa (recombinant), inactivated-zhzo')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Angelica sinensis preparation', 'drug_ingredient', 'Dong Quai root extract')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Arixtra', 'drug_ingredient', 'Atrixtra')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Ascorbic Acid', 'drug_ingredient', 'vitamin C')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Aspir-Low', 'drug_ingredient', 'Aspir Low')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Azelate', 'drug_ingredient', 'azelaic acid')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Azo-Cranberry', 'drug_ingredient', 'AZO Cranberry')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Baza-Protect', 'drug_ingredient', 'Baza Protect')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('BCG, Live, Tice Strain', 'drug_ingredient', 'BCG Vaccine, Tice Strain')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Beta-HC', 'drug_ingredient', 'Beta HC')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Bisco-Lax', 'drug_ingredient', 'Biscolax')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Bismarex', 'drug_ingredient', 'Bisma-Rex')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('BISMUTH-FORMIC-IODIDE', 'drug_ingredient', 'bismuth formic iodide')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Blistex Odor-Eaters Powder', 'drug_ingredient', 'Odor-Eaters Powder')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Bydureon', 'drug_ingredient', 'Byrdureon')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Carmol-20', 'drug_ingredient', 'CARMOL')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Cetrimides', 'drug_ingredient', 'cetrimide')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Chenodeoxycholate', 'drug_ingredient', 'chenodiol')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('chesnut oak pollen extract', 'drug_ingredient', 'chinkapin oak pollen extract')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Cholecalciferol', 'drug_ingredient', 'vitamin D3')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Chorionic Gonadotropin', 'drug_ingredient', 'choriogonadotropin alfa')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('chromic chloride', 'drug_ingredient', 'chromium')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('chromous chloride', 'drug_ingredient', 'chromium chloride')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Cleocin-T', 'drug_ingredient', 'Cleocin T')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('coenzyme Q10', 'drug_ingredient', 'ubidecarenone')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('cycloSPORINE', 'drug_ingredient', 'cyclosporin, modified')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('darbepoetin alfa', 'drug_ingredient', 'darbopoetin alfa')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('DentiCare Denti Foam', 'drug_ingredient', 'Denti-Care Denti-Foam')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('DentiCare Denti Freeze Gel', 'drug_ingredient', 'Denti-Care Denti-Freeze')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('DentiCare Denti Freeze Ointment', 'drug_ingredient', 'Denti-Care Denti-Freeze')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('DentiCare Neutral', 'drug_ingredient', 'Denti-Care DENTI-RINSE')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Deoxycholate', 'drug_ingredient', 'deoxycholic acid')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('DHE-45', 'drug_ingredient', 'D.H.E.')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Dihematoporphyrin Ether', 'drug_ingredient', 'porfimer sodium')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Doans', 'drug_ingredient', 'Doan''s Extra Strength')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Doans PM', 'drug_ingredient', 'Doan''s PM Back Pain Relief')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Docosahexaenoate', 'drug_ingredient', 'docosahexaenoic acid')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Docusate', 'drug_ingredient', 'docustate sodium')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Doxylamine', 'drug_ingredient', 'doxyalamine succinate')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Eescula', 'drug_ingredient', 'Rescula')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('efmoroctocog alfa', 'drug_ingredient', 'factor VIII (b-domain deleted recombinant) FC fusion protein')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Ethacrynate', 'drug_ingredient', 'ethacrynic acid')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Ethanol', 'drug_ingredient', 'alcohol')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('factor IX', 'drug_ingredient', 'albutrepenonacog alfa')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Factor VIII', 'drug_ingredient', 'simoctocog alfa')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Factor VIII', 'drug_ingredient', 'turoctocog alfa')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Fenofibrate', 'drug_ingredient', 'fenofibric acid')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Ferrex-150', 'drug_ingredient', 'Ferrex')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Freamine III 10', 'drug_ingredient', 'FreeAmine III')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('fumarate', 'drug_ingredient', 'fumaric acid')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Gaviscon', 'drug_ingredient', 'Gavsicon')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Glucose', 'drug_ingredient', 'dextrose')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Glutamate', 'drug_ingredient', 'glutamic acid')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('GLYCERYL PHOSPHATE', 'drug_ingredient', 'sodium glycerophosphate')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('glycolate', 'drug_ingredient', 'glycolic acid')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Goserelin', 'drug_ingredient', 'gosarelin acetate')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Human herpesvirus 1', 'drug_ingredient', 'talimogene laherparepvec')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Hypochlorite', 'drug_ingredient', 'hypochlorous acid')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Hypotears', 'drug_ingredient', 'Hypo Tears')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Insulin, Aspart, Human', 'drug_ingredient', 'insulin aspart')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Insulin, Glulisine, Human', 'drug_ingredient', 'insulin glulisine')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('insulin, isophane', 'drug_ingredient', 'insulin isophane, human')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Ionosol-B', 'drug_ingredient', 'IONOSOL B in')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Ionosol-MB', 'drug_ingredient', 'IONOSOL MB and')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Iron-Dextran Complex', 'drug_ingredient', 'iron dextran')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Isoptocarpine', 'drug_ingredient', 'Isopto Carpine')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Lactate', 'drug_ingredient', 'lactic acid')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Latrodectus mactans antivenin', 'drug_ingredient', 'Black widow spider antivenin')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('linoleate', 'drug_ingredient', 'linoleic acid')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Linseed Oil', 'drug_ingredient', 'flaxseed oil')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('LMX', 'drug_ingredient', 'L-M-X-4')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('LMX', 'drug_ingredient', 'L-M-X-5')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Magnesium Sulfate', 'drug_ingredient', 'Epsom Salt')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Mefenamate', 'drug_ingredient', 'mefenamic acid')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('methylsulfonylmethane', 'drug_ingredient', 'dimethyl sulfone')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Metoprolol', 'drug_ingredient', 'metroprolol tartrate')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Micardis-HCT', 'drug_ingredient', 'Micardis HCT')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('OsCal 500', 'drug_ingredient', 'Os-Cal')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('OXcarbazepine', 'drug_ingredient', 'oxacarbazepine')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Plasmalyte A', 'drug_ingredient', 'Plasma-Lyte A pH')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('prasterone', 'drug_ingredient', 'dehydroepiandrosterone')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Probanthine', 'drug_ingredient', 'Pro-Banthine')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('ProDenRx Rinse', 'drug_ingredient', 'Pro-Den Rx')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('profenamine', 'drug_ingredient', 'ethopropazine HCl')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('proxigermanium', 'drug_ingredient', 'germanium sesquioxide')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Rea-Lo', 'drug_ingredient', 'rea lo')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Retaine MGD', 'drug_ingredient', 'retain MGD')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Rymed-D', 'drug_ingredient', 'RYMED TABLETS')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Saccharomyces cerevisiae', 'drug_ingredient', 'brewer''s yeast')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('saccharomyces cerevisiae allergenic extract', 'drug_ingredient', 'baker''s yeast allergenic extract')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Salix alba bark extract', 'drug_ingredient', 'white willow bark')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Selenious Acid', 'drug_ingredient', 'selenium')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('sennosides, USP', 'drug_ingredient', 'senna')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('sennosides, USP', 'drug_ingredient', 'sennosides')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Sine-Off Maximum Strength Reformulated Sep 2008', 'drug_ingredient', 'SINE OFF Maximum Strength')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Slow-Fe', 'drug_ingredient', 'Slow Fe')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Sodium Fluoride', 'drug_ingredient', 'fluoride')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Soybean Lecithin', 'drug_ingredient', 'lecithin')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Stri-Dex Clear Gel', 'drug_ingredient', 'STRIDEX Clear Gel')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Superdent Hemal', 'drug_ingredient', 'super dent Hemal')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Tetrahydrocannabinol', 'drug_ingredient', 'dronabinol')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Thioctate', 'drug_ingredient', 'alpha lipoic acid')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Tiaprofenate', 'drug_ingredient', 'tiaprofenic acid')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('tiludronic acid', 'drug_ingredient', 'tiludronate disodium')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Trichloroacetate', 'drug_ingredient', 'trichloroacetic acid')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Tromethamine', 'drug_ingredient', 'THAM')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Ubiquinone', 'drug_ingredient', 'coenzyme Q-10')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Undecylenate', 'drug_ingredient', 'undecylenic acid')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Ursodeoxycholate', 'drug_ingredient', 'ursodiol')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Valproate', 'drug_ingredient', 'divalproex sodium')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Valproate', 'drug_ingredient', 'valproic acid')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('varicella-zoster immune globulin', 'drug_ingredient', 'varicella zoster immune globulin')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Varicella-Zoster Virus Vaccine Live (Oka-Merck) strain', 'drug_ingredient', 'varicella virus vaccine live')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Varicella-Zoster Virus Vaccine Live (Oka-Merck) strain', 'drug_ingredient', 'zoster vaccine live')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Visine-A', 'drug_ingredient', 'Visine A')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Vitamin B 12', 'drug_ingredient', 'cyanocobalamin')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Vitamin B6', 'drug_ingredient', 'pyridoxine HCl')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Vitamin E', 'drug_ingredient', 'dl-alpha tocopheryl acetate')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Vitamin K', 'drug_ingredient', 'phytonadione')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Vitamin K 1', 'drug_ingredient', 'phytonadione')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Viva-Drops Lubricating Eye Drops', 'drug_ingredient', 'VIVA Drops')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Yellow-Fever Virus Vaccine, 17D-204 strain', 'drug_ingredient', 'yellow fever vaccine (generic for Stamaril)')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Yellow-Fever Virus Vaccine, 17D-204 strain', 'drug_ingredient', 'yellow fever vaccine (generic for YF-Vax)')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Zinc Oxide', 'drug_ingredient', 'ZNO')
INSERT INTO c_Synonym (term, term_type, alternate) VALUES ('Zinc-DTPA', 'drug_ingredient', 'pentetate zinc trisodium')
