DELETE FROM icd_block WHERE 1=1

insert into icd_block (chapter, range, descr) values ('A-B infection / parasite','(A00-A09)','Intestinal infectious diseases')
insert into icd_block (chapter, range, descr) values ('A-B infection / parasite','(A15-A19)','Tuberculosis')
insert into icd_block (chapter, range, descr) values ('A-B infection / parasite','(A20-A28)','Certain zoonotic bacterial diseases')
insert into icd_block (chapter, range, descr) values ('A-B infection / parasite','(A30-A49)','Other bacterial diseases')
insert into icd_block (chapter, range, descr) values ('A-B infection / parasite','(A50-A64)','Infections with a predominantly sexual mode of transmission')
insert into icd_block (chapter, range, descr) values ('A-B infection / parasite','(A65-A69)','Other spirochaetal diseases')
insert into icd_block (chapter, range, descr) values ('A-B infection / parasite','(A70-A74)','Other diseases caused by chlamydiae')
insert into icd_block (chapter, range, descr) values ('A-B infection / parasite','(A75-A79)','Rickettsioses')
insert into icd_block (chapter, range, descr) values ('A-B infection / parasite','(A80-A89)','Viral diseases of the central nervous system')
insert into icd_block (chapter, range, descr) values ('A-B infection / parasite','(A90-A99)','Arthropod-borne viral fevers and viral haemorrhagic fevers')
insert into icd_block (chapter, range, descr) values ('A-B infection / parasite','(B00-B09)','Viral infections characterised by skin and mucous membrane lesions')
insert into icd_block (chapter, range, descr) values ('A-B infection / parasite','(B15-B19)','Viral hepatitis')
insert into icd_block (chapter, range, descr) values ('A-B infection / parasite','(B20-B24)','Human immunodeficiency virus [HIV] disease')
insert into icd_block (chapter, range, descr) values ('A-B infection / parasite','(B25-B34)','Other viral diseases')
insert into icd_block (chapter, range, descr) values ('A-B infection / parasite','(B35-B49)','Mycoses')
insert into icd_block (chapter, range, descr) values ('A-B infection / parasite','(B50-B64)','Protozoal diseases')
insert into icd_block (chapter, range, descr) values ('A-B infection / parasite','(B65-B83)','Helminthiases')
insert into icd_block (chapter, range, descr) values ('A-B infection / parasite','(B85-B89)','Pediculosis')
insert into icd_block (chapter, range, descr) values ('A-B infection / parasite','(B90-B94)','Sequelae of infectious and parasitic diseases')
insert into icd_block (chapter, range, descr) values ('A-B infection / parasite','(B95-B98)','Bacterial')
insert into icd_block (chapter, range, descr) values ('A-B infection / parasite','(B99-B99)','Other infectious diseases')
insert into icd_block (chapter, range, descr) values ('C-D neoplasm','(C00-C14)','Malignant neoplasms of lip, oral cavity and pharynx')
insert into icd_block (chapter, range, descr) values ('C-D neoplasm','(C15-C26)','Malignant neoplasms of digestive organs')
insert into icd_block (chapter, range, descr) values ('C-D neoplasm','(C30-C39)','Malignant neoplasm of respiratory and intrathoracic organs')
insert into icd_block (chapter, range, descr) values ('C-D neoplasm','(C40-C41)','Malignant neoplasm of bone and articular cartilage')
insert into icd_block (chapter, range, descr) values ('C-D neoplasm','(C43-C44)','Melanoma and other malignant neoplasms of skin')
insert into icd_block (chapter, range, descr) values ('C-D neoplasm','(C45-C49)','Malignant neoplasms of mesothelial and soft tissue')
insert into icd_block (chapter, range, descr) values ('C-D neoplasm','(C50-C50)','Malignant neoplasm of breast')
insert into icd_block (chapter, range, descr) values ('C-D neoplasm','(C51-C58)','Malignant neoplasms of female genital organs')
insert into icd_block (chapter, range, descr) values ('C-D neoplasm','(C60-C63)','Malignant neoplasms of male genital organs')
insert into icd_block (chapter, range, descr) values ('C-D neoplasm','(C64-C68)','Malignant neoplasm of urinary tract')
insert into icd_block (chapter, range, descr) values ('C-D neoplasm','(C69-C72)','Malignant neoplasms of eye, brain and other parts of central nervous system')
insert into icd_block (chapter, range, descr) values ('C-D neoplasm','(C73-C75)','Malignant neoplasms of thyroid and other endocrine glands')
insert into icd_block (chapter, range, descr) values ('C-D neoplasm','(C76-C80)','Malignant neoplasms of ill-defined, secondary and unspecified sites')
insert into icd_block (chapter, range, descr) values ('C-D neoplasm','(C81-C96)','Malignant neoplasms, lymphoid, haematopoietic and related tissue')
insert into icd_block (chapter, range, descr) values ('C-D neoplasm','(C97-C97)','Malignant neoplasms of independent (primary) multiple sites')
insert into icd_block (chapter, range, descr) values ('C-D neoplasm','(D00-D09)','In situ neoplasms')
insert into icd_block (chapter, range, descr) values ('C-D neoplasm','(D10-D36)','Benign neoplasms')
insert into icd_block (chapter, range, descr) values ('C-D neoplasm','(D37-D48)','Neoplasms of uncertain or unknown behaviour')
insert into icd_block (chapter, range, descr) values ('D blood / blood-forming organ','(D50-D53)','Nutritional anaemias')
insert into icd_block (chapter, range, descr) values ('D blood / blood-forming organ','(D55-D59)','Haemolytic anaemias')
insert into icd_block (chapter, range, descr) values ('D blood / blood-forming organ','(D60-D64)','Aplastic and other anaemias')
insert into icd_block (chapter, range, descr) values ('D blood / blood-forming organ','(D65-D69)','Coagulation defects, purpura and other haemorrhagic conditions')
insert into icd_block (chapter, range, descr) values ('D blood / blood-forming organ','(D70-D77)','Other diseases of blood and blood-forming organs')
insert into icd_block (chapter, range, descr) values ('D immune system','(D80-D89)','Certain disorders involving the immune mechanism')
insert into icd_block (chapter, range, descr) values ('E endocrine / nutritional / metabolic','(E00-E07)','Disorders of thyroid gland')
insert into icd_block (chapter, range, descr) values ('E endocrine / nutritional / metabolic','(E10-E14)','Diabetes mellitus')
insert into icd_block (chapter, range, descr) values ('E endocrine / nutritional / metabolic','(E15-E16)','Other disorders of glucose regulation and pancreatic internal secretion')
insert into icd_block (chapter, range, descr) values ('E endocrine / nutritional / metabolic','(E20-E35)','Disorders of other endocrine glands')
insert into icd_block (chapter, range, descr) values ('E endocrine / nutritional / metabolic','(E40-E46)','Malnutrition')
insert into icd_block (chapter, range, descr) values ('E endocrine / nutritional / metabolic','(E50-E64)','Other nutritional deficiencies')
insert into icd_block (chapter, range, descr) values ('E endocrine / nutritional / metabolic','(E65-E68)','Obesity and other hyperalimentation')
insert into icd_block (chapter, range, descr) values ('E endocrine / nutritional / metabolic','(E70-E90)','Metabolic disorders')
insert into icd_block (chapter, range, descr) values ('F mental / behavioural','(F00-F09)','Organic, including symptomatic, mental disorders')
insert into icd_block (chapter, range, descr) values ('F mental / behavioural','(F10-F19)','Mental and behavioural disorders due to psychoactive substance use')
insert into icd_block (chapter, range, descr) values ('F mental / behavioural','(F20-F29)','Schizophrenia, schizotypal and delusional disorders')
insert into icd_block (chapter, range, descr) values ('F mental / behavioural','(F30-F39)','Mood [affective] disorders')
insert into icd_block (chapter, range, descr) values ('F mental / behavioural','(F40-F48)','Neurotic, stress-related and somatoform disorders')
insert into icd_block (chapter, range, descr) values ('F mental / behavioural','(F50-F59)','Behavioural syndromes associated with psychological disturbances and physical factors')
insert into icd_block (chapter, range, descr) values ('F mental / behavioural','(F60-F69)','Disorders of adult personality and behaviour')
insert into icd_block (chapter, range, descr) values ('F mental / behavioural','(F70-F79)','Mental retardation')
insert into icd_block (chapter, range, descr) values ('F mental / behavioural','(F80-F89)','Disorders of psychological development')
insert into icd_block (chapter, range, descr) values ('F mental / behavioural','(F90-F98)','Behavioural and emotional disorders with onset usually occurring in childhood and adolescence')
insert into icd_block (chapter, range, descr) values ('F mental / behavioural','(F99-F99)','Unspecified mental disorder')
insert into icd_block (chapter, range, descr) values ('G nervous system','(G00-G09)','Inflammatory diseases of the central nervous system')
insert into icd_block (chapter, range, descr) values ('G nervous system','(G10-G14)','Systemic atrophies primarily affecting the central nervous system')
insert into icd_block (chapter, range, descr) values ('G nervous system','(G20-G26)','Extrapyramidal and movement disorders')
insert into icd_block (chapter, range, descr) values ('G nervous system','(G30-G32)','Other degenerative diseases of the central nervous system')
insert into icd_block (chapter, range, descr) values ('G nervous system','(G35-G37)','Demyelinating diseases of the central nervous system')
insert into icd_block (chapter, range, descr) values ('G nervous system','(G40-G47)','Episodic and paroxysmal disorders')
insert into icd_block (chapter, range, descr) values ('G nervous system','(G50-G59)','Nerve, nerve root and plexus disorders')
insert into icd_block (chapter, range, descr) values ('G nervous system','(G60-G64)','Polyneuropathies and other disorders of the peripheral nervous system')
insert into icd_block (chapter, range, descr) values ('G nervous system','(G70-G73)','Diseases of myoneural junction and muscle')
insert into icd_block (chapter, range, descr) values ('G nervous system','(G80-G83)','Cerebral palsy and other paralytic syndromes')
insert into icd_block (chapter, range, descr) values ('G nervous system','(G90-G99)','Other disorders of the nervous system')
insert into icd_block (chapter, range, descr) values ('H eye / adnexa','(H00-H06)','Disorders of eyelid')
insert into icd_block (chapter, range, descr) values ('H eye / adnexa','(H10-H13)','Disorders of conjunctiva')
insert into icd_block (chapter, range, descr) values ('H eye / adnexa','(H15-H22)','Disorders of sclera, cornea, iris and ciliary body')
insert into icd_block (chapter, range, descr) values ('H eye / adnexa','(H25-H28)','Disorders of lens')
insert into icd_block (chapter, range, descr) values ('H eye / adnexa','(H30-H36)','Disorders of choroid and retina')
insert into icd_block (chapter, range, descr) values ('H eye / adnexa','(H40-H42)','Glaucoma')
insert into icd_block (chapter, range, descr) values ('H eye / adnexa','(H43-H45)','Disorders of vitreous body and globe')
insert into icd_block (chapter, range, descr) values ('H eye / adnexa','(H46-H48)','Disorders of optic nerve and visual pathways')
insert into icd_block (chapter, range, descr) values ('H eye / adnexa','(H49-H52)','Disorders of ocular muscles, binocular movement, accommodation and refraction')
insert into icd_block (chapter, range, descr) values ('H eye / adnexa','(H53-H54)','Visual disturbances and blindness')
insert into icd_block (chapter, range, descr) values ('H eye / adnexa','(H55-H59)','Other disorders of eye and adnexa')
insert into icd_block (chapter, range, descr) values ('H ear / mastoid','(H60-H62)','Diseases of external ear')
insert into icd_block (chapter, range, descr) values ('H ear / mastoid','(H65-H75)','Diseases of middle ear and mastoid')
insert into icd_block (chapter, range, descr) values ('H ear / mastoid','(H80-H83)','Diseases of inner ear')
insert into icd_block (chapter, range, descr) values ('H ear / mastoid','(H90-H95)','Other disorders of ear')
insert into icd_block (chapter, range, descr) values ('I circulatory system','(I00-I02)','Acute rheumatic fever')
insert into icd_block (chapter, range, descr) values ('I circulatory system','(I05-I09)','Chronic rheumatic heart diseases')
insert into icd_block (chapter, range, descr) values ('I circulatory system','(I10-I15)','Hypertensive diseases')
insert into icd_block (chapter, range, descr) values ('I circulatory system','(I20-I25)','Ischaemic heart diseases')
insert into icd_block (chapter, range, descr) values ('I circulatory system','(I26-I28)','Pulmonary heart disease and diseases of pulmonary circulation')
insert into icd_block (chapter, range, descr) values ('I circulatory system','(I30-I52)','Other forms of heart disease')
insert into icd_block (chapter, range, descr) values ('I circulatory system','(I60-I69)','Cerebrovascular diseases')
insert into icd_block (chapter, range, descr) values ('I circulatory system','(I70-I79)','Diseases of arteries, arterioles and capillaries')
insert into icd_block (chapter, range, descr) values ('I circulatory system','(I80-I89)','Diseases of veins, lymphatic vessels and lymph nodes, not elsewhere classified')
insert into icd_block (chapter, range, descr) values ('I circulatory system','(I95-I99)','Other and unspecified disorders of the circulatory system')
insert into icd_block (chapter, range, descr) values ('J respiratory system','(J00-J06)','Acute respiratory infections')
insert into icd_block (chapter, range, descr) values ('J respiratory system','(J10-J18)','Influenza and pneumonia')
insert into icd_block (chapter, range, descr) values ('J respiratory system','(J20-J22)','Other acute lower respiratory infections')
insert into icd_block (chapter, range, descr) values ('J respiratory system','(J30-J39)','Other diseases of upper respiratory tract')
insert into icd_block (chapter, range, descr) values ('J respiratory system','(J40-J47)','Chronic lower respiratory diseases')
insert into icd_block (chapter, range, descr) values ('J respiratory system','(J60-J70)','Lung diseases due to external agents')
insert into icd_block (chapter, range, descr) values ('J respiratory system','(J80-J84)','Other respiratory diseases principally affecting the interstitium')
insert into icd_block (chapter, range, descr) values ('J respiratory system','(J85-J86)','Suppurative and necrotic conditions of lower respiratory tract')
insert into icd_block (chapter, range, descr) values ('J respiratory system','(J90-J94)','Other diseases of pleura')
insert into icd_block (chapter, range, descr) values ('J respiratory system','(J95-J99)','Other diseases of the respiratory system')
insert into icd_block (chapter, range, descr) values ('K digestive system','(K00-K14)','Diseases of oral cavity, salivary glands and jaws')
insert into icd_block (chapter, range, descr) values ('K digestive system','(K20-K31)','Diseases of oesophagus, stomach and duodenum')
insert into icd_block (chapter, range, descr) values ('K digestive system','(K35-K38)','Diseases of appendix')
insert into icd_block (chapter, range, descr) values ('K digestive system','(K40-K46)','Hernia')
insert into icd_block (chapter, range, descr) values ('K digestive system','(K50-K52)','Non-infective enteritis and colitis')
insert into icd_block (chapter, range, descr) values ('K digestive system','(K55-K64)','Other diseases of intestines')
insert into icd_block (chapter, range, descr) values ('K digestive system','(K65-K67)','Diseases of peritoneum')
insert into icd_block (chapter, range, descr) values ('K digestive system','(K70-K77)','Diseases of liver')
insert into icd_block (chapter, range, descr) values ('K digestive system','(K80-K87)','Disorders of gallbladder, biliary tract and pancreas')
insert into icd_block (chapter, range, descr) values ('K digestive system','(K90-K93)','Other diseases of the digestive system')
insert into icd_block (chapter, range, descr) values ('L skin / subcutaneous','(L00-L08)','Infections of the skin and subcutaneous tissue')
insert into icd_block (chapter, range, descr) values ('L skin / subcutaneous','(L10-L14)','Bullous disorders')
insert into icd_block (chapter, range, descr) values ('L skin / subcutaneous','(L20-L30)','Dermatitis and eczema')
insert into icd_block (chapter, range, descr) values ('L skin / subcutaneous','(L40-L45)','Papulosquamous disorders')
insert into icd_block (chapter, range, descr) values ('L skin / subcutaneous','(L50-L54)','Urticaria and erythema')
insert into icd_block (chapter, range, descr) values ('L skin / subcutaneous','(L55-L59)','Radiation-related disorders of the skin and subcutaneous tissue')
insert into icd_block (chapter, range, descr) values ('L skin / subcutaneous','(L60-L75)','Disorders of skin appendages')
insert into icd_block (chapter, range, descr) values ('L skin / subcutaneous','(L80-L99)','Other disorders of the skin and subcutaneous tissue')
insert into icd_block (chapter, range, descr) values ('M musculoskeletal / connective','(M00-M03)','Infectious arthropathies')
insert into icd_block (chapter, range, descr) values ('M musculoskeletal / connective','(M05-M14)','Inflammatory polyarthropathies')
insert into icd_block (chapter, range, descr) values ('M musculoskeletal / connective','(M15-M19)','Arthrosis')
insert into icd_block (chapter, range, descr) values ('M musculoskeletal / connective','(M20-M25)','Other joint disorders')
insert into icd_block (chapter, range, descr) values ('M musculoskeletal / connective','(M30-M36)','Systemic connective tissue disorders')
insert into icd_block (chapter, range, descr) values ('M musculoskeletal / connective','(M40-M43)','Deforming dorsopathies')
insert into icd_block (chapter, range, descr) values ('M musculoskeletal / connective','(M45-M49)','Spondylopathies')
insert into icd_block (chapter, range, descr) values ('M musculoskeletal / connective','(M50-M54)','Other dorsopathies')
insert into icd_block (chapter, range, descr) values ('M musculoskeletal / connective','(M60-M63)','Disorders of muscles')
insert into icd_block (chapter, range, descr) values ('M musculoskeletal / connective','(M65-M68)','Disorders of synovium and tendon')
insert into icd_block (chapter, range, descr) values ('M musculoskeletal / connective','(M70-M79)','Other soft tissue disorders')
insert into icd_block (chapter, range, descr) values ('M musculoskeletal / connective','(M80-M85)','Disorders of bone density and structure')
insert into icd_block (chapter, range, descr) values ('M musculoskeletal / connective','(M86-M90)','Other osteopathies')
insert into icd_block (chapter, range, descr) values ('M musculoskeletal / connective','(M91-M94)','Chondropathies')
insert into icd_block (chapter, range, descr) values ('M musculoskeletal / connective','(M95-M99)','Other disorders of the musculoskeletal system and connective tissue')
insert into icd_block (chapter, range, descr) values ('N genitourinary system','(N00-N08)','Glomerular diseases')
insert into icd_block (chapter, range, descr) values ('N genitourinary system','(N10-N16)','Renal tubulo-interstitial diseases')
insert into icd_block (chapter, range, descr) values ('N genitourinary system','(N17-N19)','Renal failure')
insert into icd_block (chapter, range, descr) values ('N genitourinary system','(N20-N23)','Urolithiasis')
insert into icd_block (chapter, range, descr) values ('N genitourinary system','(N25-N29)','Other disorders of kidney and ureter')
insert into icd_block (chapter, range, descr) values ('N genitourinary system','(N30-N39)','Other diseases of the urinary system')
insert into icd_block (chapter, range, descr) values ('N genitourinary system','(N40-N51)','Diseases of male genital organs')
insert into icd_block (chapter, range, descr) values ('N genitourinary system','(N60-N64)','Disorders of breast')
insert into icd_block (chapter, range, descr) values ('N genitourinary system','(N70-N77)','Inflammatory diseases of female pelvic organs')
insert into icd_block (chapter, range, descr) values ('N genitourinary system','(N80-N98)','Noninflammatory disorders of female genital tract')
insert into icd_block (chapter, range, descr) values ('N genitourinary system','(N99-N99)','Other disorders of the genito-urinary system')
insert into icd_block (chapter, range, descr) values ('O pregnancy / childbirth / puerperium','(O00-O08)','Pregnancy with abortive outcome')
insert into icd_block (chapter, range, descr) values ('O pregnancy / childbirth / puerperium','(O10-O16)','Oedema, proteinuria and hypertensive disorders in pregnancy, childbirth and the puerperium')
insert into icd_block (chapter, range, descr) values ('O pregnancy / childbirth / puerperium','(O20-O29)','Other maternal disorders predominantly related to pregnancy')
insert into icd_block (chapter, range, descr) values ('O pregnancy / childbirth / puerperium','(O30-O48)','Maternal care related to the foetus and amniotic cavity and possible delivery problems')
insert into icd_block (chapter, range, descr) values ('O pregnancy / childbirth / puerperium','(O60-O75)','Complications of labour and delivery')
insert into icd_block (chapter, range, descr) values ('O pregnancy / childbirth / puerperium','(O80-O84)','Delivery')
insert into icd_block (chapter, range, descr) values ('O pregnancy / childbirth / puerperium','(O85-O92)','Complications predominantly related to the puerperium')
insert into icd_block (chapter, range, descr) values ('O pregnancy / childbirth / puerperium','(O95-O99)','Other obstetric conditions')
insert into icd_block (chapter, range, descr) values ('P perinatal','(P00-P04)','Fetus and newborn affected by maternal factors / complications')
insert into icd_block (chapter, range, descr) values ('P perinatal','(P05-P08)','Disorders related to length of gestation and foetal growth')
insert into icd_block (chapter, range, descr) values ('P perinatal','(P10-P15)','Birth trauma')
insert into icd_block (chapter, range, descr) values ('P perinatal','(P20-P29)','Respiratory and cardiovascular disorders specific to the perinatal period')
insert into icd_block (chapter, range, descr) values ('P perinatal','(P35-P39)','Infections specific to the perinatal period')
insert into icd_block (chapter, range, descr) values ('P perinatal','(P50-P61)','Haemorrhagic and haematological disorders of foetus and newborn')
insert into icd_block (chapter, range, descr) values ('P perinatal','(P70-P74)','Transitory endocrine and metabolic disorders specific to foetus and newborn')
insert into icd_block (chapter, range, descr) values ('P perinatal','(P75-P78)','Digestive system disorders of foetus and newborn')
insert into icd_block (chapter, range, descr) values ('P perinatal','(P80-P83)','Conditions involving the integument and temperature regulation of foetus and newborn')
insert into icd_block (chapter, range, descr) values ('P perinatal','(P90-P96)','Other disorders originating in the perinatal period')
insert into icd_block (chapter, range, descr) values ('Q congenital / genetic','(Q00-Q07)','Congenital malformations of the nervous system')
insert into icd_block (chapter, range, descr) values ('Q congenital / genetic','(Q10-Q18)','Congenital malformations of eye, ear, face and neck')
insert into icd_block (chapter, range, descr) values ('Q congenital / genetic','(Q20-Q28)','Congenital malformations of the circulatory system')
insert into icd_block (chapter, range, descr) values ('Q congenital / genetic','(Q30-Q34)','Congenital malformations of the respiratory system')
insert into icd_block (chapter, range, descr) values ('Q congenital / genetic','(Q35-Q37)','Cleft lip and cleft palate')
insert into icd_block (chapter, range, descr) values ('Q congenital / genetic','(Q38-Q45)','Other congenital malformations of the digestive system')
insert into icd_block (chapter, range, descr) values ('Q congenital / genetic','(Q50-Q56)','Congenital malformations of genital organs')
insert into icd_block (chapter, range, descr) values ('Q congenital / genetic','(Q60-Q64)','Congenital malformations of the urinary system')
insert into icd_block (chapter, range, descr) values ('Q congenital / genetic','(Q65-Q79)','Congenital malformations and deformations of the musculoskeletal system')
insert into icd_block (chapter, range, descr) values ('Q congenital / genetic','(Q80-Q89)','Other congenital malformations')
insert into icd_block (chapter, range, descr) values ('Q congenital / genetic','(Q90-Q99)','Chromosomal abnormalities, not elsewhere classified')
insert into icd_block (chapter, range, descr) values ('R symptom / finding','(R00-R09)','Symptoms and signs involving the circulatory and respiratory systems')
insert into icd_block (chapter, range, descr) values ('R symptom / finding','(R10-R19)','Symptoms and signs involving the digestive system and abdomen')
insert into icd_block (chapter, range, descr) values ('R symptom / finding','(R20-R23)','Symptoms and signs involving the skin and subcutaneous tissue')
insert into icd_block (chapter, range, descr) values ('R symptom / finding','(R25-R29)','Symptoms and signs involving the nervous and musculoskeletal systems')
insert into icd_block (chapter, range, descr) values ('R symptom / finding','(R30-R39)','Symptoms and signs involving the urinary system')
insert into icd_block (chapter, range, descr) values ('R symptom / finding','(R40-R46)','Symptoms and signs involving cognition, perception, emotional state and behaviour')
insert into icd_block (chapter, range, descr) values ('R symptom / finding','(R47-R49)','Symptoms and signs involving speech and voice')
insert into icd_block (chapter, range, descr) values ('R symptom / finding','(R50-R69)','General symptoms and signs')
insert into icd_block (chapter, range, descr) values ('R symptom / finding','(R70-R79)','Abnormal findings on examination of blood, without diagnosis')
insert into icd_block (chapter, range, descr) values ('R symptom / finding','(R80-R82)','Abnormal findings on examination of urine, without diagnosis')
insert into icd_block (chapter, range, descr) values ('R symptom / finding','(R83-R89)','Abnormal findings on examination of other body fluids, substances and tissues, without diagnosis')
insert into icd_block (chapter, range, descr) values ('R symptom / finding','(R90-R94)','Abnormal findings on diagnostic imaging and in function studies, without diagnosis')
insert into icd_block (chapter, range, descr) values ('R symptom / finding','(R95-R99)','Ill-defined and unknown causes of mortality')
insert into icd_block (chapter, range, descr) values ('S-T injury','(S00-S09)','Injuries to the head')
insert into icd_block (chapter, range, descr) values ('S-T injury','(S10-S19)','Injuries to the neck')
insert into icd_block (chapter, range, descr) values ('S-T injury','(S20-S29)','Injuries to the thorax')
insert into icd_block (chapter, range, descr) values ('S-T injury','(S30-S39)','Injuries to the abdomen')
insert into icd_block (chapter, range, descr) values ('S-T injury','(S40-S49)','Injuries to the shoulder and upper arm')
insert into icd_block (chapter, range, descr) values ('S-T injury','(S50-S59)','Injuries to the elbow and forearm')
insert into icd_block (chapter, range, descr) values ('S-T injury','(S60-S69)','Injuries to the wrist and hand')
insert into icd_block (chapter, range, descr) values ('S-T injury','(S70-S79)','Injuries to the hip and thigh')
insert into icd_block (chapter, range, descr) values ('S-T injury','(S80-S89)','Injuries to the knee and lower leg')
insert into icd_block (chapter, range, descr) values ('S-T injury','(S90-S99)','Injuries to the ankle and foot')
insert into icd_block (chapter, range, descr) values ('S-T injury','(T00-T07)','Injuries involving multiple body regions')
insert into icd_block (chapter, range, descr) values ('S-T injury','(T08-T14)','Injuries to unspecified part of trunk, limb or body region')
insert into icd_block (chapter, range, descr) values ('S-T injury','(T15-T19)','Effects of foreign body entering through natural orifice')
insert into icd_block (chapter, range, descr) values ('S-T injury','(T20-T25)','Burns and corrosions of external body surface, specified by site')
insert into icd_block (chapter, range, descr) values ('S-T injury','(T26-T28)','Burns and corrosions confined to eye and internal organs')
insert into icd_block (chapter, range, descr) values ('S-T injury','(T29-T32)','Burns and corrosions of multiple and unspecified body regions')
insert into icd_block (chapter, range, descr) values ('S-T injury','(T33-T35)','Frostbite')
insert into icd_block (chapter, range, descr) values ('T poisoning','(T36-T50)','Poisoning by drugs, medicaments and biological substances')
insert into icd_block (chapter, range, descr) values ('T poisoning','(T51-T65)','Toxic effects of substances chiefly nonmedicinal as to source')
insert into icd_block (chapter, range, descr) values ('T external causes','(T66-T78)','Other and unspecified effects of external causes')
insert into icd_block (chapter, range, descr) values ('T external causes','(T79-T79)','Certain early complications of trauma')
insert into icd_block (chapter, range, descr) values ('T external causes','(T80-T88)','Complications of surgical and medical care, not elsewhere classified')
insert into icd_block (chapter, range, descr) values ('T external causes','(T90-T98)','Sequelae of injuries, of poisoning and of other consequences of external causes')
insert into icd_block (chapter, range, descr) values ('V transport accident','(V01-V09)','Pedestrian injured in transport accident')
insert into icd_block (chapter, range, descr) values ('V transport accident','(V10-V19)','Pedal cyclist injured in transport accident')
insert into icd_block (chapter, range, descr) values ('V transport accident','(V20-V29)','Motorcycle rider injured in transport accident')
insert into icd_block (chapter, range, descr) values ('V transport accident','(V30-V39)','Occupant of three-wheeled motor vehicle injured in transport accident')
insert into icd_block (chapter, range, descr) values ('V transport accident','(V40-V49)','Car occupant injured in transport accident')
insert into icd_block (chapter, range, descr) values ('V transport accident','(V50-V59)','Occupant of pick-up truck or van injured in transport accident')
insert into icd_block (chapter, range, descr) values ('V transport accident','(V60-V69)','Occupant of heavy transport vehicle injured in transport accident')
insert into icd_block (chapter, range, descr) values ('V transport accident','(V70-V79)','Bus occupant injured in transport accident')
insert into icd_block (chapter, range, descr) values ('V transport accident','(V80-V89)','Other land transport accidents')
insert into icd_block (chapter, range, descr) values ('V transport accident','(V90-V94)','Water transport accidents')
insert into icd_block (chapter, range, descr) values ('V transport accident','(V95-V97)','Air and space transport accidents')
insert into icd_block (chapter, range, descr) values ('V transport accident','(V98-V99)','Other and unspecified transport accidents')
insert into icd_block (chapter, range, descr) values ('W-X non-transport accident','(W00-W19)','Falls')
insert into icd_block (chapter, range, descr) values ('W-X non-transport accident','(W20-W49)','Exposure to inanimate mechanical forces')
insert into icd_block (chapter, range, descr) values ('W-X non-transport accident','(W50-W64)','Exposure to animate mechanical forces')
insert into icd_block (chapter, range, descr) values ('W-X non-transport accident','(W65-W74)','Accidental drowning and submersion')
insert into icd_block (chapter, range, descr) values ('W-X non-transport accident','(W75-W84)','Other accidental threats to breathing')
insert into icd_block (chapter, range, descr) values ('W-X non-transport accident','(W85-W99)','Exposure to electric current, radiation and extreme ambient air temperature and pressure')
insert into icd_block (chapter, range, descr) values ('W-X non-transport accident','(X00-X09)','Exposure to smoke, fire and flames')
insert into icd_block (chapter, range, descr) values ('W-X non-transport accident','(X10-X19)','Contact with heat and hot substances')
insert into icd_block (chapter, range, descr) values ('W-X non-transport accident','(X20-X29)','Contact with venomous animals and plants')
insert into icd_block (chapter, range, descr) values ('W-X non-transport accident','(X30-X39)','Exposure to forces of nature')
insert into icd_block (chapter, range, descr) values ('W-X non-transport accident','(X40-X49)','Accidental poisoning by and exposure to noxious substances')
insert into icd_block (chapter, range, descr) values ('W-X non-transport accident','(X50-X57)','Overexertion, travel and privation')
insert into icd_block (chapter, range, descr) values ('W-X non-transport accident','(X58-X59)','Exposure to other and unspecified factors')
insert into icd_block (chapter, range, descr) values ('X violence','(X60-X84)','Intentional self-harm')
insert into icd_block (chapter, range, descr) values ('X violence','(X85-Y09)','Assault')
insert into icd_block (chapter, range, descr) values ('X violence','(Y10-Y34)','Event of undetermined intent')
insert into icd_block (chapter, range, descr) values ('X violence','(Y35-Y36)','Legal intervention and operations of war')
insert into icd_block (chapter, range, descr) values ('Y adverse medical','(Y40-Y59)','Drugs, medicaments and biological substances causing adverse effects in therapeutic use')
insert into icd_block (chapter, range, descr) values ('Y adverse medical','(Y60-Y69)','Misadventures to patients during surgical and medical care')
insert into icd_block (chapter, range, descr) values ('Y adverse medical','(Y70-Y82)','Medical devices associated with adverse incidents in diagnostic and therapeutic use')
insert into icd_block (chapter, range, descr) values ('Y adverse medical','(Y83-Y84)','Surgical / medical procedures as the cause of abnormal reaction of the patient / complication')
insert into icd_block (chapter, range, descr) values ('Y adverse medical','(Y85-Y89)','Sequelae of external causes of morbidity and mortality')
insert into icd_block (chapter, range, descr) values ('Y adverse medical','(Y90-Y98)','Supplementary factors related to causes of morbidity and mortality classified elsewhere')
insert into icd_block (chapter, range, descr) values ('Z health factors','(Z00-Z13)','Persons encountering health services for examination and investigation')
insert into icd_block (chapter, range, descr) values ('Z health factors','(Z20-Z29)','Persons with potential health hazards related to communicable diseases')
insert into icd_block (chapter, range, descr) values ('Z health factors','(Z30-Z39)','Persons encountering health services in circumstances related to reproduction')
insert into icd_block (chapter, range, descr) values ('Z health factors','(Z40-Z54)','Persons encountering health services for specific procedures and health care')
insert into icd_block (chapter, range, descr) values ('Z health factors','(Z55-Z65)','Persons with potential health hazards related to socioeconomic and psychosocial circumstances')
insert into icd_block (chapter, range, descr) values ('Z health factors','(Z70-Z76)','Persons encountering health services in other circumstances')
insert into icd_block (chapter, range, descr) values ('Z health factors','(Z80-Z99)','Persons with potential health hazards related to family and personal history / health status')
insert into icd_block (chapter, range, descr) values ('U provisional','(U00-U49)','Provisional assignment of new diseases of uncertain aetiology')

update icd_block 
set range = replace(replace(range,'(',''),')','')
