ALTER TABLE [dbo].[c_Patient_material_category]
    ADD CONSTRAINT [PK___5__13] PRIMARY KEY CLUSTERED ([material_category_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

