ALTER TABLE [dbo].[o_Event_Queue_Attribute]
    ADD CONSTRAINT [PK___5__11] PRIMARY KEY CLUSTERED ([event_id] ASC, [attribute_sequence] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

