ALTER TABLE [dbo].[o_Component_Preference]
    ADD CONSTRAINT [PK___4__18] PRIMARY KEY CLUSTERED ([component_type] ASC, [component] ASC, [component_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

