ALTER TABLE [dbo].[c_Drug_HCPCS]
    ADD CONSTRAINT [PK___1__12] PRIMARY KEY CLUSTERED ([drug_id] ASC, [hcpcs_sequence] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

