ALTER TABLE [dbo].[b_Appointment_Type]
    ADD CONSTRAINT [PK___1__17] PRIMARY KEY CLUSTERED ([appointment_type] ASC, [billing_domain] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

