ALTER TABLE [dbo].[c_Qualifier_Domain]
    ADD CONSTRAINT [PK___2__14] PRIMARY KEY CLUSTERED ([qualifier_domain_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

