ALTER TABLE [dbo].[c_Treatment_Type]
    ADD CONSTRAINT [PK___c_Treatment__type] PRIMARY KEY CLUSTERED ([treatment_type] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

