ALTER TABLE [dbo].[b_Resource]
    ADD CONSTRAINT [PK___2__15] PRIMARY KEY CLUSTERED ([resource] ASC, [resource_sequence] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

