ALTER TABLE [dbo].[c_Patient_material]
    ADD CONSTRAINT [PK___1__15] PRIMARY KEY CLUSTERED ([material_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

