ALTER TABLE [dbo].[c_Event]
    ADD CONSTRAINT [PK___1__11] PRIMARY KEY CLUSTERED ([event] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

