ALTER TABLE [dbo].[o_Group_Rooms]
    ADD CONSTRAINT [PK___4__12] PRIMARY KEY CLUSTERED ([group_id] ASC, [room_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

