ALTER TABLE [dbo].[o_Event_Queue]
    ADD CONSTRAINT [PK___4__11] PRIMARY KEY CLUSTERED ([event_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

