ALTER TABLE [dbo].[c_Preference]
    ADD CONSTRAINT [PK___2__12] PRIMARY KEY CLUSTERED ([preference_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

