ALTER TABLE [dbo].[c_Component_Type]
    ADD CONSTRAINT [PK___1__18] PRIMARY KEY CLUSTERED ([component_type] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

