ALTER TABLE [dbo].[c_Attachment_Type]
    ADD CONSTRAINT [PK_attachment_type_21] PRIMARY KEY CLUSTERED ([attachment_type] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

