ALTER TABLE [dbo].[c_Folder]
    ADD CONSTRAINT [PK_c_Folder] PRIMARY KEY CLUSTERED ([folder] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

