ALTER TABLE [dbo].[c_User_Role]
    ADD CONSTRAINT [PK_c_User_Role] PRIMARY KEY CLUSTERED ([user_id] ASC, [role_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

