ALTER TABLE [dbo].[c_Epro_Object]
    ADD CONSTRAINT [PK_c_Epro_Object_50] PRIMARY KEY CLUSTERED ([epro_object] ASC) WITH (FILLFACTOR = 70, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

