ALTER TABLE [dbo].[c_Attachment_Location]
    ADD CONSTRAINT [PK_c_Attachment_Location_40] PRIMARY KEY CLUSTERED ([attachment_location_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

