ALTER TABLE [dbo].[c_Display_Format]
    ADD CONSTRAINT [PK_c_Display_Format_40] PRIMARY KEY CLUSTERED ([display_format] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

