ALTER TABLE [dbo].[c_Owner]
    ADD CONSTRAINT [PK_c_Owner_40] PRIMARY KEY CLUSTERED ([owner_id] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

