ALTER TABLE [dbo].[c_Database_Column]
    ADD CONSTRAINT [PK_c_Database_Column] PRIMARY KEY CLUSTERED ([tablename] ASC, [columnname] ASC) WITH (FILLFACTOR = 70, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

