ALTER TABLE [dbo].[c_Material]
    ADD CONSTRAINT [PK_c_Material_1__10] PRIMARY KEY CLUSTERED ([material_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

