ALTER TABLE [dbo].[c_Component_Interface]
    ADD CONSTRAINT [PK_c_component_interface] PRIMARY KEY CLUSTERED ([interfaceServiceId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

