ALTER TABLE [dbo].[c_Common_Procedure]
    ADD CONSTRAINT [PK_c_Specialty_Proc_40] PRIMARY KEY CLUSTERED ([specialty_id] ASC, [procedure_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

