ALTER TABLE [dbo].[c_Common_Assessment]
    ADD CONSTRAINT [PK_c_Specialty_Assmnt_40] PRIMARY KEY CLUSTERED ([specialty_id] ASC, [assessment_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

