ALTER TABLE [dbo].[c_Actor_Class_Route]
    ADD CONSTRAINT [PK_c_Actor_Class_Route_40] PRIMARY KEY CLUSTERED ([actor_class] ASC, [document_route] ASC) WITH (FILLFACTOR = 70, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

