ALTER TABLE [dbo].[c_Disease_Assessment]
    ADD CONSTRAINT [PK_c_Disease_assmnt_21] PRIMARY KEY CLUSTERED ([disease_id] ASC, [assessment_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

