ALTER TABLE [dbo].[c_Actor_Class_Purpose]
    ADD CONSTRAINT [PK_c_Actor_Class_Purpose] PRIMARY KEY CLUSTERED ([purpose] ASC, [actor_class] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

