ALTER TABLE [dbo].[c_Treatment_Type_Workplan]
    ADD CONSTRAINT [PK_c_Treatment_Type_Workplan] PRIMARY KEY CLUSTERED ([treatment_type] ASC, [treatment_mode] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

