ALTER TABLE [dbo].[c_Therapy_Model]
    ADD CONSTRAINT [PK_c_Therapy_Model_1__10] PRIMARY KEY CLUSTERED ([therapy_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

