ALTER TABLE [dbo].[c_Component_Param]
    ADD CONSTRAINT [PK_Comp_params_40] PRIMARY KEY CLUSTERED ([id] ASC, [param_sequence] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

