ALTER TABLE [dbo].[c_Authority_Category]
    ADD CONSTRAINT [PK_c_Authority_Category] PRIMARY KEY CLUSTERED ([authority_type] ASC, [authority_category] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

