ALTER TABLE [dbo].[c_Reccomended_Observation]
    ADD CONSTRAINT [PK_c_Reccomended_Observat1__10] PRIMARY KEY CLUSTERED ([assessment_id] ASC, [observation_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

