ALTER TABLE [dbo].[c_Vaccine_Disease]
    ADD CONSTRAINT [PK_c_Vaccine_Disease_1__14] PRIMARY KEY CLUSTERED ([vaccine_id] ASC, [disease_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

