ALTER TABLE [dbo].[c_Actor_Route_Purpose]
    ADD CONSTRAINT [PK_c_Actor_Route_Purpose] PRIMARY KEY CLUSTERED ([actor_id] ASC, [route_purpose_sequence] ASC) WITH (FILLFACTOR = 70, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

