ALTER TABLE [dbo].[c_Actor_Class_Type]
    ADD CONSTRAINT [PK_c_Actor_Class_Type] PRIMARY KEY CLUSTERED ([actor_class] ASC, [actor_type] ASC) WITH (FILLFACTOR = 70, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

