ALTER TABLE [dbo].[c_XML_Class_Selection]
    ADD CONSTRAINT [PK_c_XML_Class_Selection_40] PRIMARY KEY CLUSTERED ([xml_class_selection_id] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

