ALTER TABLE [dbo].[c_XML_Class]
    ADD CONSTRAINT [PK_c_XML_Class_40] PRIMARY KEY CLUSTERED ([xml_class] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

