ALTER TABLE [dbo].[c_Attachment_Extension]
    ADD CONSTRAINT [PK_c_Attachment_Extension_40] PRIMARY KEY CLUSTERED ([extension] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

