ALTER TABLE [dbo].[c_Property_Type]
    ADD CONSTRAINT [PK_c_Property_type_1] PRIMARY KEY CLUSTERED ([property_type] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

