ALTER TABLE [dbo].[c_Report_Definition]
    ADD CONSTRAINT [PK_c_Report_Definition_40] PRIMARY KEY CLUSTERED ([report_id] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

