ALTER TABLE [dbo].[c_ICD_Updates]
    ADD CONSTRAINT [PK_c_ICD_Updates_128] PRIMARY KEY CLUSTERED ([icd_9_code] ASC, [icd_sequence] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

