ALTER TABLE
ADD CONSTRAINT [PK_c_Config_Object_Version_Dependency] PRIMARY KEY CLUSTERED 
(
	[config_object_id] ASC,
	[version] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 70) ON [PRIMARY]
GO
