ALTER TABLE [dbo].[c_Location_Domain]
    ADD CONSTRAINT [PK_c_Location_Domain_1__10] PRIMARY KEY CLUSTERED ([location_domain] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

