ALTER TABLE [dbo].[c_Workplan_Item]
    ADD CONSTRAINT [PK_c_Workplan_Item] PRIMARY KEY CLUSTERED ([workplan_id] ASC, [item_number] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

