ALTER TABLE [dbo].[c_Growth_Data]
    ADD CONSTRAINT [PK_c_Growth_Data_1__10] PRIMARY KEY CLUSTERED ([measurement] ASC, [sex] ASC, [age_months] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

