ALTER TABLE [dbo].[c_Database_Status]
    ADD CONSTRAINT [PK_c_Database_Status] PRIMARY KEY CLUSTERED ([customer_id] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

