ALTER TABLE [dbo].[c_Property]
    ADD CONSTRAINT [PK_c_Property] PRIMARY KEY CLUSTERED ([property_id] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

