ALTER TABLE [dbo].[c_Message_Stream]
    ADD CONSTRAINT [PK_c_Message_Stream_21] PRIMARY KEY CLUSTERED ([message_type] ASC, [stream_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

