ALTER TABLE [dbo].[c_Unit_Conversion]
    ADD CONSTRAINT [PK_c_Unit_Conversion_1__10] PRIMARY KEY CLUSTERED ([unit_from] ASC, [unit_to] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

