ALTER TABLE [dbo].[c_Role]
    ADD CONSTRAINT [PK_c_Role] PRIMARY KEY CLUSTERED ([role_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

