ALTER TABLE [dbo].[c_Table_Altkey]
    ADD CONSTRAINT [PK_c_Altkey_1__13] PRIMARY KEY CLUSTERED ([cpr_table] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

