ALTER TABLE [dbo].[c_Workplan]
    ADD CONSTRAINT [PK_c_Workplan_1__10] PRIMARY KEY CLUSTERED ([workplan_id] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

