ALTER TABLE [dbo].[c_Location]
    ADD CONSTRAINT [PK_c_Location_1__27] PRIMARY KEY NONCLUSTERED ([location] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

