ALTER TABLE [dbo].[c_Assessment_Definition]
    ADD CONSTRAINT [PK_c_Assessment_Definition_40] PRIMARY KEY CLUSTERED ([assessment_id] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

