ALTER TABLE [dbo].[c_User_Progress]
    ADD CONSTRAINT [PK_c_Users_prog_40] PRIMARY KEY CLUSTERED ([user_id] ASC, [user_progress_sequence] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

