ALTER TABLE [dbo].[c_Domain_Master]
    ADD CONSTRAINT [PK_c_Domain_Master] PRIMARY KEY CLUSTERED ([domain_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

