ALTER TABLE [dbo].[c_Config_Log]
    ADD CONSTRAINT [PK_c_Config_Log] PRIMARY KEY CLUSTERED ([config_log_id] ASC) WITH (FILLFACTOR = 70, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

