ALTER TABLE [dbo].[c_Age_Range_Category]
    ADD CONSTRAINT [PK_c_Age_Range_cat_40] PRIMARY KEY CLUSTERED ([owner_id] ASC, [age_range_category] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

