ALTER TABLE [dbo].[c_Table_Update]
    ADD CONSTRAINT [PK_c_Table_Update] PRIMARY KEY CLUSTERED ([table_name] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

