ALTER TABLE [dbo].[c_Procedure_Material]
    ADD CONSTRAINT [PK_c_Procedure_Material_1__10] PRIMARY KEY CLUSTERED ([procedure_id] ASC, [material_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

