ALTER TABLE [dbo].[c_Database_Script]
    ADD CONSTRAINT [PK_c_Database_Script] PRIMARY KEY CLUSTERED ([script_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

