ALTER TABLE [dbo].[c_Formulary]
    ADD CONSTRAINT [PK_c_Formulary] PRIMARY KEY CLUSTERED ([formulary_code] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

