ALTER TABLE [dbo].[c_Property_Attribute]
    ADD CONSTRAINT [PK_c_Property_Attribute] PRIMARY KEY CLUSTERED ([property_id] ASC, [attribute_sequence] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

