ALTER TABLE [dbo].[c_Treatment_Type_List]
    ADD CONSTRAINT [PK_c_treatment_type_list] PRIMARY KEY CLUSTERED ([treatment_list_id] ASC, [list_sequence] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

