ALTER TABLE [dbo].[c_Preference_Type]
    ADD CONSTRAINT [PK_c_Preference_Type_1__12] PRIMARY KEY CLUSTERED ([preference_type] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

