ALTER TABLE [dbo].[c_Component_Param_Class]
    ADD CONSTRAINT [PK_comp_p_c_40] PRIMARY KEY CLUSTERED ([param_class] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

