ALTER TABLE [dbo].[c_Chart_Page_Definition]
    ADD CONSTRAINT [PK_chart_page_def_40] PRIMARY KEY CLUSTERED ([page_class] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

