ALTER TABLE [dbo].[c_Folder_Attribute]
    ADD CONSTRAINT [PK_c_Folder_Attribute] PRIMARY KEY CLUSTERED ([folder] ASC, [attribute_sequence] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

