ALTER TABLE [dbo].[c_Database_Table]
    ADD CONSTRAINT [PK_c_Database_Table] PRIMARY KEY CLUSTERED ([tablename] ASC, [major_release] ASC, [database_version] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

