ALTER TABLE [dbo].[c_Procedure]
    ADD CONSTRAINT [PK_c_Procedure_40] PRIMARY KEY CLUSTERED ([procedure_id] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

