ALTER TABLE [dbo].[c_Drug_Brand]
    ADD CONSTRAINT [PK_c_Drug_Brand_1__10] PRIMARY KEY CLUSTERED ([drug_id] ASC, [brand_name] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

