ALTER TABLE [dbo].[c_Administration_Frequency]
    ADD CONSTRAINT [PK_c_Administration_Frequ1__10] PRIMARY KEY CLUSTERED ([administer_frequency] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

