ALTER TABLE [dbo].[c_Chart_Page_Attribute]
    ADD CONSTRAINT [PK_c_Chart_Page_Attribute_40] PRIMARY KEY CLUSTERED ([page_class] ASC, [attribute_sequence] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

