ALTER TABLE [dbo].[c_Database_Script_Type]
    ADD CONSTRAINT [PK_c_Database_Script_Type] PRIMARY KEY CLUSTERED ([script_type] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

