ALTER TABLE [dbo].[c_Observation_Stage]
    ADD CONSTRAINT [PK_c_Observation_Stage_40] PRIMARY KEY CLUSTERED ([observation_id] ASC, [stage] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

