ALTER TABLE [dbo].[c_Display_Format_Item]
    ADD CONSTRAINT [PK_c_Display_Format_Item_40] PRIMARY KEY CLUSTERED ([display_format] ASC, [item_sequence] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

