ALTER TABLE [dbo].[c_Material_Item]
    ADD CONSTRAINT [PK_c_Material_Item_1__10] PRIMARY KEY CLUSTERED ([material_id] ASC, [material_item_sequence] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

