ALTER TABLE [dbo].[c_Maintenance_Patient_Class]
    ADD CONSTRAINT [PK_c_Maintenance_Patient_Class_40] PRIMARY KEY CLUSTERED ([maintenance_rule_id] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

