ALTER TABLE [dbo].[c_Package]
    ADD CONSTRAINT [PK_c_Package_21] PRIMARY KEY CLUSTERED ([package_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

