ALTER TABLE [dbo].[c_Chart_Alert_Category]
    ADD CONSTRAINT [PK_c_Chart_Alert_Category] PRIMARY KEY CLUSTERED ([alert_category_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

