ALTER TABLE [dbo].[c_Treatment_Type_Service]
    ADD CONSTRAINT [PK_c_Treatment_Type_Service] PRIMARY KEY CLUSTERED ([treatment_type] ASC, [service_sequence] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

