ALTER TABLE [dbo].[c_Authority]
    ADD CONSTRAINT [PK_c_Authority_21] PRIMARY KEY CLUSTERED ([authority_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

