ALTER TABLE [dbo].[c_Assessment_Coding]
    ADD CONSTRAINT [PK_c_Assessment_Coding_1] PRIMARY KEY CLUSTERED ([assessment_id] ASC, [authority_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

