ALTER TABLE [dbo].[c_Office]
    ADD CONSTRAINT [PK_c_Office_xxx] PRIMARY KEY CLUSTERED ([office_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

