ALTER TABLE [dbo].[c_Observation_Tree]
    ADD CONSTRAINT [PK_c_Observation_Tree_40] PRIMARY KEY NONCLUSTERED ([branch_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

