ALTER TABLE [dbo].[c_External_Source]
    ADD CONSTRAINT [PK_c_c_Ext_Source_40] PRIMARY KEY CLUSTERED ([external_source] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

