ALTER TABLE [dbo].[c_Chart_Section_Page]
    ADD CONSTRAINT [PK_c_Chart_Section_Page_40] PRIMARY KEY CLUSTERED ([chart_id] ASC, [section_id] ASC, [page_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

