ALTER TABLE [dbo].[c_Table_Fkey]
    ADD CONSTRAINT [PK_c_Table_Fkey_21a] PRIMARY KEY CLUSTERED ([cpr_table] ASC, [fkey_sequence] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

