ALTER TABLE [dbo].[c_Workplan_Step]
    ADD CONSTRAINT [PK_c_Workplan_Step] PRIMARY KEY CLUSTERED ([workplan_id] ASC, [workplan_step_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

