ALTER TABLE [dbo].[c_Allergy_Drug]
    ADD CONSTRAINT [PK_c_Allergy_Drug_21] PRIMARY KEY CLUSTERED ([assessment_id] ASC, [drug_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

