ALTER TABLE [dbo].[c_Component_Version]
    ADD CONSTRAINT [PK_c_Component_Version] PRIMARY KEY CLUSTERED ([component_id] ASC, [version] ASC) WITH (FILLFACTOR = 70, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

