ALTER TABLE [dbo].[c_Document_Type]
    ADD CONSTRAINT [PK_c_Document_Type_40] PRIMARY KEY CLUSTERED ([document_type] ASC) WITH (FILLFACTOR = 70, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

