ALTER TABLE [dbo].[c_Authority_Type]
    ADD CONSTRAINT [PK_c_Authority_Type] PRIMARY KEY CLUSTERED ([authority_type] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

