ALTER TABLE [dbo].[c_Prescription_Format]
    ADD CONSTRAINT [PK_c_Prescription_Format_40] PRIMARY KEY CLUSTERED ([dataobject] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

