ALTER TABLE [dbo].[c_Database_System]
    ADD CONSTRAINT [PK_c_Database_System_40] PRIMARY KEY CLUSTERED ([system_id] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

