ALTER TABLE [dbo].[c_Observation_Type]
    ADD CONSTRAINT [PK_c_Observation_Type_01] PRIMARY KEY CLUSTERED ([observation_type] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

