ALTER TABLE [dbo].[c_Procedure_Category]
    ADD CONSTRAINT [PK_c_Proc_Cat_27] PRIMARY KEY CLUSTERED ([procedure_type] ASC, [procedure_category_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

