ALTER TABLE [dbo].[c_XML_Code_Domain_Item]
    ADD CONSTRAINT [PK_c_XML_Code_Domain_Item_40] PRIMARY KEY NONCLUSTERED ([owner_id] ASC, [code_domain] ASC, [code_domain_item_id] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

