ALTER TABLE [dbo].[c_XML_Code]
    ADD CONSTRAINT [PK_c_XML_Code_40] PRIMARY KEY NONCLUSTERED ([code_id] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

