ALTER TABLE [dbo].[em_Visit_Code_Group]
    ADD CONSTRAINT [PK_em_Visit_Code_Group_40] PRIMARY KEY CLUSTERED ([visit_code_group] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

