ALTER TABLE [dbo].[em_Risk]
    ADD CONSTRAINT [PK_em_Risk] PRIMARY KEY CLUSTERED ([risk_level] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

