ALTER TABLE [dbo].[em_Component_Level]
    ADD CONSTRAINT [PK_em_History_Type_Level] PRIMARY KEY CLUSTERED ([em_component] ASC, [em_component_level] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

