ALTER TABLE [dbo].[em_Component]
    ADD CONSTRAINT [PK_em_History_Type] PRIMARY KEY CLUSTERED ([em_component] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

