ALTER TABLE [dbo].[c_Nomenclature_Medcin]
    ADD CONSTRAINT [PK_id] PRIMARY KEY NONCLUSTERED ([id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

