ALTER TABLE [dbo].[o_Message_Log]
    ADD CONSTRAINT [PK_message_log_21] PRIMARY KEY CLUSTERED ([message_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

