ALTER TABLE [dbo].[o_Users]
    ADD CONSTRAINT [PK_o_users_40] PRIMARY KEY CLUSTERED ([user_id] ASC, [computer_id] ASC) WITH (FILLFACTOR = 25, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

