ALTER TABLE [dbo].[o_User_Privilege]
    ADD CONSTRAINT [PK_o_User_Privilege_40] PRIMARY KEY CLUSTERED ([office_id] ASC, [user_id] ASC, [privilege_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

