ALTER TABLE [dbo].[o_Log]
    ADD CONSTRAINT [PK_o_log_21] PRIMARY KEY CLUSTERED ([log_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

