ALTER TABLE [dbo].[o_Computer_Printer]
    ADD CONSTRAINT [PK_o_Computer_Printer_40] PRIMARY KEY CLUSTERED ([computer_id] ASC, [printer_sequence] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

