ALTER TABLE [dbo].[o_Service_Schedule]
    ADD CONSTRAINT [PK_o_Service_Schedule_40] PRIMARY KEY CLUSTERED ([user_id] ASC, [service_sequence] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

