ALTER TABLE [dbo].[c_Workplan_Step_Room]
    ADD CONSTRAINT [PK_o_Workplan_Step_Room] PRIMARY KEY CLUSTERED ([workplan_id] ASC, [step_number] ASC, [office_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

