ALTER TABLE [dbo].[o_Rooms]
    ADD CONSTRAINT [PK_o_Rooms_40] PRIMARY KEY CLUSTERED ([room_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

