ALTER TABLE [dbo].[o_User_Logins]
    ADD CONSTRAINT [PK_o_user_logins_40] PRIMARY KEY CLUSTERED ([user_id] ASC, [action_id] ASC) WITH (FILLFACTOR = 50, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

