ALTER TABLE [dbo].[o_Service]
    ADD CONSTRAINT [PK_o_Service_01] PRIMARY KEY CLUSTERED ([service] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

