ALTER TABLE [dbo].[o_office]
    ADD CONSTRAINT [PK_o_Office_21] PRIMARY KEY CLUSTERED ([office_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

