ALTER TABLE [dbo].[o_box]
    ADD CONSTRAINT [PK_o_box_box_id] PRIMARY KEY CLUSTERED ([box_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

