ALTER TABLE [dbo].[o_Treatment_Service]
    ADD CONSTRAINT [PK_o_Treatment_Service_1__12] PRIMARY KEY CLUSTERED ([treatment_type] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

