ALTER TABLE [dbo].[o_Report_Trigger]
    ADD CONSTRAINT [PK_o_report_trigger_1__10] PRIMARY KEY CLUSTERED ([report_type] ASC, [event] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

