ALTER TABLE [dbo].[o_Computers]
    ADD CONSTRAINT [PK_o_computers_40] PRIMARY KEY CLUSTERED ([computer_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

