ALTER TABLE [dbo].[o_Groups]
    ADD CONSTRAINT [PK_o_Groups_1__12] PRIMARY KEY CLUSTERED ([group_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

