ALTER TABLE [dbo].[o_printer]
    ADD CONSTRAINT [PK_o_printer_1__10] PRIMARY KEY CLUSTERED ([printer_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

