ALTER TABLE [dbo].[o_Server_Component]
    ADD CONSTRAINT [PK_o_Server_Component_403] PRIMARY KEY CLUSTERED ([service_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

