ALTER TABLE [dbo].[o_Service_Attribute]
    ADD CONSTRAINT [PK_o_Service_Attribute_40] PRIMARY KEY CLUSTERED ([service] ASC, [attribute_sequence] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

