ALTER TABLE [dbo].[o_Service_Trigger]
    ADD CONSTRAINT [PK_o_Service_Trigger_1__10] PRIMARY KEY CLUSTERED ([service] ASC, [treatment_type] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

