ALTER TABLE [dbo].[o_Message_Subscription]
    ADD CONSTRAINT [PK_o_Message_Subscription1__13] PRIMARY KEY CLUSTERED ([subscription_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

