ALTER TABLE [dbo].[o_User_Service_Lock]
    ADD CONSTRAINT [PK_o_User_Service_Lock] PRIMARY KEY CLUSTERED ([patient_workplan_item_id] ASC) WITH (FILLFACTOR = 25, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

