ALTER TABLE [dbo].[p_Patient_Guarantor]
    ADD CONSTRAINT [PK_p_Patient_Guarantor_21] PRIMARY KEY CLUSTERED ([cpr_id] ASC, [guarantor_sequence] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

