ALTER TABLE [dbo].[p_Assessment]
    ADD CONSTRAINT [PK_p_Assessment_1_40] PRIMARY KEY CLUSTERED ([cpr_id] ASC, [problem_id] ASC, [diagnosis_sequence] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

