ALTER TABLE [dbo].[p_Patient_Alias]
    ADD CONSTRAINT [PK_p_Patient_Alias] PRIMARY KEY NONCLUSTERED ([cpr_id] ASC, [alias_type] ASC, [alias_sequence] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

