ALTER TABLE [dbo].[p_Patient_WP_Item]
    ADD CONSTRAINT [PK_p_Patient_WP_Item] PRIMARY KEY NONCLUSTERED ([patient_workplan_item_id] ASC) WITH (FILLFACTOR = 70, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [Workflow];

