ALTER TABLE [dbo].[p_Attachment]
    ADD CONSTRAINT [PK_p_Attachment_40] PRIMARY KEY NONCLUSTERED ([attachment_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

