ALTER TABLE [dbo].[p_Patient_WP]
    ADD CONSTRAINT [PK_p_Patient_Workplan] PRIMARY KEY NONCLUSTERED ([patient_workplan_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [Workflow];

