ALTER TABLE [dbo].[r_Efficacy_Data]
    ADD CONSTRAINT [PK_r_Efficacy_Data_40] PRIMARY KEY CLUSTERED ([clinicaleventid] ASC) WITH (FILLFACTOR = 70, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

