ALTER TABLE [dbo].[c_Report_Params]
    ADD CONSTRAINT [PK_Rep_params_21] PRIMARY KEY CLUSTERED ([report_id] ASC, [param_sequence] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

