ALTER TABLE [dbo].[tmp_specialties]
    ADD CONSTRAINT [PK_tmp_specialties] PRIMARY KEY CLUSTERED ([user_id] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

