ALTER TABLE [dbo].[u_Top_20]
    ADD CONSTRAINT [PK_u_Top_20_40_01] PRIMARY KEY CLUSTERED ([user_id] ASC, [top_20_code] ASC, [top_20_sequence] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

