ALTER TABLE [dbo].[u_assessment_treat_definition]
    ADD CONSTRAINT [PK_u_ass_treat_def] PRIMARY KEY NONCLUSTERED ([definition_id] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

