ALTER TABLE [dbo].[u_Exam_Definition]
    ADD CONSTRAINT [PK_u_Exam_Def_40] PRIMARY KEY CLUSTERED ([exam_sequence] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

