ALTER TABLE [dbo].[c_Workplan_Type]
    ADD CONSTRAINT [PK_workplan_type_403] PRIMARY KEY CLUSTERED ([workplan_type] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

