ALTER TABLE [dbo].[x_MedMan_Arrived]
    ADD CONSTRAINT [PK_x_MedMan_Arrived] PRIMARY KEY CLUSTERED ([billing_id] ASC, [message_id] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

