ALTER TABLE [dbo].[x_ID_Lists]
    ADD CONSTRAINT [PK_x_ID_Lists] PRIMARY KEY CLUSTERED ([IDList] ASC, [ID] ASC) WITH (FILLFACTOR = 70, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

