ALTER TABLE [dbo].[x_Integrations]
    ADD CONSTRAINT [PK_x_Integrations] PRIMARY KEY CLUSTERED ([billing_system] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

