ALTER TABLE [dbo].[x_External_Application]
    ADD CONSTRAINT [PK_x_External_Application_40] PRIMARY KEY CLUSTERED ([external_application_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

