ALTER TABLE [dbo].[x_Property_Exception]
    ADD CONSTRAINT [PK_x_Property_Exception] PRIMARY KEY CLUSTERED ([spid] ASC) WITH (FILLFACTOR = 70, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

