ALTER TABLE [dbo].[x_Performance_Log]
    ADD CONSTRAINT [PK_x_Performance_Log_21] PRIMARY KEY CLUSTERED ([log_id] ASC) WITH (FILLFACTOR = 100, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

