ALTER TABLE [dbo].[x_Message_Type]
    ADD CONSTRAINT [PK_x_Message_Type_40] PRIMARY KEY CLUSTERED ([message_type] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

