
UPDATE c_Drug_Formulation SET form_descr = 'Injzathine 1.2 Mega International Units Injection' WHERE form_rxcui = 'KEB12387'
UPDATE c_Drug_Formulation SET form_descr = 'Rhinathiol 250 MG in 5 ML Oral Solution' WHERE form_rxcui = 'KEB5514'
UPDATE c_Drug_Formulation SET form_descr = 'carbocisteine 250 MG in 5 ML Oral Solution' WHERE form_rxcui = 'KEG5514'
UPDATE c_Drug_Formulation SET form_descr = 'Rhinathiol 100 MG in 5 ML Oral Solution' WHERE form_rxcui = 'KEB5701'
UPDATE c_Drug_Formulation SET form_descr = 'carbocisteine 100 MG in 5 ML Oral Solution' WHERE form_rxcui = 'KEG5701'

UPDATE c_Drug_Formulation SET form_descr = 'Corither 100 MG/ML Injection Solution' WHERE form_rxcui = 'KEB12301'
UPDATE c_Drug_Formulation SET form_descr = 'Beclomin HFA 250 MCG Metered Dose Inhaler, 200 Puffs' WHERE form_rxcui = 'KEB1839'
UPDATE c_Drug_Formulation SET form_descr = 'Lonart Dispersible 20 MG / 120 MG Dispersible Oral Tablet' WHERE form_rxcui = 'KEB405'
UPDATE c_Drug_Formulation SET form_descr = 'Diclo-Denk 100 MG Retard Delayed Release Oral Tablet' WHERE form_rxcui = 'KEB3137'
UPDATE c_Drug_Formulation SET form_descr = 'Lantus 100 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEB5916'
UPDATE c_Drug_Formulation SET form_descr = 'Lantus Solostar 100 UNITS/ML in 3 ML Prefilled Pen' WHERE form_rxcui = 'KEB5916PF'
UPDATE c_Drug_Formulation SET form_descr = 'Lantus 100 UNT/ML Injectable Solution' WHERE form_rxcui = 'KEB5912'
UPDATE c_Drug_Formulation SET form_descr = 'HumaLOG Mix-25 100 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEB1211'
UPDATE c_Drug_Formulation SET form_descr = 'HumaLOG Mix-50 100 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEB1213'
UPDATE c_Drug_Formulation SET form_descr = 'HumaLOG Mix-25 100 UNITS/ML Injectable Suspension' WHERE form_rxcui = 'KEB1207'
UPDATE c_Drug_Formulation SET form_descr = 'HumaLOG Mix 25/75 in 3 ML Kwikpen' WHERE form_rxcui = 'KEB9230'
UPDATE c_Drug_Formulation SET form_descr = 'HumaLOG 100 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEB1202'
UPDATE c_Drug_Formulation SET form_descr = 'HumaLOG 100 UNITS/ML Injectable Solution' WHERE form_rxcui = 'KEB1148'
UPDATE c_Drug_Formulation SET form_descr = 'HumuLIN N 100 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEB1235'
UPDATE c_Drug_Formulation SET form_descr = 'HumuLIN 70/30 100 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEB1217'
UPDATE c_Drug_Formulation SET form_descr = 'HumuLIN 70/30 100 UNITS/ML Injectable Suspension' WHERE form_rxcui = 'KEB1219'
UPDATE c_Drug_Formulation SET form_descr = 'HumuLIN N 100 UNITS/ML Injectable Suspension in 10 ML Vial' WHERE form_rxcui = 'KEB1239'
UPDATE c_Drug_Formulation SET form_descr = 'HumuLIN N 100 UNITS/ML Injectable Suspension in 4 ML Vial' WHERE form_rxcui = 'KEB1239-4ML'
UPDATE c_Drug_Formulation SET form_descr = 'HumuLIN R 100 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEB1241'
UPDATE c_Drug_Formulation SET form_descr = 'HumuLIN R 100 UNITS/ML Injectable Solution in 10 ML Vial' WHERE form_rxcui = 'KEB1246'
UPDATE c_Drug_Formulation SET form_descr = 'HumuLIN R 100 UNITS/ML Injectable Solution in 4 ML Vial' WHERE form_rxcui = 'KEB1246-4ML'
UPDATE c_Drug_Formulation SET form_descr = 'InSUMan basal 100 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEB5907'
UPDATE c_Drug_Formulation SET form_descr = 'InSUMan basal 100 UNITS/ML Injectable Suspension' WHERE form_rxcui = 'KEB5907V'
UPDATE c_Drug_Formulation SET form_descr = 'InSUMan Rapid 100 UNITS/ML Insulin Human in 10 ML Vial' WHERE form_rxcui = 'KEB10907'
UPDATE c_Drug_Formulation SET form_descr = 'InSUMan Comb-30/70 in 3 ML Cartridge' WHERE form_rxcui = 'KEB10906'
UPDATE c_Drug_Formulation SET form_descr = 'InSULAtard Penfill 100 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEB229'
UPDATE c_Drug_Formulation SET form_descr = 'InSULAtard 100 UNITS/ML Injectable Suspension' WHERE form_rxcui = 'KEB217'
UPDATE c_Drug_Formulation SET form_descr = 'InSULAtard FlexPen 100 UNITS/ML in 3 ML Prefilled Pen' WHERE form_rxcui = 'KEB229PF'
UPDATE c_Drug_Formulation SET form_descr = 'Ventolin Rotacaps 200 MCG Inhalant Powder Capsule' WHERE form_rxcui = 'KEB4558'
UPDATE c_Drug_Pack SET descr = 'Ventolin Rotacaps 200 MCG Inhalant Powder Capsule, 100 Capsules' WHERE rxcui = 'KEB4558-BPCK-100'
UPDATE c_Drug_Pack SET descr = 'Ventolin Rotacaps 200 MCG Inhalant Powder Capsule, 128 Capsules' WHERE rxcui = 'KEB4558-BPCK-128'
UPDATE c_Drug_Formulation SET form_descr = 'Ticamet HFA 250 MCG / 25 MCG Metered Dose Inhaler 120 Puffs' WHERE form_rxcui = 'KEB2286'
UPDATE c_Drug_Formulation SET form_descr = 'beclometasone dipropionate 250 MCG/PUFF Metered Dose Inhaler, 200 Puffs' WHERE form_rxcui = 'KEG1839'
UPDATE c_Drug_Formulation SET form_descr = 'Azmasol HFA 100 MCG/ACTUAT Metered Dose Inhaler' WHERE form_rxcui = 'KEB2307'
UPDATE c_Drug_Formulation SET form_descr = 'Bexitrol-F HFA 25 MCG / 250 MCG Metered Dose Inhaler, 120 Metered Inhalations' WHERE form_rxcui = 'KEB2318'
UPDATE c_Drug_Formulation SET form_descr = 'Decomit HFA 100 MCG/ACTUAT Metered Dose Inhaler, 200 Metered Inhalations' WHERE form_rxcui = 'KEB2342'
UPDATE c_Drug_Formulation SET form_descr = 'Decomit HFA 50 MCG/ACTUAT Metered Dose Inhaler, 200 Metered Inhalations' WHERE form_rxcui = 'KEB2347'
UPDATE c_Drug_Formulation SET form_descr = 'salbutamol sulphate 100 MCG/ACTUAT Metered Dose Inhaler, 200 Metered Inhalations' WHERE form_rxcui = 'KEG2307'
UPDATE c_Drug_Formulation SET form_descr = 'salmeterol 25 MCG/ACTUAT / fluticasone 125 MCG/ACTUAT Metered Dose Inhaler, 120 Metered Inhalations' WHERE form_rxcui = 'KEG2315'
UPDATE c_Drug_Formulation SET form_descr = 'salmeterol 25 MCG/ACTUAT / fluticasone propionate 250 MCG/ACTUAT Metered Dose Inhaler, 120 Metered Inhalations' WHERE form_rxcui = 'KEG2318'
UPDATE c_Drug_Formulation SET form_descr = 'beclomethasone dipropionate 100 MCG/ACTUAT Inhaler, 200 Metered Inhalations' WHERE form_rxcui = 'KEG2342'
UPDATE c_Drug_Formulation SET form_descr = 'beclomethasone dipropionate 50 MCG/ACTUAT Inhaler, 200 Metered Inhalations' WHERE form_rxcui = 'KEB2347'
UPDATE c_Drug_Formulation SET form_descr = 'ACTrapid Penfill 100 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEB282'
UPDATE c_Drug_Formulation SET form_descr = 'ACTrapid 100 UNITS/ML Injectable Solution' WHERE form_rxcui = 'KEB214'
UPDATE c_Drug_Formulation SET form_descr = 'ACTrapid FlexPen 100 UNITS/ML in 3 ML Prefilled  Pen' WHERE form_rxcui = 'KEB282PF'
UPDATE c_Drug_Formulation SET form_descr = 'MIXTArd-30 Penfill 100 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEB281'
UPDATE c_Drug_Formulation SET form_descr = 'MIXTArd-30 FlexPen 100 UNITS/ML in 3 ML Prefilled Pen' WHERE form_rxcui = 'KEB281PF'
UPDATE c_Drug_Formulation SET form_descr = 'MIXTArd-30 100 UNITS/ML Injectable Suspension' WHERE form_rxcui = 'KEB191'
UPDATE c_Drug_Formulation SET form_descr = 'Lanoxin Elixir 0.05 MG/ML Oral Solution' WHERE form_rxcui = 'KEB3129'
UPDATE c_Drug_Formulation SET form_descr = 'Esose 20 MG Gastro Resistant Oral Tablet' WHERE form_rxcui = 'KEB6289'
UPDATE c_Drug_Formulation SET form_descr = 'Seretide Accuhaler/Diskus 500 MCG/50 MCG, Dry Powder Inhaler, 60 inhalations' WHERE form_rxcui = 'KEB3488'
UPDATE c_Drug_Formulation SET form_descr = 'Seretide Accuhaler/Diskus 250 MCG/50 MCG, Dry Powder Inhaler, 60 inhalations' WHERE form_rxcui = 'KEB3496'
UPDATE c_Drug_Formulation SET form_descr = 'Nurofen for Children 100 MG in 5 ML Oral Suspension' WHERE form_rxcui = 'KEB16472'
UPDATE c_Drug_Formulation SET form_descr = 'NovoMIX-30 100 UNITS/ML Injectable Suspension' WHERE form_rxcui = 'KEB283V'
UPDATE c_Drug_Formulation SET form_descr = 'NovoMIX-30 FlexPen 100 UNITS/ML in 3 ML Prefilled Pen' WHERE form_rxcui = 'KEB283PF'
UPDATE c_Drug_Formulation SET form_descr = 'NovoMIX-30 Penfill 100 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEB283'
UPDATE c_Drug_Formulation SET form_descr = 'Panadol Actifast Soluble 500 MG Effervescent Oral Tablet' WHERE form_rxcui = 'KEB4005'
UPDATE c_Drug_Formulation SET form_descr = 'Sulbacin 1.5 GM Injection' WHERE form_rxcui = 'KEB13529'
UPDATE c_Drug_Formulation SET form_descr = 'Ciloxan 0.3 % Eye Drops Solution' WHERE form_rxcui = 'KEB1580'
UPDATE c_Drug_Formulation SET form_descr = 'Probeta-N Drops 0.1 % / 0.5 % Nasal Solution' WHERE form_rxcui = 'KEB4094C'
UPDATE c_Drug_Formulation SET form_descr = 'Colimix 5 MG / 50 MG in 5 ML Oral Suspension' WHERE form_rxcui = 'KEB772'
UPDATE c_Drug_Formulation SET form_descr = 'Arip 15 MG Dispersible Oral Tablet' WHERE form_rxcui = 'KEB11718'
UPDATE c_Drug_Formulation SET form_descr = 'cholecalciferol 400 IU/ML Oral Drops' WHERE form_rxcui = 'KEG14014'
UPDATE c_Drug_Formulation SET form_descr = 'NexIUM I.V. 40 MG Injection,esomeprazole sodium 40 MG Injection' WHERE form_rxcui = 'KEB7721'
UPDATE c_Drug_Formulation SET form_descr = 'Levemir Penfill 100 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEB297'
UPDATE c_Drug_Formulation SET form_descr = 'Levemir 100 UNITS/ML Injectable Solution' WHERE form_rxcui = 'KEB297V'
UPDATE c_Drug_Formulation SET form_descr = 'Unasyn 1.5 GM Injection' WHERE form_rxcui = 'KEB5216'
UPDATE c_Drug_Formulation SET form_descr = 'Nycostat 100,000 International Units per ML Oral Suspension' WHERE form_rxcui = 'KEB5445'
UPDATE c_Drug_Formulation SET form_descr = 'S-Film 50 MG Disintegrating Oral Strip' WHERE form_rxcui = 'KEB11901'
UPDATE c_Drug_Formulation SET form_descr = 'sildenafil citrate 50 MG Disintegrating Oral Strip' WHERE form_rxcui = 'KEG11901'
UPDATE c_Drug_Formulation SET form_descr = 'Lorata 10 MG Oral Tablet', ingr_rxcui = 'KEBI4536' WHERE form_rxcui = 'KEB4526'
UPDATE c_Drug_Formulation SET form_descr = 'HepaMerz 3 GM in 5 GM Granules for Oral Solution' WHERE form_rxcui = 'KEB7212'
UPDATE c_Drug_Formulation SET form_descr = 'L-Ornithine-L-Aspartate 3 GM in 5 GM Granules for Oral Solution' WHERE form_rxcui = 'KEG7212'
UPDATE c_Drug_Formulation SET form_descr = 'Sayana Medroxyprogesterone Acetate 104 MG in 0.65 ML in Prefilled Syringe' WHERE form_rxcui = 'KEB8413'
UPDATE c_Drug_Formulation SET form_descr = 'soluble insulin 30 UNITS/ML / crystalline protamine insulin 70 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEG10906'
UPDATE c_Drug_Formulation SET form_descr = 'insulin lispro 25 UNITS/ML / insulin lispro protamine 75 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEG1211'
UPDATE c_Drug_Formulation SET form_descr = 'insulin lispro 50 UNITS/ML / insulin lispro protamine 50 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEG1213'
UPDATE c_Drug_Formulation SET form_descr = 'isophane (NPH) insulin, human 70 UNITS/ML / soluble insulin, human 30 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEG1217'
UPDATE c_Drug_Formulation SET form_descr = 'isophane (NPH) insulin, human 100 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEG1235'
UPDATE c_Drug_Formulation SET form_descr = 'soluble insulin, human 30 UNITS/ML / isophane (NPH) insulin, human 70 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEG281'
UPDATE c_Drug_Formulation SET form_descr = 'insulin aspart 30 UNITS/ML / insulin aspart protamine crystals 70 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEG283'
UPDATE c_Drug_Formulation SET form_descr = 'NovoRAPID FlexPen 100 UNITS/ML in 3 ML Prefilled Pen' WHERE form_rxcui = 'KEB289PF'
UPDATE c_Drug_Formulation SET form_descr = 'NovoRAPID 100 UNITS/ML in 10 ML Vial' WHERE form_rxcui = 'KEB289V'
UPDATE c_Drug_Formulation SET form_descr = 'soluble insulin, human 100 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEG1241'
UPDATE c_Drug_Formulation SET form_descr = 'soluble insulin, human 100 UNITS/ML in 3 ML Prefilled Pen' WHERE form_rxcui = 'KEG282PF'
UPDATE c_Drug_Formulation SET form_descr = 'insulin detemir 100 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEG297'
UPDATE c_Drug_Formulation SET form_descr = 'insulin glargine 100 UNITS/ML in 3 ML Cartridge' WHERE form_rxcui = 'KEG5916'
UPDATE c_Drug_Formulation SET form_descr = 'lactulose 10 GM / ispaghula husk 3.5 GM Granules for Oral Solution' WHERE form_rxcui = 'KEG9258'
UPDATE c_Drug_Formulation SET form_descr = 'cholecalciferol 400 IU/ML Oral Drops' WHERE form_rxcui = 'KEG14014'
UPDATE c_Drug_Formulation SET form_descr = 'benzathine penicillin 1.2 Million UNITS Injection' WHERE form_rxcui = 'KEG12387'

UPDATE c_Drug_Formulation 
SET form_descr = REPLACE(form_descr, ' hydrochloride ', ' HCl ')
WHERE form_descr like '% hydrochloride %'
-- 103

exec sp_remove_epro_drug 0, 'KE', NULL, NULL, NULL, 'KEB12082', NULL
exec sp_remove_epro_drug 0, 'KE', NULL, NULL, NULL, 'KEB10671', NULL
exec sp_remove_epro_drug 0, 'KE', NULL, NULL, NULL, 'KEB3205', NULL
exec sp_remove_epro_drug 0, 'KE', NULL, NULL, NULL, 'KEB4726', NULL

