-- misspelled in Tall Man Lettering List report, Dec 2013, NZ HQSC
DELETE FROM c_Drug_Tall_Man
WHERE spelling COLLATE SQL_Latin1_General_CP1_CI_AS IN (
'amiSULPIRIDe',
'cLOMIPHEne',
'fuARIx',
'fupENTHIXOL',
'fupHENAZINE',
'fuVAx',
'fuVOXAMine',
'MOXIfoxacin',
'NORfoxacin',
'SgliBENCLAMide')

-- From https://www.hqsc.govt.nz/our-programmes/medication-safety/publications-and-resources/publication/1281/
-- dated 2020-06

create table #temp (term varchar(50))

insert into #temp 
VALUES
('aFATinib'),
('aLEMTUzumab'),
('ALKeran'),
('aLLOPURINol'),
('amINOPHYLLIne'),
('amIODAROne'),
('amiSULPRIDe'),
('amITRIPTYLIne'),
('amLODIPIne'),
('aPomine'),
('arATAC'),
('arOPAX'),
('aTENOLol'),
('aTEZOLIzumab'),
('aTRopt'),
('avaSTIN'),
('avaXIM'),
('aVomine'),
('aXITinib'),
('azATHIOPRINE'),
('azITHROMYCIN'),
('aZopt'),
('BENZATHINE benzylpenicillin'),
('beVACizumab '),
('bisACODYl'),
('bisOPROLOl'),
('buDESONide'),
('buMETANide'),
('buPROPION'),
('buSPIRONE'),
('caLTRate'),
('caPTOPRIl'),
('caRAFate'),
('CARBAMazepine'),
('carbIMAZOLe'),
('cARBOplatin'),
('caRVEDILOl'),
('cefaCLOR '),
('cefaLEXin'),
('cefaZOLin'),
('cefEPIME'),
('cefOTAXIME'),
('cefOXITIN'),
('ceftAROLine'),
('cefTAZIDIME'),
('cefTRIAXONE'),
('cefUROXIME'),
('celAPRAM'),
('celEBREX'),
('cephaLEXin'),
('cephaZOLin'),
('CETUximab'),
('cHLORPROMAZIne'),
('ciclosPORIN'),
('ciprAMIL'),
('cIPROFLOXAcin'),
('ciprOXIN'),
('cISplatin'),
('cLARITHROMYcin'),
('clINDAmycin'),
('cLOMIFEne'),
('cLOMIPRAMIne'),
('CLONazepam'),
('cloNIDine'),
('cLOZAPine'),
('cOBIMEtinib'),
('coUMADIN'),
('coVERSYL'),
('cyclIZINE'),
('cyclOBLASTIN'),
('CYCLOPHOSPHamide'),
('cyclosERINE'),
('cyclosPORIN'),
('daBRAFEnib'),
('daCTINomycin'),
('daPTomycin'),
('daSATinib'),
('DAUNOrubicin'),
('DEPO-medrol'),
('depo-PROVERA'),
('DIazepam'),
('dIGOXin'),
('diPYRIDAMOLe'),
('diSOPYRAMIDe'),
('doBUTamine'),
('DOCEtaxel'),
('doPamine'),
('doTHIEpin'),
('dOXAZOSin'),
('doXEpin'),
('DOXOrubicin'),
('DULoxetine'),
('ERYthromycin'),
('fluARIx'),
('flupENTIXOL'),
('flupHENAZINE'),
('fluVAx'),
('fluVOXAMine'),
('foliNIc acid'),
('gliBENCLAMide'),
('gliCLAZide'),
('gliPIZide'),
('humALOG'),
('humULIN'),
('hyoscine BUTYLbromide'),
('hyoscine HYDRObromide'),
('IDArubicin'),
('IFOSFamide'),
('imUPRine'),
('INDEral'),
('INFLIximab'),
('isopto CARpine'),
('isopto HOMATROpine'),
('ISOtretinoin'),
('januMET'),
('januVIA'),
('ketALAR'),
('ketOROLAC'),
('laMICTAl'),
('laMISIl'),
('lamIVUDine'),
('lamOTRIGine'),
('lanTUs'),
('lanVIs'),
('laPAtinib'),
('laRGACTIl'),
('LEUKeran'),
('LORazepam'),
('loxaLATe'),
('loxaMINe'),
('maxiDEX'),
('maxiTROL'),
('meDROXYPROGESTERone'),
('m-eNALAPRIL'),
('mercaptAMine (cysteamine)'),
('mercaptOPURine'),
('m-eSLON'),
('methADONe'),
('metHOTREXATe'),
('methYLPHENIDATe'),
('methylprednisolone ACETate'),
('methylprednisolone SODIUM SUCCINate'),
('metOCLOPRAMIDe'),
('metoPROLOL'),
('MOXIfloxacin'),
('MYLeran'),
('nalOXone'),
('nalTREXone'),
('neO-MERCAZOLe'),
('NEOral'),
('neUROKARe'),
('niFEDIPine'),
('niMODIPine'),
('NITRazepam'),
('NORfloxacin'),
('norMISON'),
('norVASC'),
('novoMIX'),
('novoRAPID'),
('novoSEVEN'),
('oBINUTUZumab'),
('oMALizumab'),
('OXazepam'),
('OXCARBazepine'),
('oxyCONTIN'),
('oxyNORM'),
('PACLItaxel'),
('PARoxetine'),
('pAZOPanib'),
('pegFILGRASTIM'),
('pegINTERFERON'),
('penicillAMINE'),
('pERTUZumab'),
('PHENOXYMETHylpenicillin'),
('prEDNISone'),
('primaCIN'),
('primaCOR'),
('primAQUIne'),
('primaXIN'),
('primIDOne'),
('proCHLORPERazine'),
('procYCLIDine'),
('proGRAF'),
('proMETHazine'),
('propOFol'),
('propRANOLol'),
('proZAC'),
('QUETIAPine'),
('quINine'),
('rifaMPICin'),
('rifaXIMin'),
('riSPERIDONe'),
('RITUximab'),
('rOPINIROLe'),
('SERTRALine'),
('SIrolimus'),
('siTagliptin'),
('solu-CORTEF'),
('SOLU-medrol'),
('soRAFENib'),
('sulfaDIazine'),
('sulfaSALazine'),
('sUMATRIPTAn'),
('sUNITinib'),
('TACrolimus'),
('TAMoxifen'),
('tEMOdal'),
('toFRANIL'),
('toPAMAX'),
('tRAMadol'),
('trimEPRAZINE'),
('trimETHOPRIM'),
('valAciclovir'),
('valGANciclovir'),
('vinBLASTine'),
('vinCRISTine'),
('vinORELBine'),
('yasMIN'),
('yaZ')

INSERT INTO c_Drug_Tall_Man
select term from #temp where term COLLATE SQL_Latin1_General_CP1_CI_AS 
not in (select spelling COLLATE SQL_Latin1_General_CP1_CI_AS from c_Drug_Tall_Man)
-- 219 row(s) affected)

update statistics c_Drug_Tall_Man

UPDATE f
SET form_descr = dbo.fn_tallman(form_descr)
-- SELECT form_descr, dbo.fn_tallman(form_descr)
FROM c_Drug_Formulation f
WHERE dbo.fn_needs_tallman(form_descr) = 1
-- 257

UPDATE f
SET generic_name = dbo.fn_tallman(generic_name)
-- SELECT generic_name, dbo.fn_tallman(generic_name)
FROM c_Drug_Generic f
WHERE dbo.fn_needs_tallman(generic_name) = 1
-- 4

UPDATE f
SET brand_name = dbo.fn_tallman(brand_name)
-- SELECT brand_name, dbo.fn_tallman(brand_name)
FROM c_Drug_Brand f
WHERE dbo.fn_needs_tallman(brand_name) = 1
-- 55

UPDATE f
SET generic_name = dbo.fn_tallman(generic_name)
-- SELECT generic_name, dbo.fn_tallman(generic_name)
FROM c_Drug_Definition f
WHERE dbo.fn_needs_tallman(generic_name) = 1
-- 1

UPDATE f
SET common_name = dbo.fn_tallman(common_name)
-- SELECT common_name, dbo.fn_tallman(common_name)
FROM c_Drug_Definition f
WHERE dbo.fn_needs_tallman(common_name) = 1
-- 21
