; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "EncounterPRO-OS SQL Server Express"

; Source Root
!define SOURCE_ROOT "\\ICT1\ICTFileStore1\Open Source\Builds"

; Component Versions
!define SQLServerExpressVersion   "2008R2"

; Other definitions
!define PRODUCT_VERSION "${SQLServerExpressVersion}"
!define PRODUCT_PUBLISHER "EncounterPRO.ORG"
!define PRODUCT_WEB_SITE "http://www.encounterpro.org"
!define Required_Dotnet_VERSION   'v4.0'

; Module Locations
!define SQLServerExpress_SOURCE  '${SOURCE_ROOT}\3rd Party Software\MIcrosoft SQL Server Express'


; Installation constants
!define COMMONFILES_TARGET "EncounterPRO-OS"

; Include install functions
!include "..\plugins\eproinstallfunctions.nsh"

; FileFunc
!include "FileFunc.nsh"
!insertmacro GetFileName
!insertmacro GetFileVersion  

; InstallLib support
!include Library.nsh

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\modern-install.ico"

    ; Welcome page
;    !insertmacro MUI_PAGE_WELCOME
    ; License page
;    !insertmacro MUI_PAGE_LICENSE "\\techserv\builds\Common Files\Eula.txt"
    
    ; Instfiles page
    !insertmacro MUI_PAGE_INSTFILES
    ; Finish page
;    !insertmacro MUI_PAGE_FINISH

; Language files
!insertmacro MUI_LANGUAGE "English"

; Reserve Files

; MUI end ------

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "EproSQLx64.exe"
InstallDir "$PROGRAMFILES\EncounterPRO.ORG\EncounterPRO-OS\SQLServerExpressInstall"
ShowInstDetails show
AutoCloseWindow true

Function PreInstall
  Call CheckBitness
  ;MessageBox MB_OK "$Bitness bit OS"

  Call getWindowsVersion
  ${If} $WinVer = 'not NT'
      MessageBox MB_OK "This program Windows XP, Windows 2003 or Later.  Setup cannot continue."
      Abort "This program Windows XP, Windows 2003 or Later."
  ${EndIf}
  ;MessageBox MB_OK "$WinVer"
  
  ${CheckDLLVersion} "$SYSDIR\MSI.dll" "4.5" $R0
  ${If} $R0 != 'Yes'
      MessageBox MB_YESNO|MB_ICONEXCLAMATION "This program requires the Windows Installer to be at least version 4.5.  Do you wish to download the required Windows Installer version now?" IDYES OpenBrowsermsi45 IDNO GiveUpNowmsi45
      
      OpenBrowsermsi45:
      ${OpenURL} "http://www.microsoft.com/downloads/details.aspx?familyid=5A58B56F-60B6-4412-95B9-54D056D6F9F4&displaylang=en#filelist"
      Abort "Please restart setup after installing the required version of Windows Installer"
      
      GiveUpNowmsi45:
      Abort "Please install Windows Installer version 4.5 or higher before running setup again."
  ${EndIf}

  Call isNet40Installed
  Pop $R0
  ${If} $R0 != 'Yes'
      MessageBox MB_YESNO|MB_ICONEXCLAMATION "This program requires the .NET Framework 4.  Do you wish to download the required framework now?" IDYES OpenBrowser4 IDNO GiveUpNow4
      
      OpenBrowser4:
      ${OpenURL} "http://www.microsoft.com/downloads/details.aspx?FamilyID=9cfb2d51-5ff4-4491-b0e5-b386f32c0992&displaylang=en"
      Abort "Please restart setup after installing the .NET Framework 4."
      
      GiveUpNow4:
      Abort "Please install the .NET Framework 4 before running setup again."
  ${EndIf}

  Call CheckIsAdminUser
FunctionEnd

Section -Main SEC0000
        SetOutPath $INSTDIR
        StrCmp $Bitness 32 sqlncli32 sqlncli64
        
        sqlncli32:
        MessageBox MB_OK "This is the installer for the 64-bit edition of SQL Server Express.  Please use the 32-bit SQL Server Express Installer."
        Abort "Please use the 32-bit SQL Server Express Installer"
        goto sqlnclidone
        
        sqlncli64:
        SetDetailsPrint both
        DetailPrint "Installing Microsoft SQL Server Express 64-bit edition..."
        
        DetailPrint "Extracting SQL Server Express Installation Files..."
        SetDetailsPrint textonly
        File /r "${SQLServerExpress_SOURCE}\2008R2x64"
        SetDetailsPrint both
        
        DetailPrint "Installing SQL Server Express.  This may take several minutes..."
        nsExec::Exec '"$INSTDIR\2008R2x64\Setup.exe" /configurationfile="$INSTDIR\2008R2x64\EncounterPRO-OS-SQLConfiguration.ini"'

        DetailPrint "Deleting SQL Server Express Installation Files..."
        !insertmacro RemoveFilesAndSubDirs "$INSTDIR"
        goto sqlnclidone
        
        sqlnclidone:

SectionEnd

Section '-Post' SecPost
SectionEnd

Function .onInit
  Call PreInstall
FunctionEnd

