CREATE PROCEDURE jmj_copy_encounter (
	@ps_from_cpr_id varchar(12),
	@pl_from_encounter_id int,
	@ps_to_cpr_id varchar(12) )

AS

DECLARE @ll_new_encounter_id int

INSERT INTO p_Patient_Encounter (
	[cpr_id] ,
	[encounter_type] ,
	[encounter_status] ,
	[encounter_date] ,
	[encounter_description] ,
	[patient_workplan_id] ,
	[indirect_flag] ,
	[patient_class] ,
	[patient_location] ,
	[next_patient_location] ,
	[admission_type] ,
	[attending_doctor] ,
	[referring_doctor] ,
	[supervising_doctor] ,
	[ambulatory_status] ,
	[vip_indicator] ,
	[charge_price_ind] ,
	[courtesy_code] ,
	[discharge_disp] ,
	[discharge_date] ,
	[admit_reason] ,
	[attachment_id] ,
	[new_flag] ,
	[billing_note] ,
	[encounter_billing_id] ,
	[billing_posted] ,
	[bill_flag] ,
	[billing_hold_flag] ,
	[office_id] ,
	[end_date] ,
	[stone_flag] ,
	[created] ,
	[created_by] ,
	[appointment_time] ,
	[est_appointment_length] ,
	[workers_comp_flag] ,
	[coding_component_id] ,
	[billing_calc_date] ,
	[id] ,
	[default_grant] )
SELECT @ps_to_cpr_id ,
	[encounter_type] ,
	[encounter_status] ,
	[encounter_date] ,
	[encounter_description] ,
	[patient_workplan_id] ,
	[indirect_flag] ,
	[patient_class] ,
	[patient_location] ,
	[next_patient_location] ,
	[admission_type] ,
	[attending_doctor] ,
	[referring_doctor] ,
	[supervising_doctor] ,
	[ambulatory_status] ,
	[vip_indicator] ,
	[charge_price_ind] ,
	[courtesy_code] ,
	[discharge_disp] ,
	[discharge_date] ,
	[admit_reason] ,
	[attachment_id] ,
	[new_flag] ,
	[billing_note] ,
	[encounter_billing_id] ,
	[billing_posted] ,
	[bill_flag] ,
	[billing_hold_flag] ,
	[office_id] ,
	[end_date] ,
	[stone_flag] ,
	[created] ,
	[created_by] ,
	[appointment_time] ,
	[est_appointment_length] ,
	[workers_comp_flag] ,
	[coding_component_id] ,
	[billing_calc_date] ,
	[id] ,
	[default_grant]
FROM p_Patient_Encounter
WHERE cpr_id = @ps_from_cpr_id
AND encounter_id = @pl_from_encounter_id	

SET @ll_new_encounter_id = SCOPE_IDENTITY()

RETURN @ll_new_encounter_id

