CREATE PROCEDURE sp_active_services_35 (
	@ps_in_office_flag char(1) = 'Y' )
AS

SELECT patient_workplan_id,   
	patient_workplan_item_id,   
	cpr_id,   
	encounter_id,   
	ordered_service,   
	followup_workplan_id,   
	description,   
	ordered_by,   
	ordered_for,   
	priority,   
	dispatch_date,   
	owned_by,   
	begin_date,   
	status,
	room_id,
	escalation_date,
	expiration_date,
	DATEDIFF(minute, dispatch_date, getdate()) as minutes,
	user_id,
	computer_id,
	patient_location,
	office_id,
	observation_id,
	result_sequence,
	result,
	result_date_time,
	location,
	location_description,
	result_value,
	result_unit,
	result_amount_flag,
	print_result_flag,
	print_result_separator,
	abnormal_flag,
	abnormal_nature,
	severity,
	unit_preference,
	display_mask,
	in_office_flag
FROM o_Active_Services
WHERE in_office_flag LIKE @ps_in_office_flag

