#!/bin/bash
# Download PDF from Uganda website 
# https://www.nda.or.ug/drug-register-downloads/
# e.g.
# https://www.nda.or.ug/wp-content/uploads/2022/04/NATIONAL-DRUG-REGISTER-OF-UGANDA-HUMAN-MEDICINES-APRIL-2022.pdf
# https://www.adobe.com/acrobat/online/pdf-to-excel.html to convert to Excel

# Open in OpenOffice Calc
#	1. Replace all , with ! (save)
#	2. Replace all " with @ (save)
#	3. Replace all reg expression \n with space (save)
#	3. Eliminate top title row if there is one (top row should be column headings)
# S/N	NDA REGISTRATION NUMBER	LICENSE HOLDER	LOCAL TECHNICAL REPRESENTATIVE	NAME OF DRUG	GENERIC NAME OF DRUG	STRENGTH OF DRUG	MANUFACTURER	COUNTRY OF MANUFACTURE	DOSAGE FORM	PACK SIZE	REG DATE
#	4. Save as Uganda.csv

# cd /mnt/c/EncounterPro/RXNORM

# ./process-uganda.sh Uganda.csv
# (see bottom of this file for next steps)

# Remove embedded newlines and quotes, 
# replace usage of + instead of /
# awk -f remove-embedded-newlines.awk $1 no longer necessary with \n replacement above
cat $1 | \
sed 's/\([A-Z0-9]\)+\([A-Z0-9]\)/\1 \/ \2/g' | \
sed 's/ +\([A-Z0-9]\)/ \/ \1/g' | \
sed 's/\([A-Z0-9]\)+ /\1 \/ /g' | \
sed 's/ AND / \/ /g' | \
sed 's/ + / \/ /g' | \
sed 's/ \/ \/ / \/ /g' > nl.csv

# Handle extraneous commas and duplications within generic drug name column
cat nl.csv | \
sed 's/ANHYDROUS GLUCOSE \/ SODIUM CHLORIDE \/ TRISODI *UM CITRATE \/ POTASSIU *M CHLORIDE\/ZINC! ANHYDROUS GLUCOSE \/ SODIUM CHLORIDE \/ TRISODI *UM CITRATE \/ POTASSIU *M CHLORIDE\/ZINC! ANHYDROUS GLUCOSE \/ SODIUM CHLORIDE \/ TRISODI *UMCITRATE \/ POTASSIU/GLUCOSE \/ SODIUM CHLORIDE \/ TRISODIUM CITRATE \/ POTASSIUM CHLORIDE \/ ZINC/' | \
sed 's/ANHYDROUS GLUCOSE \/ SODIUM CHLORIDE \/ TRISODI *UM CITRATE \/ POTASSIU *M CHLORIDE! ANHYDROUS GLUCOSE \/ SODIUM CHLORIDE \/ TRISODI *UM CITRATE \/ POTASSIU *M CHLORIDE! ANHYDROUS GLUCOSE \/ SODIUM CHLORIDE \/ TRISODI *UMCITRATE \/ POTASSIU/GLUCOSE \/ SODIUM CHLORIDE \/ TRISODIUM CITRATE \/ POTASSIUM CHLORIDE/' | \
sed 's/ANHYDROUS GLUCOSE \/ SODIUM CHLORIDE \/ TRISODIUM CITRATE \/ POTASSIUM CHLORIDE\/ZINC!ANHYDR OUS GLUCOSE \/ SODIUM CHLORIDE \/ TRISODIUM CITRATE \/ POTASSIUM CHLORIDE\/ZINC!ANHYDR OUS GLUCOSE \/ SODIUM CHLORIDE \/ TRISODIUM/GLUCOSE \/ SODIUM CHLORIDE \/ TRISODIUM CITRATE \/ POTASSIUM CHLORIDE \/ ZINC/' | \
sed 's/ANHYDROUS GLUCOSE \/ SODIUM CHLORIDE \/ TRISODIUM CITRATE \/ POTASSIUM CHLORIDE\!ANHYDROUS GLUCOSE \/ SODIUM CHLORIDE \/ TRISODIUM CITRATE \/ POTASSIUM CHLORIDE\!ANHYDROUS GLUCOSE \/ SODIUM CHLORIDE \/ TRISODIUM/GLUCOSE \/ SODIUM CHLORIDE \/ TRISODIUM CITRATE \/ POTASSIUM CHLORIDE/' | \
sed 's/TABLET-ZINC\! SACHET- *NACL \/ KCL \/ TRISODIUM CITRATE \/ ANHYDROUS GLUCOSE/ZINC \/ SODIUM CHLORIDE \/ POTASSIUM CHLORIDE \/ TRISODIUM CITRATE \/ ANHYDROUS GLUCOSE/' | \
sed 's/\[GLUCOSE ANHYDROUS \/ SODIUM CHLORIDE \/ TRISODIUM CITRATE DIHYDRATE \/ POTASSIUM CHLORIDE \]+ \[ZINC SULPHATE MONOHYDRATE\] */GLUCOSE \/ SODIUM CHLORIDE \/ TRISODIUM CITRATE \/ POTASSIUM CHLORIDE \/ ZINC/g' | \
sed 's/\[GLUCOSE \/ SODIUM CHLORIDE \/ TRISODIUM CITRATE \/ POTASSIUM CHLORIDE \]+ \[ZINC\]/GLUCOSE \/ SODIUM CHLORIDE \/ TRISODIUM CITRATE \/ POTASSIUM CHLORIDE \/ ZINC/g' | \
sed 's/\[GLUCOSE \/ SODIUM CHLORIDE \/ TRISODIUM CITRATE \/ POTASSIUM CHLORIDE \] \/ \[ZINC SULFATE MONOHYDRATE\]/GLUCOSE \/ SODIUM CHLORIDE \/ TRISODIUM CITRATE \/ POTASSIUM CHLORIDE \/ ZINC SULFATE/g' | \
sed 's/CLOTRIMAZOLE USP\! BECLOMETASONE DIPROPIONATE BP\! GENTAMICIN SULPHATE BP/CLOTRIMAZOLE \/ BECLOMETHASONE \/ GENTAMICIN SULFATE/g' | \
sed 's/PARACETAMOL \/ CAFFEIN E\! PHENYLEPHRINE \/ CHLORPHENAMINE MALEATE/PARACETAMOL \/ CAFFEINE \/ PHENYLEPHRINE \/ CHLORPHENIRAMINE MALEATE/g' | \
sed 's/ *LINEZOLID\!CHLORHEXIDINE */LINEZOLID \/ CHLORHEXIDINE/g' | \
sed 's/LORATIDINE\!LORATIDINE/LORATIDINE/g' | \
sed 's/FOLIC ACID\!/FOLIC ACID/g' | \
sed 's/ABACAVIR\! DOLUTEGRAVIR \/ LAMIVUDINE/ABACAVIR \/ DOLUTEGRAVIR \/ LAMIVUDINE/g' | \
sed 's/DOLUTEGRAVIR SODIUM\! LAMIVUDINE \/ TENOFOVIR DISOPROXIL FUMARATE/DOLUTEGRAVIR SODIUM \/ LAMIVUDINE \/ TENOFOVIR DISOPROXIL FUMARATE/g' | \
sed 's/DOLUTEGRAVIR\! LAMIVUDINE \/ TENOFOVIR DISOPROXIL FUMARATE/DOLUTEGRAVIR \/ LAMIVUDINE \/ TENOFOVIR DISOPROXIL FUMARATE/g' | \
sed 's/DOXYLAMINE SUCCINATE & PYRIDOXINE/DOXYLAMINE \/ PYRIDOXINE/g' | \
sed 's/ATRIPLA,EFAVIRENZ *\/ *EMTRICITABI NE *\/ *TENOFOVIR/ATRIPLA,EFAVIRENZ \/ EMTRICITABINE \/ TENOFOVIR DISOPROXIL FUMARATE/g' | \
sed 's/EFAVIRENZ *\/ *EMTRICITABI *NE *\/ *TENO *FO *VIR DISOPROXIL/EFAVIRENZ \/ EMTRICITABINE \/ TENOFOVIR DISOPROXIL FUMARATE/g' | \
sed 's/EFAVIRENZ\! LAMIVUDINE \/ TENOFOVIR DISOPROXIL FUMARATE/EFAVIRENZ \/ LAMIVUDINE \/ TENOFOVIR DISOPROXIL FUMARATE/g' | \
sed 's/GLUTODINE (CYPROHEPTADINE ALPHA- *KETOGLUTARATE) *\/ *ARGININE ASPARTATE/CYPROHEPTADINE \/ ARGININE/g' | \
sed 's/GLYBURIDE (GLIBENCLAMIDE) *\/ *METFORMIN/GLYBURIDE \/ METFORMIN/g' | \
sed 's/HIGHLY PURIFIED MENOTROPHIN \[ CORRESPONDING TO FOLLICLE STIMULATING HORMONE ACTIVITY (FSH) 75 IU \/ LUTEINISING HORMONE ACTIVITY (LH) 75 IU\]/FOLLICLE STIMULATING HORMONE \/ LUTEINIZING HORMONE/g' | \
sed 's/IBUPROFEN+\. *PARACETAMOL/IBUPROFEN \/ PARACETAMOL/g' | \
sed 's/IPRATROPIUM BROMIDE & SALBUTAMOL/IPRATROPIUM BROMIDE \/ SALBUTAMOL/g' | \
sed 's/LIGHT KAOLIN *\/ *PECTIN (CITRUS)/KAOLIN \/ PECTIN/g' | \
sed 's/MACROGOL 3350 (POLYETHYLENE GLYCOL)+SODIUM CHLORIDE *\/ *SODIUM BICARBONATE *\/ *POTASSIUM CHLORIDE/POLYETHYLENE GLYCOL \/ POTASSIUM CHLORIDE \/ SODIUM BICARBONATE \/ SODIUM CHLORIDE/g' | \
sed 's/PARACETAMOL *\/ *CAFFEIN *E CITRATE *\/ *CHLORPHENIR *AMINE MALEATE *\/ *PSEUDOEPHE *DRINE HYDROCHLORIDE/PARACETAMOL \/ CAFFEINE \/ CHLORPHENIRAMINE MALEATE \/ PSEUDOEPHEDRINE HYDROCHLORIDE/g' | \
sed 's/TENOFOVIR *\/ *EMTRICITABINE *\/ *EFAVIRENZ/TENOFOVIR DISOPROXIL \/ EMTRICITABINE \/ EFAVIRENZ/g' | \
sed 's/ZINC SULPHATE MONOHYDRATE *\/ *(SODIUM CHLORIDE *\/ *POTASSIUM CHLORIDE *\/ *SODIUM CITRATE *\/ *ANHYDROUS GLUCOSE)/ SULFATE MONOHYDRATE \/ SODIUM CHLORIDE \/ POTASSIUM CHLORIDE \/ SODIUM CITRATE \/ GLUCOSE/g' \
> nl2.csv

# Next try to fix induced spaces from line breaks in the original, and misspellings
cat nl2.csv | \
sed 's/EYLEA,,,/EYLEA,AFLIBERCEPT,2 MG,/' | \
sed 's/SULPHATE/SULFATE/g' | \
sed 's/ (AS HYDROCHLORIDE)/ HYDROCHLORIDE/g' | \
sed 's/ (ANHYDROUS)/ ANHYDROUS/g' | \
sed 's/ BP//g' | \
sed 's/ USP//g' | \
sed 's/ AN *HYDROUS/ ANHYDROUS/g' | \
sed 's/ CRYSTALS//g' | \
sed 's/Z *O *LE/ZOLE/g' | \
sed 's/AM *I *N/AMIN/g' | \
sed 's/A MM/AMM/g' | \
sed 's/AMO DIA/AMODIA/g' | \
sed 's/ANTI- D/ANTI-D/g' | \
sed 's/ AZIDE/AZIDE/g' | \
sed 's/BENZ /BENZ/g' | \
sed 's/BIN ANT/BINANT/g' | \
sed 's/B *RO *M/BROM/g' | \
sed 's/CHL /CHL/g' | \
sed 's/C *H *L *O *R *A */CHLORA/g' | \
sed 's/CHOLR/CHLOR/g' | \
sed 's/CO *N *E/CONE/g' | \
sed 's/DAS E/DASE/g' | \
sed 's/DE XT/DEXT/g' | \
sed 's/D EXTRO/DEXTRO/g' | \
sed 's/DEXT *RO *M/DEXTROM/g' | \
sed 's/DON A/DONA/g' | \
sed 's/ EDRINE/EDRINE/g' | \
sed 's/EP HED/EPHED/g' | \
sed 's/ESI NIN/ESININ/g' | \
sed 's/ETH IC/ETHIC/g' | \
sed 's/EUTICA L/EUTICAL/g' | \
sed 's/FRE EZE/FREEZE/g' | \
sed 's/FUMERATE/FUMARATE/g' | \
sed 's/HYD *R *O/HYDRO/g' | \
sed 's/I M AMP/IM AMP/g' | \
sed 's/I M VIAL/IM VIAL/g' | \
sed 's/ INE/INE/g' | \
sed 's/ISI NIN/ISININ/g' | \
sed 's/IT HR/ITHR/g' | \
sed 's/I *U *M/IUM/g' | \
sed 's/LIN E/LINE/g' | \
sed 's/MAGN *ES/MAGNES/g' | \
sed 's/MAGNESS/MAGNES/g' | \
sed 's/MET HIC/METHIC/g' | \
sed 's/ME TH/METH/g' | \
sed 's/MH EX/MHEX/g' | \
sed 's/MI *D *E/MIDE/g' | \
sed 's/MI NERA/MINERA/g' | \
sed 's/NEV IRA/NEVIRA/g' | \
sed 's/NICO L/NICOL/g' | \
sed 's/NIU M/NIUM/g' | \
sed 's/ON IDA/ONIDA/g' | \
sed 's/PE NT/PENT/g' | \
sed 's/PH *A *N/PHAN/g' | \
sed 's/P *H *E *N/PHEN/g' | \
sed 's/PIOG LIT/PIOGLIT/g' | \
sed 's/POTA SS/POTASS/g' | \
sed 's/RO NE/RONE/g' | \
sed 's/R PHAN/RPHAN/g' | \
sed 's/Q UINE/QUINE/g' | \
sed 's/RI NE/RINE/g' | \
sed 's/RIN E/RINE/g' | \
sed 's/RAMIN E/RAMINE/g' | \
sed 's/RIMIN E/RIMINE/g' | \
sed 's/S ODIUM/SODIUM/g' | \
sed 's/S OLE/SOLE/g' | \
sed 's/SON E/SONE/g' | \
sed 's/SO PRA/SOPRA/g' | \
sed 's/TATI N/TATIN/g' | \
sed 's/THA NE/THANE/g' | \
sed 's/TI *N *E/TINE/g' | \
sed 's/TRIC IT/TRICIT/g' | \
sed 's/TR OPIN/TROPIN/g' | \
sed 's/ VUDINE/VUDINE/g' | \
sed 's/XID E/XIDE/g' | \
sed 's/YT ES/YTES/g' | \
sed 's/ZID E/ZIDE/g' | \
sed 's/Z INC/ZINC/g' | \
sed 's/ZIN C/ZINC/g' | \
sed 's/ZI NC/ZINC/g' | \
sed 's/ZIN E/ZINE/g' | \
sed 's/\! PHENYLEPHRINE/ \/ PHENYLEPHRINE/g' | \
sed 's/A *C *ETA *MINOPHEN/ACETAMINOPHEN/g' | \
sed 's/A CILLIN/ACILLIN/g' | \
sed 's/ACETYL *SALICYLIC ACID/ASPIRIN/g' | \
sed 's/ACETYL SALICYLATE/ASPIRIN/g' | \
sed 's/ADALIMUMAB (R-DNA ORIGIN)/ADALIMUMAB/g' | \
sed 's/AGINATE/ALGINATE/g' | \
sed 's/ADAPLENE/ADAPALENE/g' | \
sed 's/ALCOHOL 95%/ALCOHOL/g' | \
sed 's/ALGNIC ACID/ALGINIC ACID/g' | \
sed 's/ALLANTOI N/ALLANTOIN/g' | \
sed 's/ALPHA -BETA/ALPHA-BETA/g' | \
sed 's/DRIED ALUMINIUM HYDROXIDE/ALUMINUM HYDROXIDE/g' | \
sed 's/ALUMINIUM HYDROXIDEL/ALUMINUM HYDROXIDE/g' | \
sed 's/ALUMINIUM/ALUMINUM/g' | \
sed 's/AMBRO *X *OL/AMBROXOL/g' | \
sed 's/AMM *ONIUM/AMMONIUM/g' | \
sed 's/AMOXYCILLIN/AMOXICILLIN/g' | \
sed 's/AMOXILLICIN/AMOXICILLIN/g' | \
sed 's/AMOXICLLIN/AMOXICILLIN/g' | \
sed 's/AMOXICILLINTRIHY *DRAT *E/AMOXICILLIN TRIHYDRATE/g' | \
sed 's/AMPI *CILLI *N/AMPICILLIN/g' | \
sed 's/ARTHEMETHER/ARTEMETHER/g' | \
sed 's/AS *P *IRIN/ASPIRIN/g' | \
sed 's/ATORVASTATIN CALCIUM (TRIHYDRATE)/ATORVASTATIN CALCIUM/g' | \
sed 's/AZITHROMYCIN (AS)/AZITHROMYCIN/g' | \
sed 's/BCG VACCINE *(FREEZE DRIED)/BCG VACCINE/g' | \
sed 's/BECLOMETASONE/BECLOMETHASONE/g' | \
sed 's/BELLADONA DRY EXTRACT/BELLADONNA/g' | \
sed 's/BENDROFLUMETHIA ZIDE/BENDROFLUMETHIAZIDE/g' | \
sed 's/BENZYDA MINE/BENZYDAMINE/g' | \
sed 's/BENZYLPENICILLI N/BENZYLPENICILLIN/g' | \
sed 's/BENZOIC ACID/BENZOATE/g' | \
sed 's/BETA ARTEMETHER/ARTEMETHER/g' | \
sed 's/BETAMETHAS *ONE 17/BETAMETHASONE/g' | \
sed 's/ *BISOPROLOL/BISOPROLOL/g' | \
sed 's/BROMHE *XIN *E/BROMHEXINE/g' | \
sed 's/BROMHE *XIN *E/BROMHEXINE/g' | \
sed 's/C *A *F *FEI *N *E/CAFFEINE/g' | \
sed 's/CALCIPOTRIOL/CALCIPOTRIENE/g' | \
sed 's/CA MPHOR/CAMPHOR/g' | \
sed 's/C *AP *SICUM/CAPSICUM/g' | \
sed 's/CAPSICUM OLEORESIN/CAPSICUM EXTRACT/g' | \
sed 's/CARBOCYSTEINE/CARBOCISTEINE/g' | \
sed 's/CARBONYL IRON/IRON CARBONYL/g' | \
sed 's/CARBOXYMETHYLCE *LLUL *OSE/CARBOXYMETHYLCELLULOSE/g' | \
sed 's/CATALKO *NIUM/CATALKONIUM/g' > chems0.csv


cat chems0.csv | \
sed 's/CEFALEXIN MONOHYRATE/CEFALEXIN MONOHYDRATE/g' | \
sed 's/CETYL *PYRI *DINIUM/CETYLPYRIDINIUM/g' | \
sed 's/CETYL *PYRI *DINUM/CETYLPYRIDINIUM/g' | \
sed 's/CHLORAMPHENICOL SODIUM SUCCINNATE B.P/CHLORAMPHENICOL SODIUM SUCCINATE/g' | \
sed 's/CHLORPHENARI *MIN *E/CHLORPHENIRAMINE/g' | \
sed 's/C *HLO *R *O* *P *HENI *R *AMIN *E*/CHLORPHENIRAMINE/g' | \
sed 's/C *HLOR *PHENAMIN *E/CHLORPHENIRAMINE/g' | \
sed 's/C *HLO *RPHRENIRAMINE/CHLORPHENIRAMINE/g' | \
sed 's/CH *LOR *Z *O *X *AZONE/CHLORZOXAZONE/g' | \
sed 's/CHON *DROITIN SULFATE */CHONDROITIN SULFATES/g' | \
sed 's/CHORIONIC GONADOTROPIN ALFA/CHORIONIC GONADOTROPIN/g' | \
sed 's/CHORIOGONADOTR *OPIN ALFA/CHORIONIC GONADOTROPIN/g' | \
sed 's/CINC *HOCAINE/CINCHOCAINE/g' | \
sed 's/CLARITHROMYCIN *(EXTE *NTED RELEASE)/CLARITHROMYCIN/g' | \
sed 's/CLARITHR *O *MYCIN/CLARITHROMYCIN/g' | \
sed 's/DILUTED CLAVULANATE/CLAVULANATE/g' | \
sed 's/CLAV *U *LAN *ATE/CLAVULANATE/g' | \
sed 's/CLAVUNATE/CLAVULANATE/g' | \
sed 's/CLAV *ULA *N *IC ACID/CLAVULANATE/g' | \
sed 's/CLAVULIN *IC ACID/CLAVULANATE/g' | \
sed 's/CLAVULANIC/CLAVULANATE/g' | \
sed 's/CLINDAMYCIN PHOSPHATE EQUIVALENT TO CLINDAMYCIN/CLINDAMYCIN/g' | \
sed 's/CLOBETASOL-17- BUTYRATE/CLOBETASOL 17-BUTYRATE/g' | \
sed 's/CLOBETASOLE/CLOBETASOL/g' > chems1.csv

cat chems1.csv | \
sed 's/CLOMIPHENE/CLOMIFENE/g' | \
sed 's/CLOPIDOGREL BISULPHATE/CLOPIDOGREL BISULFATE/g' | \
sed 's/CLOTRIMOXAZOLE/CLOTRIMAZOLE/g' | \
sed 's/C *LOT *RIMAZOLE/CLOTRIMAZOLE/g' | \
sed 's/CLOX *A *C *ILLI *N/CLOXACILLIN/g' | \
sed 's/CO-AMOXICLAV (AMOXICILLIN *\/ *POTAS *SIUM CLAVUNATE)/AMOXICILLIN \/ CLAVUNATE/g' | \
sed 's/COB *I *CIST *AT/COBICISTAT/g' | \
sed 's/CO *DEI *N *E/CODEINE/g' | \
sed 's/C *ODEINE PHOSPATE/CODEINE PHOSPHATE/g' | \
sed 's/CODEINE PHOSPH*ATE/CODEINE PHOSPHATE/g' | \
sed 's/COLECALCIFEROL/CHOLECALCIFEROL/g' | \
sed 's/DENATURED ALCOHOL MENTHOL/ALCOHOL \/ MENTHOL/g' | \
sed 's/DESLORATIDINE/DESLORATADINE/g' | \
sed 's/DEXA *ME *T *HAS *ON *E/DEXAMETHASONE/g' | \
sed 's/DEX *TR *O *METH* *O *RP *HAN/DEXTROMETHORPHAN/g' | \
sed 's/DIC *LOFE *NAC/DICLOFENAC/g' | \
sed 's/DICLOFENAC\./DICLOFENAC/g' | \
sed 's/DICLOFENAC GASTRO-* *RESISTANT/DICLOFENAC/g' | \
sed 's/DICLOFENAC SALT/DICLOFENAC/g' | \
sed 's/DIHYDROARTEMISIN *IN/DIHYDROARTEMISININ/g' | \
sed 's/DIHYDROARTEMESI *NINE*/DIHYDROARTEMISININ/g' | \
sed 's/D *ILOX *ANIDE/DILOXANIDE/g' | \
sed 's/CONTROLLED RELEASE TABLETS OF DILTIAZEM/DILTIAZEM/g' | \
sed 's/DIMET *HICONE/DIMETHICONE/g' | \
sed 's/D *IPHE *NHYD *RAMINE/DIPHENHYDRAMINE/g' | \
sed 's/DOMPERIDONE SR/DOMPERIDONE/g' | \
sed 's/DOROZOLAMIDE/DORZOLAMIDE/g' | \
sed 's/DOXYL *AMINE/DOXYLAMINE/g' | \
sed 's/DRIED ALUMINUM HYDROXIDE/ALUMINUM HYDROXIDE/g' | \
sed 's/ELECTROLYTE *S/ELECTROLYTES/g' | \
sed 's/EMTRICIST *ABINE/EMTRICITABINE/g' | \
sed 's/EMTRICITA *BINE/EMTRICITABINE/g' | \
sed 's/ERYTHROMYCIN STEARATE TABLETS/ERYTHROMYCIN STEARATE/g' | \
sed 's/ESOMEPRAZOLE (AS MAGNESIUM)/ESOMEPRAZOLE/g' | \
sed 's/ESOMEPRAZOLE AS MAGNESIUM TRIHYDRATE PELLETS/ESOMEPRAZOLE/g' | \
sed 's/ESOMEPRAZOLE MAGNESIUM TRIHYDRATE/ESOMEPRAZOLE/g' | \
sed 's/ETHI *NYL *ESTRADIOL\.*/ETHINYL ESTRADIOL/g' | \
sed 's/EZETIMIDE/EZETIMIBE/g' | \
sed 's/FAN TRI/FANTRI/g' | \
sed 's/FERR *OUS/FERROUS/g' | \
sed 's/FERROUS FUMERATE/FERROUS FUMARATE/g' | \
sed 's/FINOFIBRATE/FENOFIBRATE/g' | \
sed 's/FOR *M[EO]TEROL/FORMOTEROL/g' | \
sed 's/FORTIFIED PROCAINE PENICILLIN SODIUM/PROCAINE PENICILLIN SODIUM/g' | \
sed 's/FORTIFIED PROCAINE PENICILLIN/PROCAINE PENICILLIN/g' | \
sed 's/FOSFOMYCIN *TROM *ETA *MOL/FOSFOMYCIN/g' | \
sed 's/FRUSEMIDE/FUROSEMIDE/g' | \
sed 's/GEN *T *AMI *C *I*N/GENTAMICIN/g' | \
sed 's/GEN *TAMYCIN/GENTAMICIN/g' | \
sed 's/GLYCOPY *RRO *NIUM/GLYCOPYRRONIUM/g' | \
sed 's/GRAMICID *IN/GRAMICIDIN/g' | \
sed 's/G *UAIF *ENESIN/GUAIFENESIN/g' | \
sed 's/G *UAIPHEN[EI]SI *N/GUAIFENESIN/g' | \
sed 's/GUAI*FEN *ESIN/GUAIFENESIN/g' | \
sed 's/GONADOTROPHIN/GONADOTROPIN/g' | \
sed 's/HEPATITIS B SURFACE ANTIGEN VACCINE (HBSAG)/HEPATITIS B SURFACE ANTIGEN VACCINE/g' | \
sed 's/HYD *RO *CH *LOROT *HI *AZID *E/HYDROCHLOROTHIAZIDE/g' | \
sed 's/HYDROCORTISONE 17- *BUTYRATE/HYDROCORTISONE 17-BUTYRATE/g' | \
sed 's/HYDROCO *RTISONE/HYDROCORTISONE/g' | \
sed 's/HYDROXYPROGESTE *RON *E/HYDROXYPROGESTERONE/g' | \
sed 's/HYDRO *CH *LOROTHIA *ZIDE/HYDROCHLOROTHIAZIDE/g' | \
sed 's/HYOSCINE-N- BUTYLBROMIDE/HYOSCINE-N-BUTYLBROMIDE/g' | \
sed 's/HYOSCINE BUTYL BROMIDE/HYOSCINE BUTYLBROMIDE/g' | \
sed 's/IBU *PRO *F *EN/IBUPROFEN/g' | \
sed 's/IBUPROFEN LYSINE/IBUPROFEN \/ LYSINE/g' | \
sed 's/IODOCHLORHYDRO *XYQUINOLINE/IODOCHLORHYDROXYQUINOLINE/g' | \
sed 's/ISONIAZID 100 MG/ISONIAZID/g' | \
sed 's/ISOSORBIDE *-5-NITRATE/ISOSORBIDE 5-NITRATE/g' | \
sed 's/LANSOP *RAZOLE/LANSOPRAZOLE/g' | \
sed 's/LANSOPRAZOLE DELAYED RELEASE/LANSOPRAZOLE/g' | \
sed 's/LA *MIV *U *DIN *E/LAMIVUDINE/g' | \
sed 's/LEDIP *ASVI *R/LEDIPASVIR/g' | \
sed 's/LEVOCETI *RIZINE/LEVOCETIRIZINE/g' | \
sed 's/LEVOFLOXACIN HEMIHYDRATES/LEVOFLOXACIN HEMIHYDRATE/g' | \
sed 's/LI *DOCAI *NE/LIDOCAINE/g' | \
sed 's/LINEZOLIDGLUCONATE/LINEZOLID GLUCONATE/g' | \
sed 's/L-ORNITHINE- *L- *ASPARTATE/L-ORNITHINE-L-ASPARTATE/g' | \
sed 's/LUM *EFANTRINE/LUMEFANTRINE/g' | \
sed 's/LUMEFANTRINE1/LUMEFANTRINE 1/g' | \
sed 's/MAGNESIUM TRISILCATE/MAGNESIUM TRISILICATE/g' | \
sed 's/MAGNESIUM TRISLICATE/MAGNESIUM TRISILICATE/g' | \
sed 's/MEDROXYPROGESTERO *NE ACETATE/MEDROXYPROGESTERONE/g' | \
sed 's/MEFENAMIC ACID/MEFENAMATE/g' > chems2.csv

cat chems2.csv | \
sed 's/M *E *N *T *H *O *L/MENTHOL/g' | \
sed 's/MENTHOL 95%/MENTHOL/g' | \
sed 's/MESALAMINE DELAYED RELEASE/MESALAMINE/g' | \
sed 's/M *ETF *O *R *M *IN/METFORMIN/g' | \
sed 's/METHO *CAR *BAMOL/METHOCARBAMOL/g' | \
sed 's/METH YL/METHYL/g' | \
sed 's/METHYL *NICOTINATE/METHYLNICOTINATE/g' | \
sed 's/METHYLPREDNISOL *ONE/METHYLPREDNISOLONE/g' | \
sed 's/METHYLSALICYLATE/METHYL SALICYLATE/g' | \
sed 's/METHYL SALICYLATE *CRYSTALS/METHYL SALICYLATE/g' | \
sed 's/METHYL SALICYLATE MENTHOL/METHYL SALICYLATE \/ MENTHOL/g' | \
sed 's/METHYL SULPHONYL METHANE SULFATE/METHYLSULFONYLMETHANE SULFATE/g' | \
sed 's/METHYL *SULP *HONYL *METHANE/METHYLSULFONYLMETHANE/g' | \
sed 's/METRON *I *DAZOLE BENZOATE/METRONIDAZOLE/g' | \
sed 's/MIC ONAZOLE/MICONAZOLE/g' | \
sed 's/MINERA *LS/MINERALS/g' | \
sed 's/N *APH *AZOLINE/NAPHAZOLINE/g' | \
sed 's/NATURAL VITAMIN E/VITAMIN E/g' | \
sed 's/N *E *O *M *YC *IN/NEOMYCIN/g' | \
sed 's/NIFEDIPINE(SR)/NIFEDIPINE/g' | \
sed 's/NILOTONIB/NILOTINIB/g' | \
sed 's/OLANZAPINE ORODISPERSIBLE/OLANZAPINE/g' | \
sed 's/GASTRO-RESISTANT OMEPRAZOLE CAPSULES 20/OMEPRAZOLE/g' | \
sed 's/ONDANSENTRON/ONDANSETRON/g' | \
sed 's/ORNID *AZOL *E/ORNIDAZOLE/g' | \
sed 's/PA *NTOT *HENOL/PANTOTHENOL/g' | \
sed 's/PA *R *AC *ET *A *MO *L/PARACETAMOL/g' | \
sed 's/PARACETAMOL(IMMEDIATE RELEASE)+ PARACETAMOL(EXTENDED RELEASE)/PARACETAMOL/g' | \
sed 's/PARACETAMOL EFFERVESCENT/PARACETAMOL/g' | \
sed 's/PARACETAMOL SUSTAINED RELEASE/PARACETAMOL/g' | \
sed 's/PEPPER *MIN *T/PEPPERMINT/g' | \
sed 's/PHENOBARBITON *E TABLETS 30MG/PHENOBARBITONE/g' | \
sed 's/PHENOXYMETHYL *P *E *NICI *LLIN/PHENOXYMETHYL PENICILLIN/g' | \
sed 's/PHENYL *EPH* *RINE/PHENYLEPHRINE/g' | \
sed 's/PHTHALYL SULPHATHIAZOLE/SULPHATHIAZOLE/g' | \
sed 's/PIOG *L *ITAZ *ONE/PIOGLITAZONE/g' | \
sed 's/P *IPERAQUINE/PIPERAQUINE/g' | \
sed 's/POLY (O-2- HYDROXYETHYL) STARCH (HES 130\/0.4)/HYDROXYETHYL STARCH 130-0.4/g' | \
sed 's/POLY *M *YXI *N[- ]B/POLYMYXIN B/g' | \
sed 's/POLYMYXIN B SO4/POLYMYXIN B SULFATE/g' | \
sed 's/PR *OME *T *HA *ZI *NE/PROMETHAZINE/g' | \
sed 's/PROMETHAZINE HCL/PROMETHAZINE/g' | \
sed 's/P *S *E *U *D *O *E *P *H *E *D *RINE/PSEUDOEPHEDRINE/g' | \
sed 's/PYRI *MET *HAMINE/PYRIMETHAMINE/g' | \
sed 's/RIB *OTLAVINE*/RIBOFLAVIN/g' | \
sed 's/RIFAMPICINHYDROCHLORIDE/RIFAMPICIN HYDROCHLORIDE/g' | \
sed 's/RITONAVIR TABLETS 300 MG \/ 100 MG/RITONAVIR/g' | \
sed 's/RITONA VIR/RITONAVIR/g' | \
sed 's/RITUXIMAB AMRING/RITUXIMAB/g' | \
sed 's/SALICYLIC CID/SALICYLIC ACID/g' | \
sed 's/SERRAT *IOPEPTID *ASE/SERRATIOPEPTIDASE/g' | \
sed 's/SILDENAFIL CIT*RATE/SILDENAFIL CITRATE/g' | \
sed 's/SILVER SULPHADIAZINE/SILVER SULFADIAZINE/g' | \
sed 's/SIM *ET *H *I *C *[AO]NE/SIMETHICONE/g' | \
sed 's/SIMETHIC ONE/SIMETHICONE/g' | \
sed 's/SIMETICONE/SIMETHICONE/g' | \
sed 's/SO *DIUM CITRATE/SODIUM CITRATE/g' | \
sed 's/SODIUM LACTATE \/ NACL/SODIUM LACTATE \/ SODIUM CHLORIDE/g' | \
sed 's/SODIUM VALPOATE/SODIUM VALPROATE/g' | \
sed 's/SULB *ACT *A *M/SULBACTAM/g' | \
sed 's/SULBACTUM/SULBACTAM/g' | \
sed 's/SULPHADOXINE/SULFADOXINE/g' | \
sed 's/SULPHAMETHOXAZOLE/SULFAMETHOXAZOLE/g' | \
sed 's/SU *LFA *METHOXAZOL *E/SULFAMETHOXAZOLE/g' > chems3.csv

cat chems3.csv | \
sed 's/TAZOBAC *T *AM/TAZOBACTAM/g' | \
sed 's/TENECTEPLASE (RECOMBINANT TISSUE PLASMINOGEN ACTIVATOR)/TENECTEPLASE/g' | \
sed 's/T *E *NO *FO *VIR/TENOFOVIR/g' | \
sed 's/TENOFOVIR DISOPROXIL ALAFENAMIDE HEMIFUMARATE */TENOFOVIR ALAFENAMIDE HEMIFUMARATE/g' | \
sed 's/TENOFOVIR DISOPROXIL ALAFENAMIDE FUMARATE */TENOFOVIR ALAFENAMIDE FUMARATE/g' | \
sed 's/TENOFOVIR DISOPROXIL ALAFENAMIDE/TENOFOVIR ALAFENAMIDE/g' | \
sed 's/TENO *FOVI *R DISOPROXIL/TENOFOVIR DISOPROXIL/g' | \
sed 's/TERBUTALINE SULFATE/TERBUTALINE/g' | \
sed 's/TERIPARATIDE \[RECOMBINANT HUMAN PARATHYROID HORMONE (1-34)\] INJECTION/TERIPARATIDE/g' | \
sed 's/THYM OL/THYMOL/g' | \
sed 's/TIN *IDAZOLE/TINIDAZOLE/g' | \
sed 's/TORSEMIDE/TORASEMIDE/g' | \
sed 's/TRA *MA *DOL/TRAMADOL/g' | \
sed 's/TRIAMCINOLON *E/TRIAMCINOLONE/g' | \
sed 's/TR *IC *HOLINE/TRICHOLINE/g' | \
sed 's/TR IMETHOPRIM/TRIMETHOPRIM/g' | \
sed 's/TRI *SODIIUM CITT*RATE/TRISODIUM CITRATE/g' | \
sed 's/TRI *SO *DIUM CITRATE/TRISODIUM CITRATE/g' | \
sed 's/TRASFUZUMAB/TRASTUZUMAB/g' | \
sed 's/T *RIAMCINOLONE/TRIAMCINOLONE/g' | \
sed 's/T *RIPR*O *LIDINE/TRIPROLIDINE/g' | \
sed 's/TRIPLORIDINE/TRIPROLIDINE/g' | \
sed 's/URSODEOXYCHOLI *C ACID/URSODEOXYCHOLATE/g' | \
sed 's/VARDENAFIL MONOHYDROCHLO RIDE/VARDENAFIL MONOHYDROCHLORIDE/g' | \
sed 's/VIT B/VITAMIN B/g' | \
sed 's/VITAMINE A/VITAMIN A/g' | \
sed 's/VITAMINE E/VITAMIN E/g' | \
sed 's/VITAMIN E ACETATE/VITAMIN E/g' | \
sed 's/ZIDOV *UDI *NE/ZIDOVUDINE/g' > chems4.csv

# spacing problems around the slash 
cat chems4.csv | \
sed 's/ABACAVIR SULFATE *\/ *LAMIVUDINE/ABACAVIR \/ LAMIVUDINE/g' | \
sed 's/ACECLOFENAC *\/ * PARACETAMOL *\/ * SERRA *TIOPEPTIDASE/ACECLOFENAC \/ PARACETAMOL \/ SERRATIOPEPTIDASE/g' | \
sed 's/ACRIFLAVINE *\/ *THY *MOL/ACRIFLAVINE \/ THYMOL/g' | \
sed 's/ALUMINUM HYDROXIDE *\/ *MAGNESIUM HYDROXIDE *\/ *DIMETHICONE *\/ *LIQUORICE/ALUMINUM HYDROXIDE \/ MAGNESIUM HYDROXIDE \/ DIMETHICONE \/ LIQUORICE/g' | \
sed 's/ALUMINUM HYDROXIDE *\/ *MAGNESIUM HYDROXIDE *\/ *MAGNESIUM ALUMINUM SILICATE *\/ *SIMETHICONE/ALUMINUM HYDROXIDE \/ MAGNESIUM HYDROXIDE \/ MAGNESIUM ALUMINUM SILICATE \/ SIMETHICONE/g' | \
sed 's/ALUMINUM HYDROXIDE *\/ *MAGNESIUM TRISILICATE/ALUMINUM HYDROXIDE \/ MAGNESIUM TRISILICATE/g' | \
sed 's/AMINO ACIDS *\/ *ELECTROLYTES/AMINO ACIDS \/ ELECTROLYTES/g' | \
sed 's/AMINO ACIDS *\/ *SORBITOL/AMINO ACIDS \/ SORBITOL/g' | \
sed 's/AMOXICILLIN SODIUM *\/ *CLAVULANATE POTASSIUM/AMOXICILLIN \/ CLAVULANATE/g' | \
sed 's/AMOXICILLIN.*\/.*CLAVULANATE/AMOXICILLIN \/ CLAVULANATE/g' | \
sed 's/AMPICILLIN *\/ *CLOXACILLIN/AMPICILLIN \/ CLOXACILLIN/g' | \
sed 's/ANDROGRAPHOLID *ES *\/ *TRICHOLINE CITRATE/ANDROGRAPHOLIDES \/ TRICHOLINE CITRATE/g' | \
sed 's/ARTEMETHER *\/ *LUMEFANTRINE/ARTEMETHER \/ LUMEFANTRINE/g' | \
sed 's/ASPIRIN *\/ *PARACETAMOL *\/ *CAFFEINE/ASPIRIN \/ PARACETAMOL \/ CAFFEINE/g' | \
sed 's/ATORVASTATIN *\/ *EZ *ETIMIBE/ATORVASTATIN \/ EZETIMIBE/g' | \
sed 's/ATTAPULGITE *\/ *ALUMINUM HYDROXIDE/ATTAPULGITE \/ ALUMINUM HYDROXIDE/g' | \
sed 's/BACITRACIN ZINC \/ NEOMYCIN/BACITRACIN \/ ZINC \/ NEOMYCIN/g' | \
sed 's/BECLOMETHASONE *\/ *CLOTRIMAZOLE *\/ *GE *NTAMYCIN/BECLOMETHASONE \/ CLOTRIMAZOLE \/ GENTAMYCIN/g' | \
sed 's/BETAMETHASONE *\/ *GENTAMICIN/BETAMETHASONE \/ GENTAMICIN/g' | \
sed 's/CEFTRIAXONE *\/ *SUL *BACTAM/CEFTRIAXONE \/ SULBACTAM/g' | \
sed 's/CHLORHEXIDINE GLUCONATE *\/ *SILVER SULFADIAZINE/CHLORHEXIDINE GLUCONATE \/ SILVER SULFADIAZINE/g' | \
sed 's/CHLORHEXIDINE *\/ *SILVER SULFADIAZINE/CHLORHEXIDINE \/ SILVER SULFADIAZINE/g' | \
sed 's/CHLORHEXIDINE GLUCONATE *\/ *SILVE R SULPHADIAZINE/CHLORHEXIDINE GLUCONATE \/ SILVE R SULPHADIAZINE/g' | \
sed 's/CHLORPHENARIMI *NE MALEATE *\/ *DEXAMETHASONE/CHLORPHENARIMINE MALEATE \/ DEXAMETHASONE/g' | \
sed 's/CHLORPHENIRAMINE MALEATE *\/ *PROMETHAZINE *\/ *DIPHENHY *DRAMINE *\/ *EPHEDRINE *\/ *AMMONIUM CHLORIDE *\/ *SODIUM CITRATE/CHLORPHENIRAMINE MALEATE \/ PROMETHAZINE \/ DIPHENHYDRAMINE \/ EPHEDRINE \/ AMMONIUM CHLORIDE \/ SODIUM CITRATE/g' | \
sed 's/CHLORPHENIRAMINE *\/ *DEXAMETHASONE/CHLORPHENIRAMINE \/ DEXAMETHASONE/g' | \
sed 's/CHLORPHENIRAMINE *\/ *DEXTROMETHORPHAN HBR *\/ *PHENYLEPHRINE HCL/CHLORPHENIRAMINE \/ DEXTROMETHORPHAN HBR \/ PHENYLEPHRINE HCL/g' | \
sed 's/CHLORPHENIRAMINE *\/ *DEXTROMETHORPHAN *\/ *PHENYLEPHRINE/CHLORPHENIRAMINE \/ DEXTROMETHORPHAN \/ PHENYLEPHRINE/g' | \
sed 's/CHLORPHENIRAMINE *\/ *GUAIFENESIN *\/ *AMMONIUM CHLORIDE/CHLORPHENIRAMINE \/ GUAIFENESIN \/ AMMONIUM CHLORIDE/g' | \
sed 's/CHLORPHENIRAMINE *\/ *PHENYLEPHRINE *\/ *DEXTROMETHORPHAN/CHLORPHENIRAMINE \/ PHENYLEPHRINE \/ DEXTROMETHORPHAN/g' | \
sed 's/CHLORPHENIRAMINE *\/ *PROMETHAZINE *\/ *DIPHENHYDRAMINE *\/ *EPHEDRINE *\/ *AMMONIUM CHLORIDE *\/ *SODIUM CITRATE/CHLORPHENIRAMINE \/ PROMETHAZINE \/ DIPHENHYDRAMINE \/ EPHEDRINE \/ AMMONIUM CHLORIDE \/ SODIUM CITRATE/g' | \
sed 's/CHOLINE SALICYLATE *\/ *LIDOC *AINE/CHOLINE SALICYLATE \/ LIDOCAINE/g' | \
sed 's/CLOBETASOL *\/ *GENTAMICIN *\/ *MICONAZOLE/CLOBETASOL \/ GENTAMICIN \/ MICONAZOLE/g' | \
sed 's/DEXAMETHASONE *\/ *CHLORAMPHENICOL/DEXAMETHASONE \/ CHLORAMPHENICOL/g' | \
sed 's/DEXAMETHASONE *\/ *NEOMYCIN *\/ *POLYMYXIN B/DEXAMETHASONE \/ NEOMYCIN \/ POLYMYXIN B/g' | \
sed 's/DEXAMETHASONE *\/ *NEOMYCIN/DEXAMETHASONE \/ NEOMYCIN/g' | \
sed 's/DI-IODO HYDROXYQUINOLI *NE *\/ *SULPHATHIAZOLE *\/ *HOMATROPINE *\/ *STREPTOMYCIN/DIIODOHYDROXYQUINOLINE \/ SULPHATHIAZOLE \/ HOMATROPINE \/ STREPTOMYCIN/g' | \
sed 's/DICLOFENAC *\/ *METHYL SALICYLATE *\/ *MENTHOL *\/ *CAPSICUM EXTRACT/DICLOFENAC \/ METHYL SALICYLATE \/ MENTHOL \/ CAPSICUM EXTRACT/g' | \
sed 's/DICLOFENAC *\/ *PARA *CETAMOL *\/ *CHLORZOXAZONE/DICLOFENAC \/ PARACETAMOL \/ CHLORZOXAZONE/g' | \
sed 's/DIHYDROARTEMISININ *\/ *PIPERAQUINE PHOSPHATE/DIHYDROARTEMISININ \/ PIPERAQUINE PHOSPHATE/g' | \
sed 's/DIPHENHYDRAMINE HCL *\/ *DEXTROMETHORPHAN HBR/DIPHENHYDRAMINE HCL \/ DEXTROMETHORPHAN HBR/g' | \
sed 's/DIPHENHYDRAMINE *\/ *DEXTROMETHORPHAN/DIPHENHYDRAMINE \/ DEXTROMETHORPHAN/g' | \
sed 's/DISODIUM BISPHOSPHATE *\/ *SODIUM PHOSPHATE/DISODIUM BISPHOSPHATE \/ SODIUM PHOSPHATE/g' | \
sed 's/ECONAZOLE *\/ *TRIAMCINOLONE *\/ *GENTAMICIN/ECONAZOLE \/ TRIAMCINOLONE \/ GENTAMICIN/g' | \
sed 's/EMTRICITABINE *\/ *TENOFOVIR ALAFENAMIDE/EMTRICITABINE \/ TENOFOVIR ALAFENAMIDE/g' | \
sed 's/EMTRICITABINE *\/ *TENOFOVIR DISOPROXIL/EMTRICITABINE \/ TENOFOVIR DISOPROXIL/g' | \
sed 's/FOLLICLE STIMULATING HORMONE *\/ *LUTEINIZING HORMONE *\/ *150 I.U/FOLLICLE STIMULATING HORMONE \/ LUTEINIZING HORMONE/g' | \
sed 's/FOLLITROPIN ALFA *\/ *LUTROPIN ALFA/FOLLITROPIN ALFA \/ LUTROPIN ALFA/g' | \
sed 's/GLUCOSE *\/ *SODIUM CHLORIDE *\/ *TRISODIUM CITRATE *\/ *POTASSIUM CHLORIDE *\/ *ZINC/GLUCOSE \/ SODIUM CHLORIDE \/ TRISODIUM CITRATE \/ POTASSIUM CHLORIDE \/ ZINC/g' | \
sed 's/IBUPROFEN *\/ *PSEUDOEPHEDRINE/IBUPROFEN \/ PSEUDOEPHEDRINE/g' | \
sed 's/IRBESARTAN *\/ *HYDROCHLOROTHIAZIDE/IRBESARTAN \/ HYDROCHLOROTHIAZIDE/g' | \
sed 's/KETOCONAZOLE *\/ *ZINC PYRITHIONE/KETOCONAZOLE \/ ZINC PYRITHIONE/g' | \
sed 's/LAMIVUDINE *\/ *ZIDOVUDINE/LAMIVUDINE \/ ZIDOVUDINE/g' | \
sed 's/LOPINAVIR *\/ *RITONAVIR/LOPINAVIR \/ RITONAVIR/g' | \
sed 's/LOPINAVIR *\/ *RITONAVIR/LOPINAVIR \/ RITONAVIR/g' | \
sed 's/METRONIDAZOLE *\/ *DILOXANIDE/METRONIDAZOLE \/ DILOXANIDE/g' | \
sed 's/MOMETASONE *\/ *AZELASTINE/MOMETASONE \/ AZELASTINE/g' | \
sed 's/MULTIVITAMIN *\/ *DIASTASE *\/ *PEPSIN/MULTIVITAMIN \/ DIASTASE \/ PEPSIN/g' | \
sed 's/MULTIVITAMIN *\/ *MINERALS/MULTIVITAMIN \/ MINERALS/g' | \
sed 's/PARACETAMOL *\/ *CHLORPHENIRAMINE *\/ *EPHEDRINE/PARACETAMOL \/ CHLORPHENIRAMINE \/ EPHEDRINE/g' | \
sed 's/PARACETAMOL *\/ *DIPHENHYDRAMINE *\/ *PARACETAMOL *\/ *PSEUDOEPHEDRINE/PARACETAMOL \/ DIPHENHYDRAMINE \/ PARACETAMOL \/ PSEUDOEPHEDRINE/g' | \
sed 's/PARACETAMOL *\/ *CAFFEINE TABLETS/PARACETAMOL \/ CAFFEINE TABLETS/g' | \
sed 's/PARACETAMOL *\/ *CAFFEINE/PARACETAMOL \/ CAFFEINE/g' | \
sed 's/PARACETAMOL *\/ *DICLOFENAC/PARACETAMOL \/ DICLOFENAC/g' | \
sed 's/PARACETAMOL *\/ *DIPHENHYDRAMINE CHLORIDE *\/ *PARACETAMOL *\/ *PSEUDOEPHEDRINE/PARACETAMOL \/ DIPHENHYDRAMINE \/ PARACETAMOL \/ PSEUDOEPHEDRINE/g' | \
sed 's/PARACETAMOL *\/ *IBUPROFEN/PARACETAMOL \/ IBUPROFEN/g' | \
sed 's/PARACETAMOL *\/ *PHENYLEPHRINE HYDROCHLORIDE *\/ *CAFFEINE ANHYDROUS *\/ *CHLORPHENIRAMINE/PARACETAMOL \/ PHENYLEPHRINE \/ CAFFEINE \/ CHLORPHENIRAMINE/g' | \
sed 's/PARACETAMOL *\/ *PHENYLEPHRINE HCL *\/ *DEXTROMETHORPHAN HBR *\/ *CHLORPHENIRAMINE MALEATE/PARACETAMOL \/ PHENYLEPHRINE \/ DEXTROMETHORPHAN HBR \/ CHLORPHENIRAMINE MALEATE/g' | \
sed 's/PARACETAMOL *\/ *PHENYLEPHRINE *\/ *CAFFEINE *\/ *CHLORPHENIRAMINE/PARACETAMOL \/ PHENYLEPHRINE \/ CAFFEINE \/ CHLORPHENIRAMINE/g' | \
sed 's/PARACETAMOL *\/ *PSEUDOEPHEDRINE HCL *\/ *CAFFEINE/PARACETAMOL \/ PSEUDOEPHEDRINE \/ CAFFEINE/g' | \
sed 's/PARACETAMOL *\/ *PSEUDOEPHEDRINE *\/ *CHLORPHENIRAMINE/PARACETAMOL \/ PSEUDOEPHEDRINE \/ CHLORPHENIRAMINE/g' | \
sed 's/PARACETAMOL *\/ *TR *AMADOL HYDROCHLORIDE/PARACETAMOL \/ TRAMADOL/g' | \
sed 's/PREDNISOLONE *\/ *CHLORAMPHENICOL/PREDNISOLONE \/ CHLORAMPHENICOL/g' | \
sed 's/RABIES ANTIGEN DERIVED FROM RABIES VIRUS(L.PASTEUR 2061 *\/ *VERO STRAIN)/RABIES ANTIGEN DERIVED FROM RABIES VIRUS (L.PASTEUR 2061 \/ VERO STRAIN)/g' | \
sed 's/SALBUTAMOL SULFATE *\/ *AMBROXOL SULFATE *\/ *GUAIFENESIN *\/ *MENTHOL/SALBUTAMOL \/ AMBROXOL \/ GUAIFENESIN \/ MENTHOL/g' | \
sed 's/SALBUTAMOL *\/ *AMBROXOL *\/ *GUAIFENESIN *\/ *MENTHOL/SALBUTAMOL \/ AMBROXOL \/ GUAIFENESIN \/ MENTHOL/g' | \
sed 's/SALMETEROL *\/ *FLUTICASONE/SALMETEROL \/ FLUTICASONE/g' | \
sed 's/(SULFADOXINE *\/ *PYRIMETHAMINE) *\/ *AMODIAQUINE/SULFADOXINE \/ PYRIMETHAMINE \/ AMODIAQUINE/g' | \
sed 's/SULFADOXINE *\/ *PYRIMETHAMINE/SULFADOXINE \/ PYRIMETHAMINE/g' | \
sed 's/SULFAMETHOXAZOLE *\/ *TRIMETHOPRIM/SULFAMETHOXAZOLE \/ TRIMETHOPRIM/g' | \
sed 's/TELMISARTAN *\/ *HYDROCHLOROTHIAZIDE/TELMISARTAN \/ HYDROCHLOROTHIAZIDE/g' | \
sed 's/TERBUTALINE *\/ *BROMHEXINE *\/ *GUAIFENESIN/TERBUTALINE \/ BROMHEXINE \/ GUAIFENESIN/g' | \
sed 's/THIAMINE MONONITRATE *\/ *PYRIDOXINE *\/ *CYANOCOBALAMIN/THIAMINE MONONITRATE \/ PYRIDOXINE \/ CYANOCOBALAMIN/g' | \
sed 's/TINIDAZOLE *\/ *CLARITHROMYCIN *\/ *LANSOPRAZOLE/TINIDAZOLE \/ CLARITHROMYCIN \/ LANSOPRAZOLE/g' | \
sed 's/TOBRAMYCIN *\/ *DEX *AMETHASONE/TOBRAMYCIN \/ DEXAMETHASONE/g' | \
sed 's/TRAMADOL *\/ *PARACETAMOL/TRAMADOL \/ PARACETAMOL/g' | \
sed 's/TRIMETHOPRIM *\/ *SULFAMETHOXAZOLE *\/ *BROMHEXINE *\/ *SO *DIUM BENZOATE *\/ *TOLU BALSAM/TRIMETHOPRIM \/ SULFAMETHOXAZOLE \/ BROMHEXINE \/ SODIUM BENZOATE \/ TOLU BALSAM/g' | \
sed 's/TRIMETHOPRIM *\/ *SULFAMETHOXAZOLE/TRIMETHOPRIM \/ SULFAMETHOXAZOLE/g' | \
sed 's/TRIPROLIDINE HCL *\/ *PSEUDOEPHEDRINE *\/ *GUAIPHENE *SIN/TRIPROLIDINE \/ PSEUDOEPHEDRINE \/ GUAIFENESIN/g' | \
sed 's/TRIPROLIDINE HCL *\/ *PSEUDOEPHEDRINE *\/ *GUAIFENESIN/TRIPROLIDINE \/ PSEUDOEPHEDRINE \/ GUAIFENESIN/g' | \
sed 's/VILDAGLIPTIN *\/ *METFORMIN/VILDAGLIPTIN \/ METFORMIN/g' | \
sed 's/VITAMIN C *\/ * VITAMIN A *\/ * ZINC SULFATE/VITAMIN C \/ VITAMIN A \/ ZINC SULFATE/g' | \
sed 's/VITAMINS B1 \/ B2 \/ B6/VITAMIN B1 \/ VITAMIN B2 \/ VITAMIN B6/g' | \
sed 's/VITAMINS B1 \/ B6 \/ B12 WITH L- GLUTAMIC ACID/VITAMIN B1 \/ VITAMIN B6 \/ VITAMIN B12 \/ L-GLUTAMIC ACID/g' | \
sed 's/DIHYDROARTEMISININ *\/ *PIPERAQUINE,/DIHYDROARTEMISININ \/ PIPERAQUINE PHOSPHATE,/g' | \
sed 's/EMTRICITABINE *\/ *TENOFOVIR,/EMTRICITABINE \/ TENOFOVIR DISOPROXIL,/g' | \
sed 's/RIFAMPICIN & ISONIAZID/RIFAMPICIN \/ ISONIAZID/g' | \
sed 's/NDA.MAL.HDP.//g' | \
sed 's/,\([0-9.]\+\) \([0-9.]\+\),/,\1\2,/' | \
sed 's/   */ /g' | cut -f 2- -d "," > last.csv

# rm nl.csv nl2.csv first*.csv second*.csv third*.csv fourth*.csv fifth*.csv chems*.csv

#	Open last.csv in Calc: 
#		Excel: using new workbook, Data -> Get External Data -> Text and in Step 3, choose MDY date formatting
#		Calc: , as separator Date type as DMY for last column
#	1. Replace all ! with , (wait, search again for !)
#	2. Replace all @ with " (save)
#	3. Change date formatting to yyyy-mm-dd, NDA formatting to 00000 (save)
#	x5. Save as XSLX
#	4. Add the header back in
# NDA	LICENSE HOLDER	LOCAL TECHNICAL REPRESENTATIVE	NAME OF DRUG	GENERIC NAME OF DRUG	STRENGTH OF DRUG	MANUFACTURER	COUNTRY OF MANUFACTURE	DOSAGE FORM	PACK SIZE	REG DATE
# 	4. Save as UgandaApr2022.csv, close the worksheet
# 	6. Use ImportKenya.ps1 to import Uganda2022.csv to the database
# 	7. Use ImportUgandaDrugs.sql to repopulate Uganda_Drugs table.
