 #Import-DbaCsv -Path "C:\EncounterPro\RXNORM\11_17_2020 KenyaRetentionDrugsAdditions.csv" -SqlInstance "[DESKTOP-GU15HUD\EncounterPro_OS]"  -Database EncounterPro_Os  -Truncate  -KeepNulls  -AutoCreateTable -UseFileNameForSchema  -TrimmingOption All  -Encoding UTF8  -SkipEmptyLine  -SupportsMultiline  -UseColumnDefault  -NoTransaction  -EnableException 
#Import-DbaCsv -Path "C:\EncounterPro\RXNORM\01_29_2020 KenyaRetentionDrugsUpdate.csv" -SqlInstance "[DESKTOP-GU15HUD\EncounterPro_OS]"  -Database EncounterPro_Os  -Truncate  -KeepNulls  -AutoCreateTable -UseFileNameForSchema  -TrimmingOption All  -Encoding UTF8  -SkipEmptyLine  -SupportsMultiline  -UseColumnDefault  -NoTransaction  -EnableException 
#Import-DbaCsv -Path "C:\EncounterPro\RXNORM\02_21_2021 KenyaVaccines.csv" -SqlInstance "[DESKTOP-GU15HUD\EncounterPro_OS]"  -Database EncounterPro_Os  -Truncate  -KeepNulls  -AutoCreateTable -UseFileNameForSchema  -TrimmingOption All  -Encoding UTF8  -SkipEmptyLine  -SupportsMultiline  -UseColumnDefault  -NoTransaction  -EnableException 
#Import-DbaCsv -Path "C:\EncounterPro\RXNORM\04_06_2021_Vaccine_Formulations_Procedures.csv" -SqlInstance "[DESKTOP-GU15HUD\EncounterPro_OS]"  -Database EncounterPro_Os  -Truncate  -KeepNulls  -AutoCreateTable -UseFileNameForSchema  -TrimmingOption All  -Encoding UTF8  -SkipEmptyLine  -SupportsMultiline  -UseColumnDefault  -NoTransaction  -EnableException 
#Import-DbaCsv -Path "C:\EncounterPro\RXNORM\05_07_2021_VaccineFormulations_DiseaseGroups.csv" -SqlInstance "[DESKTOP-GU15HUD\EncounterPro_OS]"  -Database EncounterPro_Os  -Truncate  -KeepNulls  -AutoCreateTable -UseFileNameForSchema  -TrimmingOption All  -Encoding UTF8  -SkipEmptyLine  -SupportsMultiline  -UseColumnDefault  -NoTransaction  -EnableException 
#Import-DbaCsv -Path "C:\EncounterPro\RXNORM\05_07_2021_VaccineFormulations_Diseases.csv" -SqlInstance "[DESKTOP-GU15HUD\EncounterPro_OS]"  -Database EncounterPro_Os  -Truncate  -KeepNulls  -AutoCreateTable -UseFileNameForSchema  -TrimmingOption All  -Encoding UTF8  -SkipEmptyLine  -SupportsMultiline  -UseColumnDefault  -NoTransaction  -EnableException 
#Import-DbaCsv -Path "C:\EncounterPro\RXNORM\08_01_2021_Kenya_US_Immunizationschedule.csv" -SqlInstance "[DESKTOP-GU15HUD\EncounterPro_OS]"  -Database EncounterPro_Os  -Truncate  -KeepNulls  -AutoCreateTable -UseFileNameForSchema  -TrimmingOption All  -Encoding UTF8  -SkipEmptyLine  -SupportsMultiline  -UseColumnDefault  -NoTransaction  -EnableException 
#Import-DbaCsv -Path "C:\EncounterPro\RXNORM\UgandaDec2021DrugsOnly.csv" -SqlInstance "[DESKTOP-GU15HUD\EncounterPro_OS]"  -Database EncounterPro_Os  -Truncate  -KeepNulls  -AutoCreateTable -UseFileNameForSchema  -TrimmingOption All  -Encoding UTF8  -SkipEmptyLine  -SupportsMultiline  -UseColumnDefault  -NoTransaction  -EnableException 
Import-DbaCsv -Path "C:\EncounterPro\RXNORM\UgandaJan2022.csv" -SqlInstance "[DESKTOP-GU15HUD\EncounterPro_OS]"  -Database EncounterPro_Os  -Truncate  -KeepNulls  -AutoCreateTable -UseFileNameForSchema  -TrimmingOption All  -Encoding UTF8  -SkipEmptyLine  -SupportsMultiline  -UseColumnDefault  -NoTransaction  -EnableException 
