
/*
  observation_id	collection_location_domain	perform_location_domain	collection_procedure_id	
  perform_procedure_id	specimen_type	description	definition	narrative_phrase	observation_type	composite_flag	exclusive_flag	location_pick_flag	location_bill_flag	in_context_flag	display_only_flag	display_style	material_id	default_view	legal_notice	sort_sequence	result_count	status	last_updated	updated_by	id	owner_id	owner_key	observation_key
0001120x	NA	NA	36415	NULL	NULL	RDW	RDW		Lab/Test	N	Y	N	N	N	N	OBO|RRR|CRN	NULL	R	NULL	NULL	NULL	OK	2021-09-30 20:25:13.057	NULL	BDA5B7D2-1058-4DF6-86D6-A980A73CD74A	0	NULL	1774
*/

/*
insert into [c_Observation_treatment_type] (
[observation_id]
      ,treatment_type
	  )select distinct 
	substring(replace( 
		case 
		when detail is null then test_name
		when test_name = 'Progesterone' then
			case when detail = 'Ovulation confirmed' then 'ProgesteroneOvConf'
			when detail = 'Ovulation possible' then 'ProgesteroneOvPoss'
			when detail = 'Ovulation unlikely' then 'ProgesteroneOvUnlk'
			when detail = 'Post menopausal' then 'ProgesteronePostMP'
			else 'Progesterone' end
		when test_name = 'Quantiferon Mitogen - Nil' then
			case when detail = 'Indeterminate' then 'QuantiferonMitogenNI'
			when detail = 'Negative' then 'QuantiferonMitogenNN'
			else 'QuantiferonMitogenN' end
		when test_name = 'Quantiferon TB1/TB2 Antigen - Nil' then
			case when detail = 'Positive if Nil under 8.0' then 'QuantiferonTB1TB2Pos'
			when detail = 'Use Mitogen result' then 'QuantiferonTB1TB2Mit'
			else 'QuantiferonTB1TB2' end		
		when detail = 'Prenatal' or test_name in (
				-- detail on these tests is oriented towards the procedure conditions, not result characterization
				'Glucose', 'Glucose Tolerance', 'SHBG'
					)
			then case when test_name = 'Glucose Tolerance' then
						case when detail = 'Non-Pregnant 2 hour' then 'GlucoseToleranceNP2H'
							when detail = 'Non-Pregnant Fasting' then 'GlucoseToleranceNPF'
							when detail = 'Pregnant 2 hour' then 'GlucoseToleranceP2H'
							when detail = 'Pregnant Fasting' then 'GlucoseTolerancePF'
							else 'GlucoseTolerance' end
			else
				test_name + detail
			end
		else
			test_name + case when detail like 'Vitamin D intoxication has been reported at this level%' 
				then 'Intox' else detail end
		end
	,' ',''),1,20)
	,
	'LAB'
from c_Lab_Reference_Range
-- (167 rows affected)
*/

delete
-- select '''' + observation_id + ''','
from c_Observation_treatment_type 
where observation_id in (
'24-hourUrineCreatini',
'24-hourUrineProtein',
'AdjustedCalcium',
'AFP',
'Albumin',
'Albumine/CreatinineR',
'AlbuminGestational',
'ALP',
'ALT',
'AMH',
'ANATitre',
'Anti-dsDNAIndetermin',
'Anti-dsDNANegative',
'Anti-dsDNAPositive',
'Anti-Myeloperoxidase',
'Anti-Proteinase3',
'Anti-TissueTransglut',
'AnylaseSerum',
'AST',
'Basophils',
'Bicarbonate',
'Calcium',
'CarbamazepineTherape',
'CardiolipinIgG',
'CardiolipinIgM',
'CCPantibodies',
'CEANonsmokers',
'Chloride',
'Cholesterol',
'CholesterolHDLratio',
'Creatinine',
'CreatinineClearance',
'CRP',
'DeamidatedGliadinPep',
'DHEAS',
'DigoxinTherapeuticra',
'DiluteThrombinclotti',
'DirectBilirubin',
'eGFR',
'Eosinophils',
'ESR',
'Ferritin',
'FIBFibrinogen',
'FreeT4',
'FreeT4Gestational',
'Freetestosterone',
'FSH',
'FSHFollicular',
'FSHLuteal',
'FSHMidcycle',
'FSHPost-menopausal',
'FSHPregnant',
'GGT',
'Globulin',
'GlucoseChallenge',
'GlucoseToleranceNP2H',
'GlucoseToleranceNPF',
'GlucoseToleranceP2H',
'GlucoseTolerancePF',
'Haemoglobin',
'HaemoglobinPrenatal',
'HCG',
'HCT(PCV)',
'HCT(PCV)Prenatal',
'HDLCholesterol',
'HepatitisATotalAbCon',
'Homocysteine',
'Insulin',
'LDH',
'LDLCholesterol',
'lgA',
'lgE',
'lgG',
'lgM',
'LH',
'LHFollicular',
'LHLuteal',
'LHMidcycle',
'LHPostmenopausal',
'LHPregnant',
'LipaseSerum',
'LithiumTrough(12hrsp',
'Lymphocytes',
'Magnesium',
'MCH',
'MCHC',
'MCV',
'Monocytes',
'Monomericprolactin',
'Neutrophils',
'NeutrophilsPrenatal',
'NTProBNP',
'Oestradiol',
'OestradiolFollicular',
'OestradiolLuteal',
'OestradiolMid-cycle',
'OestradiolPostMenopa',
'PhenytoinTherapeutic',
'Phosphate',
'PI(INR)',
'PI(INR)Highriskthera',
'PI(INR)Standardriskt',
'PlateletCount',
'Potassium',
'ProgesteroneOvConf',
'ProgesteroneOvPoss',
'ProgesteroneOvUnlk',
'ProgesteronePostMP',
'Prolactin',
'ProteinCreatinineRat',
'Prothrombintime',
'PSA',
'PTH',
'PTT',
'QuantiferonMitogenNI',
'QuantiferonMitogenNN',
'QuantiferonNilIndete',
'QuantiferonTB1TB2Mit',
'QuantiferonTB1TB2Pos',
'RabiesIgG',
'RDW',
'RedBloodCount',
'RedBloodCountPrenata',
'Ret-He',
'RheumatoidFactor',
'RubellalgGConsidered',
'RubellalgGNon-Immune',
'SerumCortisolmorning',
'SerumFolate',
'SHBG',
'SHBGPost-pubertal',
'SHBGPre-pubertal',
'Sodium',
'ThyroperoxidaseAb',
'TissueAutoantibody(A',
'TotalBilirubin',
'TotalProtein',
'TransferrinSaturatio',
'Triglycerides',
'TSH',
'TSHGestational',
'Urea',
'UricAcid',
'Urinecalcium/creatin',
'UrineChloride',
'UrinePotassium',
'UrineSodium',
'ValproicAcidTherapeu',
'VitaminDIntox',
'VitaminDMilddeficien',
'VitaminDModeratetose',
'VitaminDOptimaltarge',
'WhiteBloodCount',
'WhiteBloodCountPrena',
'981^813','981^805','981^814','981^815','981^817','981^851','981^822','981^829','981^808','981^824','981^811','981^825','981^831'
)

INSERT INTO [dbo].[c_Observation_Treatment_Type] VALUES
('24-hourUrineCreatini','LAB'),
('24-hourUrineProtein','LAB'),
('AdjustedCalcium','LAB'),
('AFP','LAB'),
('Albumin','LAB'),
('Albumine/CreatinineR','LAB'),
('AlbuminGestational','LAB'),
('ALP','LAB'),
('ALT','LAB'),
('AMH','LAB'),
('ANATitre','LAB'),
('Anti-dsDNAIndetermin','LAB'),
('Anti-dsDNANegative','LAB'),
('Anti-dsDNAPositive','LAB'),
('Anti-Myeloperoxidase','LAB'),
('Anti-Proteinase3','LAB'),
('Anti-TissueTransglut','LAB'),
('AnylaseSerum','LAB'),
('AST','LAB'),
('Basophils','LAB'),
('Bicarbonate','LAB'),
('Calcium','LAB'),
('CarbamazepineTherape','LAB'),
('CardiolipinIgG','LAB'),
('CardiolipinIgM','LAB'),
('CCPantibodies','LAB'),
('CEANonsmokers','LAB'),
('Chloride','LAB'),
('Cholesterol','LAB'),
('CholesterolHDLratio','LAB'),
('981^813','LAB'),
('Creatinine','LAB'),
('CreatinineClearance','LAB'),
('CRP','LAB'),
('DeamidatedGliadinPep','LAB'),
('DHEAS','LAB'),
('DigoxinTherapeuticra','LAB'),
('DiluteThrombinclotti','LAB'),
('DirectBilirubin','LAB'),
('eGFR','LAB'),
('Eosinophils','LAB'),
('ESR','LAB'),
('Ferritin','LAB'),
('FIBFibrinogen','LAB'),
('981^805','LAB'),
('FreeT4','LAB'),
('FreeT4Gestational','LAB'),
('Freetestosterone','LAB'),
('FSH','LAB'),
('FSHFollicular','LAB'),
('FSHLuteal','LAB'),
('FSHMidcycle','LAB'),
('FSHPost-menopausal','LAB'),
('FSHPregnant','LAB'),
('GGT','LAB'),
('Globulin','LAB'),
('GlucoseChallenge','LAB'),
('981^814','LAB'),
('981^815','LAB'),
('GlucoseToleranceNP2H','LAB'),
('GlucoseToleranceNPF','LAB'),
('GlucoseToleranceP2H','LAB'),
('GlucoseTolerancePF','LAB'),
('Haemoglobin','LAB'),
('HaemoglobinPrenatal','LAB'),
('981^817','LAB'),
('HCG','LAB'),
('HCT(PCV)','LAB'),
('HCT(PCV)Prenatal','LAB'),
('HDLCholesterol','LAB'),
('HepatitisATotalAbCon','LAB'),
('981^851','LAB'),
('Homocysteine','LAB'),
('Insulin','LAB'),
('981^822','LAB'),
('LDH','LAB'),
('LDLCholesterol','LAB'),
('lgA','LAB'),
('lgE','LAB'),
('lgG','LAB'),
('lgM','LAB'),
('LH','LAB'),
('LHFollicular','LAB'),
('LHLuteal','LAB'),
('LHMidcycle','LAB'),
('LHPostmenopausal','LAB'),
('LHPregnant','LAB'),
('LipaseSerum','LAB'),
('LithiumTrough(12hrsp','LAB'),
('Lymphocytes','LAB'),
('Magnesium','LAB'),
('MCH','LAB'),
('MCHC','LAB'),
('MCV','LAB'),
('Monocytes','LAB'),
('Monomericprolactin','LAB'),
('Neutrophils','LAB'),
('NeutrophilsPrenatal','LAB'),
('NTProBNP','LAB'),
('Oestradiol','LAB'),
('OestradiolFollicular','LAB'),
('OestradiolLuteal','LAB'),
('OestradiolMid-cycle','LAB'),
('OestradiolPostMenopa','LAB'),
('PhenytoinTherapeutic','LAB'),
('Phosphate','LAB'),
('PI(INR)','LAB'),
('PI(INR)Highriskthera','LAB'),
('PI(INR)Standardriskt','LAB'),
('PlateletCount','LAB'),
('Potassium','LAB'),
('ProgesteroneOvConf','LAB'),
('ProgesteroneOvPoss','LAB'),
('ProgesteroneOvUnlk','LAB'),
('ProgesteronePostMP','LAB'),
('Prolactin','LAB'),
('ProteinCreatinineRat','LAB'),
('Prothrombintime','LAB'),
('PSA','LAB'),
('PTH','LAB'),
('PTT','LAB'),
('QuantiferonMitogenNI','LAB'),
('QuantiferonMitogenNN','LAB'),
('QuantiferonNilIndete','LAB'),
('QuantiferonTB1TB2Mit','LAB'),
('QuantiferonTB1TB2Pos','LAB'),
('RabiesIgG','LAB'),
('RDW','LAB'),
('RedBloodCount','LAB'),
('RedBloodCountPrenata','LAB'),
('Ret-He','LAB'),
('981^829','LAB'),
('RheumatoidFactor','LAB'),
('RubellalgGConsidered','LAB'),
('RubellalgGNon-Immune','LAB'),
('SerumCortisolmorning','LAB'),
('SerumFolate','LAB'),
('SHBG','LAB'),
('SHBGPost-pubertal','LAB'),
('SHBGPre-pubertal','LAB'),
('Sodium','LAB'),
('981^808','LAB'),
('ThyroperoxidaseAb','LAB'),
('TissueAutoantibody(A','LAB'),
('TotalBilirubin','LAB'),
('TotalProtein','LAB'),
('Transferrin','LAB'),
('TransferrinSaturatio','LAB'),
('Triglycerides','LAB'),
('981^811','LAB'),
('TSH','LAB'),
('TSHGestational','LAB'),
('Urea','LAB'),
('UricAcid','LAB'),
('Urinecalcium/creatin','LAB'),
('UrineChloride','LAB'),
('UrinePotassium','LAB'),
('UrineSodium','LAB'),
('ValproicAcidTherapeu','LAB'),
('981^825','LAB'),
('VitaminDIntox','LAB'),
('VitaminDMilddeficien','LAB'),
('VitaminDModeratetose','LAB'),
('VitaminDOptimaltarge','LAB'),
('WhiteBloodCount','LAB'),
('WhiteBloodCountPrena','LAB'),
('981^831','LAB')