
INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Amphetamine with MAO inhibitor', 'Amphetamine', 'MAO Inhibitor', 'Critical DDI ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Amphetamine', 'Dexmethylphenidate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Amphetamine', 'Dextroamphetamine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Amphetamine', 'Methylphenidate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Amphetamine', 'Lisdexamefetamine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Amphetamine', 'Methamphetamine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Amphetamine', 'Phendimetrazine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Amphetamine', 'Pseudoephedrine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Amphetamine', 'Amphetamine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Amphetamine', 'Benzphetamine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Amphetamine', 'Diethylpropion')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Amphetamine', 'Phentermine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Amphetamine', 'Atomoxetine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('MAO Inhibitor', 'Tranylcypromine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('MAO Inhibitor', 'Phenelzine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('MAO Inhibitor', 'Isocarboxazid')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('MAO Inhibitor', 'Procarbazine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name, qualifier)
VALUES ('MAO Inhibitor', 'Selegiline', 'MAO inhibition takes place at higher doses / non-transdermal route')

INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Atazanavir with gastric pH alkalizing agent', 'Atazanavir', 'PPI', 'Critical DDI ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Atazanavir', 'Atazanavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('PPI', 'Omeprazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('PPI', 'Lansoprazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('PPI', 'Pantoprazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('PPI', 'Rabeprazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('PPI', 'Esmoprazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('PPI', 'Dexlansoprazole')

INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Febuxostat with Azathioprine / Mercaptopurine', 'Febuxostate', 'Azathioprine / Mercaptopurine', 'Critical DDI ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Febuxostat', 'Febuxostat')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Azathioprine / Mercaptopurine', 'Azathioprine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Azathioprine / Mercaptopurine', 'Mercaptopurine')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Selective serotonin reuptake inhibitor (SSRI) with MAO Inhibitor', 'SSRI', 'MAO Inhibitor', 'Critical DDI ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('SSRI', 'Fluoxetine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('SSRI', 'Paroxetine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('SSRI', 'Citalopram')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('SSRI', 'Escitalopram')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('SSRI', 'Sertraline')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('SSRI', 'Fluvoxamine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('SSRI', 'Duloxetine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('SSRI', 'Nefazodone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('SSRI', 'Desvenlafaxine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('SSRI', 'Milnacipran')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('SSRI', 'Venlafaxine')

INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Irinotecan with CYP3A4 Inhibitor', 'Irinotecan', 'CYP3A4 Inhibitor', 'Critical DDI ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Irinotecan', 'Irinotecan')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Ritonavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Nelfinavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Atazanavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Indinavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Saquinavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Amprenavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Darunavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Lopinavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Tipranavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Fosamprenavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Saquinavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Clarithromycin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Erythromycin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Telithromycin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Amiodarone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Verapamil')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Diltiazem')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Ketoconazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Itraconazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Fluconazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Voriconazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Nefazodone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Aprepitant')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor', 'Cimetidine')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Narcotic analgesic with MAO inhibitor', 'Narcotic Analgesic', 'MAO Inhibitor', 'Critical DDI ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Narcotic Analgesic', 'Meperidine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Narcotic Analgesic', 'Methadone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Narcotic Analgesic', 'Tapentadol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Narcotic Analgesic', 'Fentanyl')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Narcotic Analgesic', 'Tramadol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Narcotic Analgesic', 'Dextromethorphan')



INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Tricyclic Antidepressant with MAO Inhibitor', 'TCA', 'MAO Inhibitor', 'Critical DDI ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('TCA', 'Amineptine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('TCA', 'Amitriptyline')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('TCA', 'Amoxapine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('TCA', 'Butriptyline')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('TCA', 'Clomipramine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('TCA', 'Desipramine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('TCA', 'Dibenzepin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('TCA', 'Dosulepin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('TCA', 'Doxepin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('TCA', 'Imipramine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('TCA', 'Iprindole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('TCA', 'Lofepramine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('TCA', 'Maprotiline')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('TCA', 'Norclomipramine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('TCA', 'Northiaden')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('TCA', 'Nortriptyline')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('TCA', 'Opipramol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('TCA', 'Protriptyline')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('TCA', 'Tianeptine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('TCA', 'Trimipramine')

-- These will flag for all uses of any one of these drugs along with another one of them
INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('QT prolonging agent with Known Risk of torsades de pointes', 'QT prolonging agent', 'QT prolonging agent', 'Critical DDI ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Aclarubicin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Amiodarone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Anagrelide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Arsenic trioxide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Azithromycin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Chloroquine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Chlorpromazine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Cilostazol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Ciprofloxacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Citalopram')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Clarithromycin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Cocaine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Disopyramide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Dofetilide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Domperidone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Donepezil')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Dronedarone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Droperidol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Erythromycin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Escitalopram')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Flecainide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Fluconazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Halofantrine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Haloperidol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Ibogaine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Ibutilide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Levofloxacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Levomepromazine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Methotrimeprazine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Levosulpiride')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Methadone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Moxifloxacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Ondansetron')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Oxaliplatin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Papaverine HCl (Intra-coronary)')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Pentamidine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Pimozide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Procainamide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Propofol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Quinidine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Roxithromycin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Sevoflurane')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Sotalol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Sulpiride')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Sultopride')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Terlipressin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Terodiline')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Thioridazine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Vandetanib')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('QT prolonging agent', 'Nilotinib')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Ramelteon with CYP1A2 Inhibitor', 'Ramelteon', 'Strong CYP1A2 Inhibitor', 'Critical DDI ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('Ramelteon', 'Ramelteon')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('Strong CYP1A2 Inhibitor', 'Fluvoxamine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('Strong CYP1A2 Inhibitor', 'Amiodarone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('Strong CYP1A2 Inhibitor', 'Ticlopidine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('Strong CYP1A2 Inhibitor', 'Ciprofloxacin')

INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Strong CYP3A4 Inducer with Protease Inhibitor (dosage dependent)', 'Strong CYP3A4 Inducer', 'Protease Inhibitor', 'Critical DDI ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('Strong CYP3A4 Inducer', 'Bosentan')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Strong CYP3A4 Inducer', 'Rifapentine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Strong CYP3A4 Inducer', 'Carbamazepine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Strong CYP3A4 Inducer', 'Rifabutin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Strong CYP3A4 Inducer', 'Rifampin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Strong CYP3A4 Inducer', 'St John''s wort')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Protease Inhibitor', 'Ritonavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Protease Inhibitor', 'Nelfinavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Protease Inhibitor', 'Atazanavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Protease Inhibitor', 'Indinavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Protease Inhibitor', 'Saquinavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Protease Inhibitor', 'Amprenavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Protease Inhibitor', 'Darunavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Protease Inhibitor', 'Lopinavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Protease Inhibitor', 'Tipranavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Protease Inhibitor', 'Fosamprenavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Protease Inhibitor', 'Saquinavir')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('HMG Co-A Reductase Inhibitor with CYP3A4 Inhibitor', 'HMG Co-A Reductase Inhibitor', 'CYP3A4 Inhibitor', 'Critical DDI ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('HMG Co-A Reductase Inhibitor', 'Simvastatin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('HMG Co-A Reductase Inhibitor', 'Lovastatin')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('CYP3A4 Inhibitor with Ergot Alkaloid', 'CYP3A4 Inhibitor / Ergot', 'Ergot Alkaloid', 'Critical DDI ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('Ergot Alkaloid', 'Ergotamine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('Ergot Alkaloid', 'Methylergon')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('Ergot Alkaloid', 'Dihydroergot')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('Ergot Alkaloid', 'Ergonovine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor / Ergot', 'Ritonavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor / Ergot', 'Nelfinavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor / Ergot', 'Atazanavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor / Ergot', 'Indinavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor / Ergot', 'Saquinavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor / Ergot', 'Amprenavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor / Ergot', 'Darunavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor / Ergot', 'Lopinavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor / Ergot', 'Tipranavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor / Ergot', 'Fosamprenavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor / Ergot', 'Saquinavir')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor / Ergot', 'Clarithromycin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor / Ergot', 'Erythromycin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor / Ergot', 'Telithromycin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor / Ergot', 'Ketoconazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor / Ergot', 'Itraconazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('CYP3A4 Inhibitor / Ergot', 'Voriconazole')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Tizanidine with CYP1A2 Inhibitor', 'Tizanidine', 'CYP1A2 Inhibitor', 'Critical DDI ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('Tizanidine', 'Tizanidine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('CYP1A2 Inhibitor', 'Fluvoxamine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('CYP1A2 Inhibitor', 'Amiodarone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('CYP1A2 Inhibitor', 'Ticlopidine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('CYP1A2 Inhibitor', 'Ciprofloxacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('CYP1A2 Inhibitor', 'Mexiletine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('CYP1A2 Inhibitor', 'Propafenone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('CYP1A2 Inhibitor', 'Zileuton')



INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Tranylcypromine with Procarbazine', 'Tranylcypromine', 'Procarbazine', 'Critical DDI ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('Tranylcypromine', 'Tranylcypromine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('Procarbazine', 'Procarbazine')

INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Triptan with MAO inhibitor', 'Triptan', 'MAO inhibitor', 'Critical DDI ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('Triptan', 'Sumatriptan')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('Triptan', 'Zolmitriptan')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) 
VALUES ('Triptan', 'Rizatriptan')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Triptan / MAO Inhibitor', 'Tranylcypromine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Triptan / MAO Inhibitor', 'Phenelzine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Triptan / MAO Inhibitor', 'Isocarboxazid')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Triptan / MAO Inhibitor', 'Procarbazine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Triptan / MAO Inhibitor', 'Moclobamide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name)
VALUES ('Triptan / MAO Inhibitor', 'Methylene blue')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('ACE Inhibitor with Salicylate', 'ACE Inhibitor', 'Salicylate', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('ACE Inhibitor', 'benazepril')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('ACE Inhibitor', 'captopril')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('ACE Inhibitor', 'enalapril')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('ACE Inhibitor', 'fosinopril')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('ACE Inhibitor', 'lisinopril')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('ACE Inhibitor', 'perindopril')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('ACE Inhibitor', 'quinapril')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('ACE Inhibitor', 'ramipril')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('ACE Inhibitor', 'trandolapril')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('ACE Inhibitor', 'moexipril')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('ACE Inhibitor', 'Cilazapril')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('ACE Inhibitor', 'Imidapril')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Salicylate', 'Aminosalicylate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Salicylate', 'Methacholine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Salicylate', 'Morpholine Salicylate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Salicylate', 'Niclosamide')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Niacin with Statin', 'Niacin', 'Statin', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Niacin', 'Niacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Statin', 'Simvastatin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Statin', 'Atorvastatin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Statin', 'Fluvastatin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Statin', 'Lovastatin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Statin', 'Pravastatin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Statin', 'Rosuvastatin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Statin', 'Mevastatin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Statin', 'Cerivastatin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Statin', 'Pitavastatin')

INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('β-Adrenergic blocker with Serotonin reuptake blocker', 'β-Adrenergic blocker', 'Serotonin reuptake blocker', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('β-Adrenergic blocker', 'Acebutolol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('β-Adrenergic blocker', 'Alprenolol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('β-Adrenergic blocker', 'Atenolol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('β-Adrenergic blocker', 'Betaxolol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('β-Adrenergic blocker', 'Bisoprolol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('β-Adrenergic blocker', 'bopindolol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('β-Adrenergic blocker', 'Bupranolol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('β-Adrenergic blocker', 'Carteolol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('β-Adrenergic blocker', 'carvedilol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('β-Adrenergic blocker', 'esmolol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('β-Adrenergic blocker', 'Labetalol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('β-Adrenergic blocker', 'Metoprolol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('β-Adrenergic blocker', 'Nadolol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('β-Adrenergic blocker', 'nebivolol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('β-Adrenergic blocker', 'Oxprenolol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('β-Adrenergic blocker', 'Penbutolol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('β-Adrenergic blocker', 'Pindolol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('β-Adrenergic blocker', 'Practolol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('β-Adrenergic blocker', 'Propranolol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('β-Adrenergic blocker', 'Sotalol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('β-Adrenergic blocker', 'tertatolol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('β-Adrenergic blocker', 'Timolol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Statin', 'Citalopram')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Statin', 'Escitalopram')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Statin', 'Fluoxetine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Statin', 'Fluvoxamine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Statin', 'Paroxetine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Statin', 'Sertraline')

INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Iron salt with Proton pump inhibitor', 'Iron salt', 'Proton pump inhibitor', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Iron salt', 'Iron-Dextran')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Iron salt', 'Ferric Carboxymaltose')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Iron salt', 'Sodium Ferric Gluconate complex')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Iron salt', 'Iron sucrose complex')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Iron salt', 'Ferrous sulfate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Iron salt', 'Ferrous gluconate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Iron salt', 'Ferrous fumarate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Proton pump inhibitor', 'Omeprazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Proton pump inhibitor', 'Lansoprazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Proton pump inhibitor', 'Pantoprazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Proton pump inhibitor', 'Rabeprazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Proton pump inhibitor', 'Esmoprazole')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Thiazide-type diuretic with ACE Inhibitor', 'Thiazide-type diuretic', 'ACE Inhibitor', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Thiazide-type diuretic', 'Cyclopenthiazide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Thiazide-type diuretic', 'cyclothiazide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Thiazide-type diuretic', 'Trichlormethiazide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Thiazide-type diuretic', 'Bendroflumethiazide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Thiazide-type diuretic', 'Chlorothiazide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Thiazide-type diuretic', 'Hydrochlorothiazide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Thiazide-type diuretic', 'Hydroflumethiazide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Thiazide-type diuretic', 'Methyclothiazide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Thiazide-type diuretic', 'Polythiazide')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Thyroid hormone with Calcium salt', 'Thyroid hormone', 'Calcium salt', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Thyroid hormone', 'Thyroid USP')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Thyroid hormone', 'Levothyroxine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Thyroid hormone', 'Liothyronine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Thyroid hormone', 'Liotrix')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Calcium salt', 'Calcium Acetate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Calcium salt', 'Calcium Carbonate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Calcium salt', 'Calcium Citrate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Calcium salt', 'Calcium Glubionate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Calcium salt', 'Calcium Gluconate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Calcium salt', 'Calcium Lactate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Calcium salt', 'Tricalcium Phosphate')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Thyroid hormone with Statin', 'Thyroid hormone', 'Statin', 'Non-Interruptive ONC')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Thiazide-type diuretic with NSAID', 'Thiazide-type diuretic', 'NSAID', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Aceclofenac')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Aspirin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Celecoxib')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Diclofenac')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Diflunisal')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Etodolac')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Fenoprofen')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Flurbiprofen')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Ibuprofen')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Indomethacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Ketoprofen')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Ketorolac')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Lornoxicam')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'meloxicam')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'nabumetone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Naproxen')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Nimesulide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Oxaprozin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Piroxicam')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Rofecoxib')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Salsalate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Sulindac')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Tolmetin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Valdecoxib')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Meclofenamate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('NSAID', 'Mefenamic acid')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('β-Adrenergic blocker with Thyroid hormone', 'β-Adrenergic blocker', 'Thyroid hormone', 'Non-Interruptive ONC')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Macrolide immunosuppressive with Corticosteroid', 'Macrolide immunosuppressive', 'Corticosteroid', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Macrolide immunosuppressive', 'Tacrolimus')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Macrolide immunosuppressive', 'Sirolimus')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Macrolide immunosuppressive', 'Everolimus')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Corticosteroid', 'Betamethasone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Corticosteroid', 'Budesonide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Corticosteroid', 'cortisone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Corticosteroid', 'Dexamethasone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Corticosteroid', 'Hydrocortisone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Corticosteroid', 'Methylprednisolone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Corticosteroid', 'Prednisolone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Corticosteroid', 'Prednisone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Corticosteroid', 'flunisolide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Corticosteroid', 'fluticasone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Corticosteroid', 'triamcinolone')



INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Antacid with Oral Corticosteroid', 'Antacid', 'Oral Corticosteroid', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Antacid', 'Aluminum Hydroxide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Antacid', 'Calcium Carbonate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Antacid', 'dihydroxyaluminum aminoacetate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Antacid', 'Magnesium Oxide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Antacid', 'Sodium Bicarbonate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Corticosteroid', 'cortisone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Corticosteroid', 'Dexamethasone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Corticosteroid', 'Hydrocortisone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Corticosteroid', 'Methylprednisolone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Corticosteroid', 'Prednisolone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Corticosteroid', 'Prednisone')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Bisphosphonate with Calcium salt', 'Bisphosphonate', 'Calcium salt', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Bisphosphonate', 'Etidronate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Bisphosphonate', 'Clodronate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Bisphosphonate', 'Tiludronate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Bisphosphonate', 'Pamidronate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Bisphosphonate', 'Neridronate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Bisphosphonate', 'Olpadronate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Bisphosphonate', 'Alendronate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Bisphosphonate', 'Ibandronate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Bisphosphonate', 'Risedronate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Bisphosphonate', 'Zoledronate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Bisphosphonate', 'cobalamin')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Vitamin B12 with Omeprazole', 'cobalamin', 'Omeprazole', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('cobalamin', 'cobalamin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Omeprazole', 'Omeprazole')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Folic Acid with Omeprazole', 'Folic Acid', 'Methotrexate', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Folic Acid', 'Folic Acid')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Methotrexate', 'Methotrexate')



INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Sulfonylurea with ACE Inhibitor', 'Sulfonylurea', 'ACE Inhibitor', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Sulfonylurea', 'Carbutamide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Sulfonylurea', 'Chlorpropamide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Sulfonylurea', 'Tolbutamide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Sulfonylurea', 'Tolazamide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Sulfonylurea', 'Glipizide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Sulfonylurea', 'Gliclazide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Sulfonylurea', 'Glibenclamide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Sulfonylurea', 'Glibornuride')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Sulfonylurea', 'Gliquidone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Sulfonylurea', 'Glisoxepide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Sulfonylurea', 'Glyclopyramide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Sulfonylurea', 'Glimepiride')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Iron salt with Thyroid hormone', 'Iron salt', 'Thyroid hormone', 'Non-Interruptive ONC')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Anticoagulant with Corticosteroid', 'Anticoagulant', 'Corticosteroid', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Anticoagulant', 'Dalteparin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Anticoagulant', 'Enoxaparin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Anticoagulant', 'Fondaparinux')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Anticoagulant', 'Lepirudin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Anticoagulant', 'Warfarin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Anticoagulant', 'Dipyridamole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Anticoagulant', 'dabigatran')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Anticoagulant', 'apixaban')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Anticoagulant', 'rivaroxaban')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Anticoagulant', 'anagrelide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Anticoagulant', 'bivalirudin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Anticoagulant', 'argatroban')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Anticoagulant', 'heparin')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Anticoagulant with Acetaminophen', 'Anticoagulant', 'Acetaminophen', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Acetaminophen', 'Acetaminophen')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Antacid with Oral Iron salt', 'Antacid', 'Oral Iron salt', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Iron salt', 'Ferrous sulfate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Iron salt', 'Ferrous gluconate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Iron salt', 'Ferrous fumarate')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Anticoagulant with Proton pump inhibitor', 'Anticoagulant', 'Proton pump inhibitor', 'Non-Interruptive ONC')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Proton pump inhibitor with Imidazole', 'Proton pump inhibitor', 'Imidazole', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Imidazole', 'Bifonazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Imidazole', 'Butoconazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Imidazole', 'Clotrimazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Imidazole', 'Econazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Imidazole', 'Fenticonazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Imidazole', 'Isoconazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Imidazole', 'Ketoconazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Imidazole', 'Luliconazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Imidazole', 'Miconazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Imidazole', 'Omoconazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Imidazole', 'Oxiconazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Imidazole', 'Sertaconazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Imidazole', 'Sulconazole')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Imidazole', 'Tioconazole')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('β-Adrenergic blocker with Oral Calcium salt', 'β-Adrenergic blocker', 'Calcium salt', 'Non-Interruptive ONC')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('ACE Inhibitor with Angiotensin II receptor antagonist', 'ACE Inhibitor', 'Angiotensin II receptor antagonist', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Angiotensin II receptor antagonist', 'Valsartan')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Angiotensin II receptor antagonist', 'Telmisartan')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Angiotensin II receptor antagonist', 'Losartan')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Angiotensin II receptor antagonist', 'Irbesartan')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Angiotensin II receptor antagonist', 'Azilsartan')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Angiotensin II receptor antagonist', 'Olmesartan')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Angiotensin II receptor antagonist', 'Candesartan')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Angiotensin II receptor antagonist', 'Eprosartan')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Anticoagulant with Statin', 'Anticoagulant', 'Statin', 'Non-Interruptive ONC')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Omeprazole with Benzodiazepine', 'Omeprazole', 'Benzodiazepine', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Benzodiazepine', 'Alprazolam')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Benzodiazepine', 'Bromazepam')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Benzodiazepine', 'Brotizolam')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Benzodiazepine', 'Chlordiazepoxide')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Benzodiazepine', 'Clonazepam')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Benzodiazepine', 'Clorazepate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Benzodiazepine', 'Clotiazepam')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Benzodiazepine', 'Cloxazolam')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Benzodiazepine', 'Diazepam')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Benzodiazepine', 'Estazolam')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Benzodiazepine', 'Etizolam')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Benzodiazepine', 'Flunitrazepam')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Benzodiazepine', 'Flurazepam')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Benzodiazepine', 'Loprazolam')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Benzodiazepine', 'Lorazepam')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Benzodiazepine', 'Midazolam')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Benzodiazepine', 'Nitrazepam')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Benzodiazepine', 'Nordazepam')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Benzodiazepine', 'Oxazepam')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Benzodiazepine', 'Temazepam')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Anticoagulant with Vitamin E', 'Anticoagulant', 'Vitamin E', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Vitamin E', 'Vitamin E')



INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Oral Zinc salt with Oral Quinolone', 'Oral Zinc salt', 'Oral Quinolone', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Zinc salt', 'Zinc  Acetate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Zinc salt', 'zinc sulfate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Zinc salt', 'Zinc Gluconate')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Quinolone', 'Ciprofloxacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Quinolone', 'enoxacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Quinolone', 'fleroxacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Quinolone', 'lomefloxacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Quinolone', 'nadifloxacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Quinolone', 'norfloxacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Quinolone', 'ofloxacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Quinolone', 'pefloxacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Quinolone', 'rufloxacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Quinolone', 'balofloxacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Quinolone', 'levofloxacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Quinolone', 'pazufloxacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Quinolone', 'tosufloxacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Quinolone', 'gatifloxacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Quinolone', 'gemifloxacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Quinolone', 'moxifloxacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Quinolone', 'sitafloxacin')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral Quinolone', 'prulifloxacin')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('NSAID with β-Adrenergic blocker', 'NSAID', 'β-Adrenergic blocker', 'Non-Interruptive ONC')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Clopidogrel with Salicylate', 'Clopidogrel', 'Salicylate', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Clopidogrel', 'Clopidogrel')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Oral contraceptive with Corticosteroid', 'Oral contraceptive', 'Corticosteroid', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral contraceptive', 'Desogestrel')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral contraceptive', 'ethynodiol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral contraceptive', 'Etonogestrel')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral contraceptive', 'Levonorgestrel')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral contraceptive', 'Medroxyprogesterone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral contraceptive', 'Megestrol')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral contraceptive', 'Norethindrone')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Oral contraceptive', 'Norgestrel')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Corticosteroid with Anticholinesterase', 'Corticosteroid', 'Anticholinesterase', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Anticholinesterase', 'Physostigmine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Anticholinesterase', 'neostigmine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Anticholinesterase', 'Pyridostigmine')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Anticholinesterase', 'Ambenonium')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Anticholinesterase', 'Demecariuim')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Anticholinesterase', 'Edrophonium')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('Corticotropin with Anticholinesterase', 'Corticotropin', 'Anticholinesterase', 'Non-Interruptive ONC')
INSERT INTO c_Drug_Interaction_Class (drug_class, generic_drug_name) VALUES ('Corticotropin', 'Corticotropin')


INSERT INTO c_Drug_Interaction (interaction_name, object_drug_class, precipitant_drug_class, alert_level)
VALUES ('ACE inhibitor with NSAID', 'ACE inhibitor', 'NSAID', 'Non-Interruptive ONC')

update di
set generic_rxcui = g.generic_rxcui
from c_drug_interaction_class di
join c_drug_generic g
on g.generic_name = di.generic_drug_name
-- 380
