IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[c_Unit]') AND type in (N'U'))
ALTER TABLE [c_Unit] DROP CONSTRAINT IF EXISTS [PK_c_Unit_1__10] WITH ( ONLINE = OFF )

SET ANSI_PADDING ON

ALTER TABLE c_Unit ALTER COLUMN unit_id varchar(30) NOT NULL

ALTER TABLE [c_Unit] ADD  CONSTRAINT [PK_c_Unit_1__10] PRIMARY KEY CLUSTERED 
(
	[unit_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]


GO



