
-- Assume if first and last ones are not present, all have not yet been inserted.
IF NOT EXISTS (SELECT 1 FROM [u_Top_20] 
	WHERE [user_id] = '$CARDIO'
	AND [top_20_code] = 'Patient Instructions_MEDICATION'
	AND item_text = 'Check pulse before taking medication'
	)
	AND NOT EXISTS (SELECT 1 FROM [u_Top_20] 
	WHERE [user_id] = '$PEDS'
	AND [top_20_code] = 'Pharmacist Instructions_MEDICATION'
	AND item_text = 'May Not Substitute'
	)
BEGIN
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$CARDIO','Patient Instructions_MEDICATION','Check pulse before taking medication')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$CARDIO','Patient Instructions_MEDICATION','(1) Take 4 tablets daily for 5 days with breakfast.  (2) Then take 2 tablets daily for 5 days with breakfast.  (3) Then take 1 tablet daily for 5 days with breakfast.  (4) Then take 1/2 tablet on days 16 and 18.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$CARDIO','Patient Instructions_MEDICATION','Contact Physician before taking medication if pulse rate is less than 60 or greater than 100')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$CARDIO','Patient Instructions_MEDICATION','Do not crush or chew.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$CARDIO','Patient Instructions_MEDICATION','Do not take with food')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$CARDIO','Patient Instructions_MEDICATION','If you miss a dose, do not double dose')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$CARDIO','Patient Instructions_MEDICATION','Return to clinic after completing last dose')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$CARDIO','Patient Instructions_MEDICATION','Swallow Whole. Do not crush, chew, or cut.  Take with fluids.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$CARDIO','Patient Instructions_MEDICATION','Take 1 hour before meals')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$CARDIO','Patient Instructions_MEDICATION','Take 1 tab every 12 hours on first day, then one dose per day.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$CARDIO','Patient Instructions_MEDICATION','Take 2 tablets on the first day, then take 1 tablet once per day for the next four days (days 2 through 4)')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$CARDIO','Patient Instructions_MEDICATION','Take 3 tablets per day for 4 days, then 2 tablets per day for 4 days, then 1 tablet per day for 4 days')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$CARDIO','Patient Instructions_MEDICATION','Take at least 30 minutes before meals.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$CARDIO','Patient Instructions_MEDICATION','Take just before bedtime')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$CARDIO','Patient Instructions_MEDICATION','Take on empty stomach.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$CARDIO','Patient Instructions_MEDICATION','Take one tablet daily for 7 days; then take two tablets daily for 7 days; then take three tablets daily for 7 days.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$CARDIO','Patient Instructions_MEDICATION','Take with food')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$CARDIO','Patient Instructions_MEDICATION','Wear for 12 to 14 hours per day. Remove patch for 10 to 12 hours')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$CARDIO','Pharmacist Instructions_MEDICATION','Brand Medically Necessary')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$CARDIO','Pharmacist Instructions_MEDICATION','Dispense as Written')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$DERM','Patient Instructions_MEDICATION','Before applying face lotion')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$EYE','Patient Instructions_MEDICATION','1 drop in each eye at least 4 times a day')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','(1) Take 4 tablets daily for 5 days with breakfast.  (2) Then take 2 tablets daily for 5 days with breakfast.  (3) Then take 1 tablet daily for 5 days with breakfast.  (4) Then take 1/2 tablet on days 16 and 18.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','Apply to eyelids')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','Before applying face lotion')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','Check pulse before taking medication')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','Contact Physician before taking medication if pulse rate is less than 60 or greater than 100')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','Do not take with food')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','Do not take with high fat meals.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','If you miss a dose, do not double dose')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','Place unit between cheek and lower gum, ocassionally switching sides.  Suck, do not chew.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','Return to clinic after completing last dose')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','Swallow Whole. Do not crush, chew, or cut.  Take with fluids.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','Take 1 and 1/2 Tabs in the AM and 1 Tab at Lunch.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','Take 1 hour before meals')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','Take 1 tab at onset of headache.  May repeat after 2 hours.  Take no more than 2 tabs in a 24 hour period.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','Take 1 tab every 12 hours on first day, then one dose per day.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','Take 1 Tab in the AM and 1 Tab at Lunch.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','Take 1 Tab in the AM and 1/2 Tab at Lunch.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','Take 1 to 2 pills every 4 hours as needed for headache pain.  Do not take more than 6 pills per day.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','Take 1 to 2 tabs every 4 hours as needed for pain.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','Take 2 tablets on the first day, then take 1 tablet once per day for the next four days (days 2 through 4)')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','Take 3 tablets per day for 4 days, then 2 tablets per day for 4 days, then 1 tablet per day for 4 days')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','Take just before bedtime')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Patient Instructions_MEDICATION','Take one tablet daily for 7 days; then take two tablets daily for 7 days; then take three tablets daily for 7 days.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Pharmacist Instructions_MEDICATION','Brand Medically Necessary')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Pharmacist Instructions_MEDICATION','Dispense as Written')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Pharmacist Instructions_MEDICATION','Do not fill before _____/_____/_____')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Pharmacist Instructions_MEDICATION','Do not REFILL Prescription')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Pharmacist Instructions_MEDICATION','Do Not Substitute')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FP','Pharmacist Instructions_MEDICATION','May Not Substitute')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FPOB','Patient Instructions_MEDICATION','(1) Take 4 tablets daily for 5 days with breakfast.  (2) Then take 2 tablets daily for 5 days with breakfast.  (3) Then take 1 tablet daily for 5 days with breakfast.  (4) Then take 1/2 tablet on days 16 and 18.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FPOB','Patient Instructions_MEDICATION','Do not take with food')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FPOB','Patient Instructions_MEDICATION','Do not take with high fat meals.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FPOB','Patient Instructions_MEDICATION','If you miss a dose, do not double dose')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FPOB','Patient Instructions_MEDICATION','Place unit between cheek and lower gum, ocassionally switching sides.  Suck, do not chew.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FPOB','Patient Instructions_MEDICATION','Return to clinic after completing last dose')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FPOB','Patient Instructions_MEDICATION','Swallow Whole. Do not crush, chew, or cut.  Take with fluids.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FPOB','Patient Instructions_MEDICATION','Take 1 hour before meals')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FPOB','Patient Instructions_MEDICATION','Take 2 tablets on the first day, then take 1 tablet once per day for the next four days (days 2 through 4)')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FPOB','Patient Instructions_MEDICATION','Take just before bedtime')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FPOB','Patient Instructions_MEDICATION','Take one tablet daily for 7 days; then take two tablets daily for 7 days; then take three tablets daily for 7 days.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FPOB','Patient Instructions_MEDICATION','Take with food')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FPOB','Patient Instructions_MEDICATION','Use one patch per week for three weeks, then one week off')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FPOB','Pharmacist Instructions_MEDICATION','Brand Medically Necessary')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FPOB','Pharmacist Instructions_MEDICATION','Dispense as Written')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FPOB','Pharmacist Instructions_MEDICATION','Do not fill before _____/_____/_____')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FPOB','Pharmacist Instructions_MEDICATION','Do not REFILL Prescription')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FPOB','Pharmacist Instructions_MEDICATION','Do Not Substitute')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$FPOB','Pharmacist Instructions_MEDICATION','May Not Substitute')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$GYN','Patient Instructions_MEDICATION','Take 1 hour before meals')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$GYN','Patient Instructions_MEDICATION','Use one patch per week for three weeks, then one week off')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','(1) Take 4 tablets daily for 5 days with breakfast.  (2) Then take 2 tablets daily for 5 days with breakfast.  (3) Then take 1 tablet daily for 5 days with breakfast.  (4) Then take 1/2 tablet on days 16 and 18.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Apply to eyelids')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Before applying face lotion')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Check pulse before taking medication')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Contact Physician before taking medication if pulse rate is less than 60 or greater than 100')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Do not crush or chew.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Do not take with food')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Do not take with high fat meals.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','If you miss a dose, do not double dose')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Place unit between cheek and lower gum, ocassionally switching sides.  Suck, do not chew.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Return to clinic after completing last dose')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Swallow Whole. Do not crush, chew, or cut.  Take with fluids.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Take 1 and 1/2 Tabs in the AM and 1 Tab at Lunch.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Take 1 hour before meals')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Take 1 tab at onset of headache.  May repeat after 2 hours.  Take no more than 2 tabs in a 24 hour period.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Take 1 tab every 12 hours on first day, then one dose per day.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Take 1 Tab in the AM and 1 Tab at Lunch.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Take 1 Tab in the AM and 1/2 Tab at Lunch.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Take 1 to 2 pills every 4 hours as needed for headache pain.  Do not take more than 6 pills per day.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Take 1 to 2 tabs every 4 hours as needed for pain.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Take 2 tablets on the first day, then take 1 tablet once per day for the next four days (days 2 through 4)')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Take 3 tablets per day for 4 days, then 2 tablets per day for 4 days, then 1 tablet per day for 4 days')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Take at least 30 minutes before meals.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Take just before bedtime')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Take on empty stomach.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Take one tablet daily for 7 days; then take two tablets daily for 7 days; then take three tablets daily for 7 days.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Take with food')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Patient Instructions_MEDICATION','Wear for 12 to 14 hours per day. Remove patch for 10 to 12 hours')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Pharmacist Instructions_MEDICATION','Brand Medically Necessary')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Pharmacist Instructions_MEDICATION','Brand Necessary')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Pharmacist Instructions_MEDICATION','Dispense as Written')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Pharmacist Instructions_MEDICATION','Do not fill before _____/_____/_____')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Pharmacist Instructions_MEDICATION','Do not REFILL Prescription')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Pharmacist Instructions_MEDICATION','Do Not Substitute')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Pharmacist Instructions_MEDICATION','May Not Substitute')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$IM','Pharmacist Instructions_MEDICATION','QS - dispense sufficient quantity as needed')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$OB','Pharmacist Instructions_MEDICATION','Brand Medically Necessary')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$OBGYN','Patient Instructions_MEDICATION','Use one patch per week for three weeks, then one week off')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','(1) Take 4 tablets daily for 5 days with breakfast.  (2) Then take 2 tablets daily for 5 days with breakfast.  (3) Then take 1 tablet daily for 5 days with breakfast.  (4) Then take 1/2 tablet on days 16 and 18.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Before applying face lotion')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Check pulse before taking medication')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Contact Physician before taking medication if pulse rate is less than 60 or greater than 100')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Do not crush or chew.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Do not take with food')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Do not take with high fat meals.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','If you miss a dose, do not double dose')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Place unit between cheek and lower gum, ocassionally switching sides.  Suck, do not chew.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Return to clinic after completing last dose')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Swallow Whole. Do not crush, chew, or cut.  Take with fluids.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Take 1 and 1/2 Tabs in the AM and 1 Tab at Lunch.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Take 1 hour before meals')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Take 1 tab at onset of headache.  May repeat after 2 hours.  Take no more than 2 tabs in a 24 hour period.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Take 1 tab every 12 hours on first day, then one dose per day.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Take 1 Tab in the AM and 1 Tab at Lunch.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Take 1 Tab in the AM and 1/2 Tab at Lunch.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Take 1 to 2 pills every 4 hours as needed for headache pain.  Do not take more than 6 pills per day.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Take 1 to 2 tabs every 4 hours as needed for pain.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Take 2 tablets on the first day, then take 1 tablet once per day for the next four days (days 2 through 4)')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Take 3 tablets per day for 4 days, then 2 tablets per day for 4 days, then 1 tablet per day for 4 days')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Take at least 30 minutes before meals.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Take just before bedtime')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Take on empty stomach.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Take one tablet daily for 7 days; then take two tablets daily for 7 days; then take three tablets daily for 7 days.')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Take with food')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Patient Instructions_MEDICATION','Wear for 12 to 14 hours per day. Remove patch for 10 to 12 hours')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Pharmacist Instructions_MEDICATION','Brand Medically Necessary')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Pharmacist Instructions_MEDICATION','Dispense as Written')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Pharmacist Instructions_MEDICATION','Do not fill before _____/_____/_____')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Pharmacist Instructions_MEDICATION','Do not REFILL Prescription')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Pharmacist Instructions_MEDICATION','Do Not Substitute')
	INSERT INTO [u_Top_20] ([user_id],[top_20_code],item_text) VALUES ('$PEDS','Pharmacist Instructions_MEDICATION','May Not Substitute')
END