
ALTER TABLE [dbo].[Kenya_Drugs] ALTER COLUMN Ingredient varchar(1300)

-- Long names were truncated to 200 chars
UPDATE Kenya_Drugs SET Ingredient = 'bordetella pertussis filamentous hemagglutinin vaccine, inactivated / bordetella pertussis pertactin vaccine, inactivated / bordetella pertussis toxoid vaccine, inactivated / diphtheria toxoid vaccine, inactivated / haemophilus influenzae b polysaccharide conjugated to tetanus toxoid as carrier protein / hepatitis B surface antigen vaccine / poliovirus vaccine inactivated, type 1 (Mahoney) / poliovirus vaccine inactivated, type 2 (MEF-1) / poliovirus vaccine inactivated, type 3 (Saukett) / tetanus toxoid vaccine, inactivated' WHERE [Retention_No] = '4495'
UPDATE Kenya_Drugs SET Ingredient = 'L1 protein, human papillomavirus type 11 vaccine / L1 protein, human papillomavirus type 16 vaccine / L1 protein, human papillomavirus type 18 vaccine / L1 protein, human papillomavirus type 6 vaccine' WHERE [Retention_No] = '7058A'
UPDATE Kenya_Drugs SET Ingredient = 'L1 protein, human papillomavirus type 11 vaccine / L1 protein, human papillomavirus type 16 vaccine / L1 protein, human papillomavirus type 18 vaccine / L1 protein, human papillomavirus type 6 vaccine' WHERE [Retention_No] = '7058B'
UPDATE Kenya_Drugs SET Ingredient = 'v. cholerae O1 Inaba E1 tor strain phil 6973 formaldehyde killed 600 EU / v.cholerae O1 ogawa classical strain cairo 50 heat killed 300 EU / v.cholerae O1 ogawa classical strain cairo 50 formaldehyde killed 300 EU / v.cholerae O1 inaba classical strain cairo 48 heat killed 300 EU / v.cholerae O139 strain 4260B formaldehyde killed 600 EU' WHERE [Retention_No] = '9195'
UPDATE Kenya_Drugs SET Ingredient = 'Neisseria meningitidis serogroup A capsular polysaccharide diphtheria toxoid protein conjugate vaccine / Neisseria meningitidis serogroup C capsular polysaccharide diphtheria toxoid protein conjugate vaccine / Neisseria meningitidis serogroup W-135 capsular polysaccharide diphtheria toxoid protein conjugate vaccine / Neisseria meningitidis serogroup Y capsular polysaccharide diphtheria toxoid protein conjugate vaccine' WHERE [Retention_No] = '6896'
UPDATE Kenya_Drugs SET Ingredient = 'pneumococcal polysaccharide serotype 23F / pneumococcal polysaccharide serotype 4 / pneumococcal polysaccharide serotype 5 / pneumococcal polysaccharide serotype 6B / pneumococcal polysaccharide serotype 7F / pneumococcal polysaccharide serotype 9V / pneumococcal polysaccharide serotype 1 / pneumococcal polysaccharide serotype 14 / pneumococcal polysaccharide serotype 18C / pneumococcal polysaccharide serotype 19F' WHERE [Retention_No] = '7692B'
UPDATE Kenya_Drugs SET Ingredient = 'pneumococcal polysaccharide serotype 23F / pneumococcal polysaccharide serotype 4 / pneumococcal polysaccharide serotype 5 / pneumococcal polysaccharide serotype 6B / pneumococcal polysaccharide serotype 7F / pneumococcal polysaccharide serotype 9V / pneumococcal polysaccharide serotype 1 / pneumococcal polysaccharide serotype 14 / pneumococcal polysaccharide serotype 18C / pneumococcal polysaccharide serotype 19F' WHERE [Retention_No] = '7692A'
-- RXNB596702
UPDATE Kenya_Drugs SET Ingredient = 'Streptococcus pneumoniae serotype 1 capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 14 capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 18C capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 19A capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 19F capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 23F capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 3 capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 4 capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 5 capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 6A capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 6B capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 7F capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 9V capsular antigen diphtheria CRM197 protein conjugate vaccine' WHERE [Retention_No] = '2911'
-- RXNB496892
UPDATE Kenya_Drugs SET Ingredient = 'Human-Bovine Reassortant Rotavirus Strain G1 Vaccine / Human-Bovine Reassortant Rotavirus Strain G2 Vaccine / Human-Bovine Reassortant Rotavirus Strain G3 Vaccine / Human-Bovine Reassortant Rotavirus Strain G4 Vaccine / Human-Bovine Reassortant Rotavirus Strain P1A[8] Vaccine' WHERE [Retention_No] = '10093'

UPDATE c_Drug_Generic SET generic_name = 'bordetella pertussis filamentous hemagglutinin vaccine, inactivated / bordetella pertussis pertactin vaccine, inactivated / bordetella pertussis toxoid vaccine, inactivated / diphtheria toxoid vaccine, inactivated / haemophilus influenzae b polysaccharide conjugated to tetanus toxoid as carrier protein / hepatitis B surface antigen vaccine / poliovirus vaccine inactivated, type 1 (Mahoney) / poliovirus vaccine inactivated, type 2 (MEF-1) / poliovirus vaccine inactivated, type 3 (Saukett) / tetanus toxoid vaccine, inactivated' WHERE drug_id = 'KEGI4495'
UPDATE c_Drug_Generic SET generic_name = 'L1 protein, human papillomavirus type 11 vaccine / L1 protein, human papillomavirus type 16 vaccine / L1 protein, human papillomavirus type 18 vaccine / L1 protein, human papillomavirus type 6 vaccine' WHERE drug_id = 'KEGI7058'
UPDATE c_Drug_Generic SET generic_name = 'L1 protein, human papillomavirus type 11 vaccine / L1 protein, human papillomavirus type 16 vaccine / L1 protein, human papillomavirus type 18 vaccine / L1 protein, human papillomavirus type 6 vaccine' WHERE drug_id = 'KEGI7058A'
UPDATE c_Drug_Generic SET generic_name = 'v. cholerae O1 Inaba E1 tor strain phil 6973 formaldehyde killed 600 EU / v.cholerae O1 ogawa classical strain cairo 50 heat killed 300 EU / v.cholerae O1 ogawa classical strain cairo 50 formaldehyde killed 300 EU / v.cholerae O1 inaba classical strain cairo 48 heat killed 300 EU / v.cholerae O139 strain 4260B formaldehyde killed 600 EU' WHERE drug_id = 'KEGI9195'
UPDATE c_Drug_Generic SET generic_name = 'Neisseria meningitidis serogroup A capsular polysaccharide diphtheria toxoid protein conjugate vaccine / Neisseria meningitidis serogroup C capsular polysaccharide diphtheria toxoid protein conjugate vaccine / Neisseria meningitidis serogroup W-135 capsular polysaccharide diphtheria toxoid protein conjugate vaccine / Neisseria meningitidis serogroup Y capsular polysaccharide diphtheria toxoid protein conjugate vaccine' WHERE drug_id = 'KEGI6896'
UPDATE c_Drug_Generic SET generic_name = 'pneumococcal polysaccharide serotype 23F / pneumococcal polysaccharide serotype 4 / pneumococcal polysaccharide serotype 5 / pneumococcal polysaccharide serotype 6B / pneumococcal polysaccharide serotype 7F / pneumococcal polysaccharide serotype 9V / pneumococcal polysaccharide serotype 1 / pneumococcal polysaccharide serotype 14 / pneumococcal polysaccharide serotype 18C / pneumococcal polysaccharide serotype 19F' WHERE drug_id = 'KEGI7692A'
-- RXNB596702
UPDATE c_Drug_Generic SET generic_name = 'Streptococcus pneumoniae serotype 1 capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 14 capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 18C capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 19A capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 19F capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 23F capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 3 capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 4 capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 5 capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 6A capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 6B capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 7F capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 9V capsular antigen diphtheria CRM197 protein conjugate vaccine' WHERE drug_id = 'KEGI2911'
-- RXNB496892
UPDATE c_Drug_Generic SET generic_name = 'Human-Bovine Reassortant Rotavirus Strain G1 Vaccine / Human-Bovine Reassortant Rotavirus Strain G2 Vaccine / Human-Bovine Reassortant Rotavirus Strain G3 Vaccine / Human-Bovine Reassortant Rotavirus Strain G4 Vaccine / Human-Bovine Reassortant Rotavirus Strain P1A[8] Vaccine' WHERE drug_id = 'KEGI10093'

UPDATE c_Drug_Definition SET generic_name = left('bordetella pertussis filamentous hemagglutinin vaccine, inactivated / bordetella pertussis pertactin vaccine, inactivated / bordetella pertussis toxoid vaccine, inactivated / diphtheria toxoid vaccine, inactivated / haemophilus influenzae b polysaccharide conjugated to tetanus toxoid as carrier protein / hepatitis B surface antigen vaccine / poliovirus vaccine inactivated, type 1 (Mahoney) / poliovirus vaccine inactivated, type 2 (MEF-1) / poliovirus vaccine inactivated, type 3 (Saukett) / tetanus toxoid vaccine, inactivated',497) + '...' WHERE drug_id = 'KEGI4495'
UPDATE c_Drug_Definition SET generic_name = 'L1 protein, human papillomavirus type 11 vaccine / L1 protein, human papillomavirus type 16 vaccine / L1 protein, human papillomavirus type 18 vaccine / L1 protein, human papillomavirus type 6 vaccine' WHERE drug_id = 'KEGI7058A'
UPDATE c_Drug_Definition SET generic_name = 'v. cholerae O1 Inaba E1 tor strain phil 6973 formaldehyde killed 600 EU / v.cholerae O1 ogawa classical strain cairo 50 heat killed 300 EU / v.cholerae O1 ogawa classical strain cairo 50 formaldehyde killed 300 EU / v.cholerae O1 inaba classical strain cairo 48 heat killed 300 EU / v.cholerae O139 strain 4260B formaldehyde killed 600 EU' WHERE drug_id = 'KEGI9195'
UPDATE c_Drug_Definition SET generic_name = 'pneumococcal polysaccharide serotype 23F / pneumococcal polysaccharide serotype 4 / pneumococcal polysaccharide serotype 5 / pneumococcal polysaccharide serotype 6B / pneumococcal polysaccharide serotype 7F / pneumococcal polysaccharide serotype 9V / pneumococcal polysaccharide serotype 1 / pneumococcal polysaccharide serotype 14 / pneumococcal polysaccharide serotype 18C / pneumococcal polysaccharide serotype 19F' WHERE drug_id = 'KEGI7692A'

UPDATE c_Drug_Definition SET generic_name = left('bordetella pertussis filamentous hemagglutinin vaccine, inactivated / bordetella pertussis pertactin vaccine, inactivated / bordetella pertussis toxoid vaccine, inactivated / diphtheria toxoid vaccine, inactivated / haemophilus influenzae b polysaccharide conjugated to tetanus toxoid as carrier protein / hepatitis B surface antigen vaccine / poliovirus vaccine inactivated, type 1 (Mahoney) / poliovirus vaccine inactivated, type 2 (MEF-1) / poliovirus vaccine inactivated, type 3 (Saukett) / tetanus toxoid vaccine, inactivated',497) + '...' WHERE drug_id = 'KEBI4495'
UPDATE c_Drug_Definition SET generic_name = 'L1 protein, human papillomavirus type 11 vaccine / L1 protein, human papillomavirus type 16 vaccine / L1 protein, human papillomavirus type 18 vaccine / L1 protein, human papillomavirus type 6 vaccine' WHERE drug_id = 'KEBI7058A'
UPDATE c_Drug_Definition SET generic_name = 'v. cholerae O1 Inaba E1 tor strain phil 6973 formaldehyde killed 600 EU / v.cholerae O1 ogawa classical strain cairo 50 heat killed 300 EU / v.cholerae O1 ogawa classical strain cairo 50 formaldehyde killed 300 EU / v.cholerae O1 inaba classical strain cairo 48 heat killed 300 EU / v.cholerae O139 strain 4260B formaldehyde killed 600 EU' WHERE drug_id = 'KEBI9195'
UPDATE c_Drug_Definition SET generic_name = 'pneumococcal polysaccharide serotype 23F / pneumococcal polysaccharide serotype 4 / pneumococcal polysaccharide serotype 5 / pneumococcal polysaccharide serotype 6B / pneumococcal polysaccharide serotype 7F / pneumococcal polysaccharide serotype 9V / pneumococcal polysaccharide serotype 1 / pneumococcal polysaccharide serotype 14 / pneumococcal polysaccharide serotype 18C / pneumococcal polysaccharide serotype 19F' WHERE drug_id = 'KEBI7692A'
-- RXNB596702
UPDATE c_Drug_Definition SET generic_name = left('Streptococcus pneumoniae serotype 1 capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 14 capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 18C capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 19A capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 19F capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 23F capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 3 capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 4 capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 5 capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 6A capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 6B capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 7F capsular antigen diphtheria CRM197 protein conjugate vaccine / Streptococcus pneumoniae serotype 9V capsular antigen diphtheria CRM197 protein conjugate vaccine',497) + '...' WHERE drug_id = 'KEBI2911'
