
DROP PROCEDURE IF EXISTS jmjrpt_patient_any_flow
DROP PROCEDURE IF EXISTS sp_cancel_service
DROP PROCEDURE IF EXISTS sp_check_development_status
DROP PROCEDURE IF EXISTS sp_close_encounter_if_done
DROP PROCEDURE IF EXISTS sp_close_todo_encounter
DROP PROCEDURE IF EXISTS sp_complete_service
DROP PROCEDURE IF EXISTS sp_delete_assessment_therapy
DROP PROCEDURE IF EXISTS sp_delete_report
DROP PROCEDURE IF EXISTS sp_dispatch_pharmacist_service
DROP PROCEDURE IF EXISTS sp_get_assessment_therapies
DROP PROCEDURE IF EXISTS sp_get_current_finding
DROP PROCEDURE IF EXISTS sp_get_encounter_services
DROP PROCEDURE IF EXISTS sp_get_exam_observations
DROP PROCEDURE IF EXISTS sp_get_history_questionnaires
DROP PROCEDURE IF EXISTS sp_get_last_discussed_by
DROP PROCEDURE IF EXISTS sp_get_outstanding_objectives
DROP PROCEDURE IF EXISTS sp_get_performed_objectives
DROP PROCEDURE IF EXISTS sp_get_physical_objectives
DROP PROCEDURE IF EXISTS sp_get_physicals
DROP PROCEDURE IF EXISTS sp_get_physicals_with_no_results
DROP PROCEDURE IF EXISTS sp_get_result
DROP PROCEDURE IF EXISTS sp_get_result_loc
DROP PROCEDURE IF EXISTS sp_get_results_by_loc
DROP PROCEDURE IF EXISTS sp_get_stage
DROP PROCEDURE IF EXISTS sp_get_test
DROP PROCEDURE IF EXISTS sp_get_test_attachment_id
DROP PROCEDURE IF EXISTS sp_get_todo_item
DROP PROCEDURE IF EXISTS sp_get_unperformed_objectives
DROP PROCEDURE IF EXISTS sp_get_vitals
DROP PROCEDURE IF EXISTS sp_get_vitals_quick
DROP PROCEDURE IF EXISTS sp_interesting_objectives
DROP PROCEDURE IF EXISTS sp_new_activity_therapy
DROP PROCEDURE IF EXISTS sp_new_assessment_treatment
DROP PROCEDURE IF EXISTS sp_new_encounter_log
DROP PROCEDURE IF EXISTS sp_new_followup_therapy
DROP PROCEDURE IF EXISTS sp_new_history_questionnaire
DROP PROCEDURE IF EXISTS sp_new_medication_therapy
DROP PROCEDURE IF EXISTS sp_new_observation_node
DROP PROCEDURE IF EXISTS sp_new_procedure_therapy
DROP PROCEDURE IF EXISTS sp_new_referral_therapy
DROP PROCEDURE IF EXISTS sp_new_test_therapy
DROP PROCEDURE IF EXISTS sp_order_child_test
DROP PROCEDURE IF EXISTS sp_order_recheck
DROP PROCEDURE IF EXISTS sp_order_service
DROP PROCEDURE IF EXISTS sp_order_service_for
DROP PROCEDURE IF EXISTS sp_order_service_param
DROP PROCEDURE IF EXISTS sp_order_test
DROP PROCEDURE IF EXISTS sp_order_todo_service_enc
DROP PROCEDURE IF EXISTS sp_order_todo_service_patient
DROP PROCEDURE IF EXISTS sp_post_assessments
DROP PROCEDURE IF EXISTS sp_post_billing
DROP PROCEDURE IF EXISTS sp_primary_service_check
DROP PROCEDURE IF EXISTS sp_queue_encounter_report
DROP PROCEDURE IF EXISTS sp_queue_report
DROP PROCEDURE IF EXISTS sp_queue_report_ready
DROP PROCEDURE IF EXISTS sp_queue_report_set_attribute
DROP PROCEDURE IF EXISTS sp_queue_report_set_ready
DROP PROCEDURE IF EXISTS sp_queue_report_type
DROP PROCEDURE IF EXISTS sp_recheck
DROP PROCEDURE IF EXISTS sp_reopen_encounter
DROP PROCEDURE IF EXISTS sp_room_patient_count
DROP PROCEDURE IF EXISTS sp_set_cat_default_results
DROP PROCEDURE IF EXISTS sp_set_discussed_by
DROP PROCEDURE IF EXISTS sp_set_exam_defaults
DROP PROCEDURE IF EXISTS sp_set_location
DROP PROCEDURE IF EXISTS sp_set_obs_default_results
DROP PROCEDURE IF EXISTS sp_set_obs_defaults
DROP PROCEDURE IF EXISTS sp_set_preferred_report
DROP PROCEDURE IF EXISTS sp_set_result
DROP PROCEDURE IF EXISTS sp_set_result_amount
DROP PROCEDURE IF EXISTS sp_set_service_status
DROP PROCEDURE IF EXISTS sp_set_service_todo_item
DROP PROCEDURE IF EXISTS sp_set_test_attachment_id
DROP PROCEDURE IF EXISTS sp_set_test_collected
DROP PROCEDURE IF EXISTS sp_set_test_need_sample
DROP PROCEDURE IF EXISTS sp_set_test_not_collected
DROP PROCEDURE IF EXISTS sp_set_test_performed
DROP PROCEDURE IF EXISTS sp_set_test_send_out
DROP PROCEDURE IF EXISTS sp_start_service
DROP PROCEDURE IF EXISTS sp_synch_execute_database_script
DROP PROCEDURE IF EXISTS sp_synch_execute_database_script_charindex
DROP PROCEDURE IF EXISTS sp_todo_rule_encounter_close
DROP PROCEDURE IF EXISTS sp_todo_service
DROP PROCEDURE IF EXISTS sp_todo_service_set_attribute
DROP PROCEDURE IF EXISTS sp_todo_service_set_ready
DROP PROCEDURE IF EXISTS sp_trigger_reports
DROP PROCEDURE IF EXISTS sp_unset_cat
DROP PROCEDURE IF EXISTS sp_unset_discussed_by
DROP PROCEDURE IF EXISTS sp_unset_exam
DROP PROCEDURE IF EXISTS sp_unset_location
DROP PROCEDURE IF EXISTS sp_unset_observation
DROP PROCEDURE IF EXISTS sp_unset_result
DROP PROCEDURE IF EXISTS sp_unset_result_location
DROP PROCEDURE IF EXISTS sp_update_workplan_item
GO