-- Some missing spaces mess up dbo.fn_strength_sort

UPDATE c_Drug_Formulation
SET form_descr = REPLACE(form_descr, 'n1', 'n 1')
WHERE form_descr LIKE '%n1%'

UPDATE c_Drug_Formulation
SET form_descr = REPLACE(form_descr, 'e1', 'e 1')
WHERE form_descr LIKE '%e1%'

UPDATE c_Drug_Formulation
SET form_descr = REPLACE(form_descr, 'spiramycin3', 'spiramycin 3')
WHERE form_descr LIKE '%spiramycin3%'


--(1 row(s) affected)

--(2 row(s) affected)

--(1 row(s) affected)

-- Formulation with ambiguous brand names

update c_Drug_Formulation set form_descr = '"AkuriT-4" (rifampicin 150 MG / isoniazid 75 MG / pyrazinamide 400 MG / ethambutol 275 MG) Oral Tablet' where form_rxcui = 'KEB11416'
update c_Drug_Formulation set form_descr = '"Ampiclox 250 MG" (ampicillin 125 MG / cloxacillin 125 MG) in 5 ML Powder for Oral Solution' where form_rxcui = 'KEB2700'
update c_Drug_Formulation set form_descr = '"Ampiclox 500 MG" (ampicillin 250 MG / cloxacillin 250 MG) Oral Capsule' where form_rxcui = 'KEB2676'
update c_Drug_Formulation set form_descr = '"Ampiclox 90 MG" (ampicillin 60 MG / cloxacillin 30 MG) in 0.6 ML Neonatal Oral Drops Suspension'  where form_rxcui = 'KEB2682'
update c_Drug_Formulation set form_descr = '"Ampoxin 1 GM" (ampicillin 500 MG / cloxacillin 500 MG) Injection' where form_rxcui = 'KEB7602'
update c_Drug_Formulation set form_descr = '"Ampoxin 500 MG" (ampicillin 250 MG / cloxacillin 250 MG) Injection' where form_rxcui = 'KEB7580'
update c_Drug_Formulation set form_descr = '"Amqunate" { 6 (Artesunate 50 MG Oral Tablet) / 6 (Amodiaquine 153 MG Oral Tablet) } Combi pack' where form_rxcui = 'KEB5310'
update c_Drug_Formulation set form_descr = '"Amqunate-P" { 6 (Artesunate 25 MG Dispersible Oral Tablet) / 6 (Amodiaquine 76.5 MG Dispersible Oral Tablet) } Combipack' where form_rxcui = 'KEB6023'
update c_Drug_Pack set descr = '"Artequin-300/375 Child" { 3 (artesunate 100 MG Oral Tablet) / 3 (mefloquine 125 MG Oral Tablet) } Pack' where rxcui = 'KEB4662'
update c_Drug_Pack set descr = '"Artequin-600/750 Adult" { 3 (artesunate 200 MG Oral Tablet) / 3 (mefloquine 250 MG Oral Tablet) } Pack' where rxcui = 'KEB4664'
update c_Drug_Formulation set form_descr = '"Augmentin 312 MG" (amoxicillin 250 MG / clavulanic acid 62.5 MG) in 5 ML Oral Suspension' where form_rxcui = 'KEB2758'
update c_Drug_Formulation set form_descr = '"Augmentin 375 MG" (amoxicillin 250 MG / clavulanate potassium 125 MG) Oral Tablet' where form_rxcui = 'KEB2759'
update c_Drug_Formulation set form_descr = '"Augmentin 625 MG" (amoxicillin 500 MG / clavulanate potassium 125 MG) Oral Tablet' where form_rxcui = 'KEB2761'
update c_Drug_Pack set descr = '"Azflor" { 2 (azithromycin 500 MG Oral Tablet) / 1 (fluconazole 150 MG Oral Capsule) / 2 ( ornidazole 750 MG Oral Tablet) } Kit' where rxcui = 'KEB13286'
update c_Drug_Formulation set form_descr = '"Azil-40H" (40 MG / 12.5 MG) Oral Tablet' where form_rxcui = 'KEB16702'
update c_Drug_Formulation set form_descr = '"Azil-80H" (80 MG / 12.5 MG) Oral Tablet' where form_rxcui = 'KEB16707'
update c_Drug_Formulation set form_descr = '"Bioferon 75 MG / 0.75 MG / 5 MCG / 305 MG" (equivalent to elemental Iron 100 MG) / 5 MG Oral Capsule' where form_rxcui = 'KEB6388'
update c_Drug_Formulation set form_descr = '"Calcinol-1000" (2500 MG / 400 IU) Granules for Oral Solution' where form_rxcui = 'KEB475'
update c_Drug_Pack set descr = '"Candid-V6" { 1 (Candid 100 MG Vaginal Tablet) / 1 (Candid 1 % Vaginal Cream) } Combipack' where rxcui = 'KEB6461'
update c_Drug_Formulation set form_descr = '"Carbosten Promethazine" (carbocisteine 100 MG / promethazine 2.5 MG) in 5 ML Oral Syrup' where form_rxcui = 'KEB941'
update c_Drug_Formulation set form_descr = '"Cefo-bact 1 GM" (cefoperazone 500 MG / sulbactam 500 MG ) Injection' where form_rxcui = 'KEB12395'
update c_Drug_Formulation set form_descr = '"Cilnitel 40 CT" (cilnidipine 10 MG / telmisartan 40 MG / chlorthalidone 12.5 MG) Oral Tablet' where form_rxcui = 'KEB17387'
update c_Drug_Formulation set form_descr = '"Cilnitel 5/40 CT" (cilnidipine 5 MG / telmisartan 40 MG / chlorthalidone 12.5 MG) Oral Tablet' where form_rxcui = 'KEB17385'
update c_Drug_Formulation set form_descr = '"Cilnitel 5/80 CT" (cilnidipine 5 MG / telmisartan 80 MG / chlorthalidone 12.5 MG) Oral Tablet' where form_rxcui = 'KEB17386'
update c_Drug_Formulation set form_descr = '"Cilnitel 80 CT" (cilnidipine 10 MG / telmisartan 80 MG / chlorthalidone 12.5 MG) Oral Tablet' where form_rxcui = 'KEB17388'
update c_Drug_Formulation set form_descr = '"Clavulin 1000 MG" (amoxicillin 875 MG / clavulanate potassium 125 MG) Oral Tablet' where form_rxcui = 'KEB2812'
update c_Drug_Formulation set form_descr = '"Clavulin 228.5 MG" (amoxicillin 200 MG / clavulanic acid 28.5 MG) in 5 ML Oral Suspension' where form_rxcui = 'KEB2806'
update c_Drug_Formulation set form_descr = '"Clavulin 625 MG" (amoxicillin 500 MG / clavulanate potassium 125 MG) Oral Tablet' where form_rxcui = 'KEB2810'
update c_Drug_Formulation set form_descr = '"Cledomox-DT 228.5 MG" (amoxicillin 200 MG / clavulanate potassium 28.5 MG) Dispersible Oral Tablet' where form_rxcui = 'KEB9591'
update c_Drug_Pack set descr = '"Co-Arinate FDC Adult" { 3 (artesunate 200 MG / sulfamethoxypyrazine 500 MG / pyrimethamine 25 MG Oral Tablet) } Pack' where rxcui = 'KEB1532'
update c_Drug_Pack set descr = '"Co-Arinate FDC Junior{ 3  (artesunate 100 MG / sulfamethoxypyrazine 250 MG / pyrimethamine 12.5 MG Oral Tablet) } Pack' where rxcui = 'KEB1527'
update c_Drug_Formulation set form_descr = '"Coldcap Daytime and Night time" { 12 (paracetamol 500 MG / caffeine 30 MG / pseudoephedrine 30 MG Oral Capsule) 12 (paracetamol 500 MG / chlorpheniramine maleate 2 MG Oral Capsule ) } Pack' where form_rxcui = 'KEB480'
update c_Drug_Pack set descr = '"Combisaf" { 1 (Azithromycin 1000 MG Oral Tablet) / 1 (Fluconazole 150 MG Oral Capsule) / 1 (Secnidazole 1000 MG Oral Tablet) } Kit' where rxcui = 'KEB11635'
update c_Drug_Formulation set form_descr = '"Curam 1000 MG" (amoxicillin 875 MG / clavulanate potassium 125 MG) Oral Tablet' where form_rxcui = 'KEB241'
update c_Drug_Formulation set form_descr = '"Curam 156.25 MG" (amoxicillin 125 MG / clavulanic acid 31.25 MG) in 5 ML Oral Suspension' where form_rxcui = 'KEB267'
update c_Drug_Formulation set form_descr = '"Curam 457 MG" (amoxicillin 400 MG / clavulanic acid 57 MG) Powder for Oral Suspension' where form_rxcui = 'KEB15791'
update c_Drug_Formulation set form_descr = '"Curam 625 MG" (amoxicillin 500 MG / clavulanate potassium 125 MG) Oral Tablet' where form_rxcui = 'KEB237'
update c_Drug_Formulation set form_descr = '"Dafraclav 1000 MG" (amoxicillin 875 MG / clavulanic acid 125 MG) Oral Tablet' where form_rxcui = 'KEB1899'
update c_Drug_Formulation set form_descr = '"Dafraclav 228 MG" (amoxicillin 200 MG / clavulanic acid 28 MG) in 5 ML Powder for Oral Suspension' where form_rxcui = 'KEB1919'
update c_Drug_Formulation set form_descr = '"Dafraclav 457 MG" (amoxicillin 400 MG / clavulanic acid 57 MG) Powder for Oral Suspension' where form_rxcui = 'KEB1922'
update c_Drug_Formulation set form_descr = '"Dafraclav 625 MG" (amoxicillin 500 MG / clavulanic acid 125 MG) Oral Tablet' where form_rxcui = 'KEB1897'
update c_Drug_Formulation set form_descr = '"Dazel" { 1 (fluconazole 150 MG Oral Tablet) / 1 (azithromycin 1 GM Oral Tablet) / 2 (secnidazole 1 GM Oral Tablet) } Kit' where form_rxcui = 'KEB9429'
update c_Drug_Formulation set form_descr = '"Dexorange" (ferric ammonium citrate 160 MG" (equivalent to elemental iron 32.8 MG) / vitamin B12 7.5 MCG / folic acid 0.5 MG / zinc sulphate monohydrate 20.61 MG" (equivalent to elemental zinc 7.5 MG)) Oral Capsule' where form_rxcui = 'KEB13239'
update c_Drug_Formulation set form_descr = '"DF118" (dihydrocodeine tartrate 30 MG) Oral Tablet' where form_rxcui = 'KEB3623'
update c_Drug_Formulation set form_descr = '"Diane-35" (cyproterone acetate 2 MG / ethinyl estradiol 0.035 MG) Oral Tablet' where form_rxcui = 'KEB980'
update c_Drug_Formulation set form_descr = '"Drepene 6:3:3" (benzathine penicillin 600,000 UNITS / procaine penicillin 300,000 UNITS / benzylpenicillin potassium 300,000 UNITS) Injection' where form_rxcui = 'KEB11566'
update c_Drug_Formulation set form_descr = '"Ecee-2" (levonorgestrel 0.75 MG) Oral Tablet' where form_rxcui = 'KEB2038'
update c_Drug_Formulation set form_descr = '"Emcon-1" (levonorgestrel 1.5 MG) Oral Tablet' where form_rxcui = 'KEB11982'
update c_Drug_Pack set descr = '"Esclam H. Pylori- 7" { 2 (esomeprazole 20 MG Oral Tablet) / 2 (clarithromycin 500 MG Oral Tablet) / 2 (amoxicillin 1000 MG Oral Tablet) } Kit' where rxcui = 'KEB8620'
update c_Drug_Pack set descr = '"Esose H.Pylori- 7" { 1 (esomeprazole 40 MG Oral Tablet ) / 1 (levofloxacin 500 MG Oral Tablet ) / 2 (amoxicillin 500 MG Oral Capsule ) Morning Pack / 1 (esomeprazole 40 MG Oral Tablet ) / 1 (levofloxacin 500 MG Oral Tablet ) / 2 (amoxicillin 500 MG Oral Capsule ) Evening Pack } Kit' where rxcui = 'KEB14713'
update c_Drug_Formulation set form_descr = '"Eurolide Depot 3.75 MG" (1 Month) Powder for Injection' where form_rxcui = 'KEB13936'
update c_Drug_Formulation set form_descr = '"Ferogen Iron Sucrose" (equivalent to elemental iron) 100 MG in 5 ML Injection' where form_rxcui = 'KEB13294'
update c_Drug_Formulation set form_descr = '"Flamox 250 MG" (amoxicillin 125 MG / flucloxacillin magnesium 125 MG) in 5 ML Powder for Oral Suspension' where form_rxcui = 'KEB7623'
update c_Drug_Formulation set form_descr = '"Fleming 228.5 MG" (amoxicillin 200 MG / clavulanic acid 28.5 MG) in 5 ML Oral Suspension' where form_rxcui = 'KEB6014'
update c_Drug_Formulation set form_descr = '"Furoxiclav 625" (Cefuroxime 500 MG / Clavulanic Acid 125 MG) Oral Tablet' where form_rxcui = 'KEB15924'
update c_Drug_Formulation set form_descr = '"Fytobact 2 GM" (cefoperazone 1000 MG / sulbactam 1000 MG) Injection' where form_rxcui = 'KEB13074'
update c_Drug_Formulation set form_descr = '"Glifozin M 1000" (canaglifozin 50 MG / metformin 1000 MG) Oral Tablet' where form_rxcui = 'KEB16709'
update c_Drug_Formulation set form_descr = '"Glifozin M 500" (canaglifozin 50 MG / metformin 500 MG) Oral Tablet' where form_rxcui = 'KEB16708'
update c_Drug_Pack set descr = '"Gynagone" { 2 (Azithromycin 500 MG Oral Tablet) / 1 (Fluconazole 150 MG Oral Capsule) / 4 (Secnidazole 500 MG Oral Tablet) } Kit' where rxcui = 'KEB10821'
update c_Drug_Pack set descr = '"H-Cure ES - 7" { 1 (esomeprazole 40 MG Oral Tablet ) / 1 (levofloxacin 500 MG Oral Tablet ) / 2 (amoxicillin 500 MG Oral Capsule ) Morning Pack / 1 (esomeprazole 40 MG Oral Tablet ) / 1 (levofloxacin 500 MG Oral Tablet ) / 2 (amoxicillin 500 MG Oral Capsule ) Evening Pack } Kit' where rxcui = 'KEB13462'
update c_Drug_Pack set descr = '"Helicoban  7" { 2 (omeprazole  20 MG Oral Capsule) / 2 (clarithromycin 250 MG Oral Capsule) / 2 (tinidazole  500 MG Oral Capsule) } Kit' where rxcui = 'KEB11423'
update c_Drug_Pack set descr = '"Heligo H. Pylori -7" { 2 (lansoprazole 30 MG Oral Capsule) / 2 (clarithromycin 250 MG Oral Tablet) / 2 (tinidazole 500 MG Oral Tablet) } Kit' where rxcui = 'KEB5777'
update c_Drug_Pack set descr = '"Heligone" { 6 (azithromycin 500 MG Oral Tablet) / 28 (amoxicillin 500 MG Oral Capsule) / 14 (omeprazole 20 MG Oral Capsule) } Kit' where rxcui = 'KEB10820'
update c_Drug_Formulation set form_descr = '"INJ.K MM" (Pediatric) 2 MG IN 0.2 ML Injection' where form_rxcui = 'KEB16615'
update c_Drug_Formulation set form_descr = '"Koact 312.5 MG" (amoxicillin 250 MG / clavulanic acid 62.5 MG) in 5 ML Oral  Suspension' where form_rxcui = 'KEB1754'
update c_Drug_Formulation set form_descr = '"Komefan 140" (artemether 20 MG / lumefantrine 120 MG) Oral Tablet' where form_rxcui = 'KEB12059'
update c_Drug_Formulation set form_descr = '"Komefan 280" (artemether 40 MG / lumefantrine 240 MG) Oral Tablet' where form_rxcui = 'KEB12060'
update c_Drug_Formulation set form_descr = '"Lupride Depot 11.25 MG" (3 Month) Injection' where form_rxcui = 'KEB7574'
update c_Drug_Formulation set form_descr = '"Lupride Depot 3.75 MG" (1 Month) Injection' where form_rxcui = 'KEB7572'
update c_Drug_Formulation set form_descr = '"Medisart 300H" (irbesartan 300 MG / hydrochlorothiazide 12.5 MG) Oral Tablet' where form_rxcui = 'KEB12494'
update c_Drug_Pack set descr = '"Microgynon Fe" { 21 (levonorgestrel 0.15 MG / ethinyl estradiol 0.03 MG Oral Tablet) / 7 ( ferrous fumarate 75 MG Oral Tablet) } Pack' where rxcui = 'KEB1038'
update c_Drug_Formulation set form_descr = '"Microgynon-30" (levonorgestrel 150 MCG / ethinylestradiol 30 MCG) Oral Tablet' where form_rxcui = 'KEB1037'
update c_Drug_Pack set descr = '"Nexiken H. Pylori- 7" { 2 (esomeprazole 20 MG Delayed Release Oral Tablet) / 2 (clarithromycin 500 MG Oral Tablet) / 2 (amoxicillin 1000 MG Oral Tablet ) } Kit' where rxcui = 'KEB9106'
update c_Drug_Formulation set form_descr = '"Postinor-2" (levonorgestrel 0.75 MG) Oral Tablet' where form_rxcui = 'KEB3780'
update c_Drug_Pack set descr = '"Pylodi H. Pylori 7" { 2 (lansoprazole 30 MG Oral Capsule) / 2 (clarithromycin 500 MG Oral Tablet) / 2 (tinidazole  500 MG Oral Tablet) } Kit' where rxcui = 'KEB8744'
update c_Drug_Formulation set form_descr = '"Pylotrip H. Pylori- 7" { 2 (lansoprazole 30 MG Delayed Release Capsule) / 2 (amoxicillin 1000 MG Oral Capsule) / 2 (clarithromycin 500 MG Oral Tablet) } Kit' where form_rxcui = 'KEB2120'
update c_Drug_Formulation set form_descr = '"Ranferon" (ferrous fumarate 305 MG" (equivalent to elemental iron 100 MG) / folic acid 0.75 MG / cyanocobalamin 5 MCG / ascorbic acid 75 MG / zinc sulphate 5 MG) Oral Capsule' where form_rxcui = 'KEB2963'
update c_Drug_Formulation set form_descr = '"Ranferon-12" (ferric ammonium citrate 200 MG" (equivalent to elemental iron 41 MG) / folic acid 1.5 MG / vitamin B 12 50 MCG) in 5 ML Oral Solution' where form_rxcui = 'KEB2970'
update c_Drug_Formulation set form_descr = '"RAZ 20 MG" (Lyophilised) Injection' where form_rxcui = 'KEB11031'
update c_Drug_Formulation set form_descr = '"Revoke-72" (levonorgestrel 0.75 MG) Oral Tablet' where form_rxcui = 'KEB9030'
update c_Drug_Formulation set form_descr = '"Rhinathiol Promethazine" (carbocisteine 2000 MG / promethazine 500 MG in 125 ML) Oral Syrup' where form_rxcui = 'KEB5702'
update c_Drug_Formulation set form_descr = '"Rifafour-E-275" (rifampicin 150 MG / isoniazid 75 MG / pyrazinamide 400 MG / ethambutol 275 MG) Oral Tablet' where form_rxcui = 'KEB5924'
update c_Drug_Formulation set form_descr = '"Rihaz-E" (rifampicin 150 MG / isoniazid 75 MG / pyrazinamide 400 MG / ethambutol 275 MG) Oral Tablet' where form_rxcui = 'KEB6926'
update c_Drug_Formulation set form_descr = '"Rimstar 4-FDC" (rifampicin 150 MG / isoniazid 75 MG / pyrazinamide 400 MG / ethambutol 275 MG) Oral Tablet' where form_rxcui = 'KEB1081'
update c_Drug_Formulation set form_descr = '"Sandimmun Neoral" (cycloSPORINE, modified 100 MG) Oral Capsule' where form_rxcui = 'KEB4886'
update c_Drug_Formulation set form_descr = '"Sandimmun Neoral" (cycloSPORINE, modified 25 MG) Oral Capsule' where form_rxcui = 'KEB4881'
update c_Drug_Formulation set form_descr = '"Sulbacin 1.5 GM" (ampicillin 1000 MG / sulbactam 500 MG) Injection' where form_rxcui = 'KEB13529'
update c_Drug_Formulation set form_descr = '"Suprapen 500 MG" (amoxicillin 250 MG / flucloxacillin sodium 250 MG) Oral Capsule' where form_rxcui = 'KEB3517'
update c_Drug_Formulation set form_descr = '"Suprapen Syrup 250 MG" (amoxicillin 125 MG / flucloxacillin magnesium 125 MG) in 5 ML Oral Solution' where form_rxcui = 'KEB3518'
update c_Drug_Formulation set form_descr = '"Tenoret 50" (atenolol 50 MG / chlorthalidone 12.5 MG) Oral Tablet' where form_rxcui = 'KEB7763'
update c_Drug_Formulation set form_descr = '"Theotaz 281.25" (ceftriaxone 250 MG / tazobactam 31.25 MG) Injection' where form_rxcui = 'KEB15406'
update c_Drug_Formulation set form_descr = '"Traxol-S 1.5 GM" (cefTRIAXone 1000 MG / sulbactam 500 MG) Injection' where form_rxcui = 'KEB5082'
update c_Drug_Formulation set form_descr = '"Trixon-S 750 MG" (cefTRIAXone 500 MG / sulbactam 250 MG) Injection' where form_rxcui = 'KEB9513'
update c_Drug_Formulation set form_descr = '"Unasyn 1.5 GM" (ampicillin 1000 MG / sulbactam 500 MG) Injection' where form_rxcui = 'KEB5216'
update c_Drug_Formulation set form_descr = '"Uperio 100 MG" (sacubitril 48.6 MG / valsartan 51.4 MG) Oral Tablet' where form_rxcui = 'KEB13806'
update c_Drug_Formulation set form_descr = '"Uperio 200 MG" (sacubitril 97.2 MG / valsartan 102.8 MG) Oral Tablet' where form_rxcui = 'KEB13803'
update c_Drug_Formulation set form_descr = '"Uperio 50 MG" (sacubitril 24.3 MG / valsartan 25.7 MG) Oral Tablet' where form_rxcui = 'KEB13804'
update c_Drug_Formulation set form_descr = '"Vancolon 0.5 GM" (vancomycin 500 MG) Injection' where form_rxcui = 'KEB8466'
update c_Drug_Formulation set form_descr = '"Vastor 20-EZ" (atorvastatin 20 MG / ezetimibe 10 MG) Oral Tablet' where form_rxcui = 'KEB5811'
update c_Drug_Pack set descr = '"VDM" { 1 (azithromycin 1000 MG Oral Tablet) / 1 (fluconazole 150 MG Oral Tablet) / 2 ( secnidazole 1000 MG Oral Tablet) } Kit ' where rxcui = 'KEB8977'
update c_Drug_Formulation set form_descr = '"Vita-UVD3" (vitamin D3 60,000 IU) Oral Capsule' where form_rxcui = 'KEB15207'

