sqlcmd -Q "exec sys.sp_table_privileges 'b_Appointment_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'b_Provider_Translation'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'b_Resource'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_1_record'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Actor_Address'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Actor_Class'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Actor_Class_Purpose'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Actor_Class_Route'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Actor_Class_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Actor_Communication'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Actor_Route_Purpose'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Administration_Frequency'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Administration_Method'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Administration_Method_Proc'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Age_Range'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Age_Range_Assessment'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Age_Range_Category'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Age_Range_Procedure'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Allergy_Drug'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Allergy_Substance'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Assessment'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Assessment_Category'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Assessment_Coding'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Assessment_Definition'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Assessment_Keywords'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Assessment_Map'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Assessment_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Assessment_Type_Progress_Key'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Assessment_Type_Progress_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Attachment_Extension'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Attachment_Extension_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Attachment_Location'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Attachment_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Authority'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Authority_Category'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Authority_Formulary'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Authority_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Cdc_BmiAge'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Cdc_HcAgeInf'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Cdc_LenAgeInf'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Cdc_StatAge'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Cdc_WtAge'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Cdc_WtAgeInf'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Cdc_WtLenInf'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Cdc_WtStat'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Chart'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Chart_Alert_Category'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Chart_Page_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Chart_Page_Definition'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Chart_Section'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Chart_Section_Page'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Chart_Section_Page_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Classification_Set'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Classification_Set_Item'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Common_Assessment'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Common_Drug'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Common_Observation'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Common_Procedure'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Component'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Component_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Component_Attribute_Def'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Component_Base_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Component_Base_Attribute_Def'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Component_Definition'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Component_Interface'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_component_interface_object_log'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_component_interface_route'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_component_interface_route_property'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Component_Log'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Component_Param'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Component_Param_Class'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Component_Registry'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Component_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Component_Version'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Config_Log'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Config_Object'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Config_Object_Category'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Config_Object_Library'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Config_Object_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Config_Object_Version'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Config_Object_Version_Dependency'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Consultant'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Controller_HotSpots'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_CPT_Updates'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Database_Column'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Database_Maintenance'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Database_Modification_Dependancy'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Database_Object'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Database_Object_Permission'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Database_Script'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Database_Script_Log'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Database_Script_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Database_Status'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Database_System'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Database_Table'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Datawindow'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Datawindow_Mapping'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Datawindow_Mapping_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Disease'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Disease_Assessment'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Disease_Group'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Disease_Group_Item'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Display_Command_Definition'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Display_Format'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Display_Format_Item'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Display_Script'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Display_Script_Cmd_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Display_Script_Command'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Document_Purpose'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Document_Route'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Document_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Domain'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Domain_Master'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Dosage_Form'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Drug_Administration'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Drug_Brand'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Drug_Category'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Drug_Compound'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Drug_Definition'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Drug_Drug_Category'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Drug_HCPCS'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Drug_Instruction'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Drug_Maker'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Drug_Package'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Drug_Package_Dispense'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Drug_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Encounter_Procedure'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Encounter_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Encounter_Type_Progress_Key'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Encounter_Type_Progress_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Epro_Object'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Equivalence'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Equivalence_Group'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Event'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_External_Observation'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_External_Observation_Location'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_External_Observation_Result'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_External_Source'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_External_Source_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_External_Source_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Folder'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Folder_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Folder_Selection'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Folder_Workplan'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Formulary'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Formulary_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Growth_Data'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_ICD_Code'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_ICD_Properties'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_ICD_Updates'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Immunization_Dose_Schedule'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Immunization_Schedule'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Location'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Location_Domain'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Maintenance_Assessment'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Maintenance_Metric'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Maintenance_Patient_Class'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Maintenance_Policy'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Maintenance_Procedure'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Maintenance_Protocol'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Maintenance_Protocol_Item'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Maintenance_Treatment'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Material'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Material_Item'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Menu'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Menu_Item'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Menu_Item_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Message_Definition'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Message_Fkey'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Message_Part'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Message_Stream'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Nomenclature_Medcin'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Object_Default_Progress_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Observation'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Observation_Category'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Observation_Observation_Cat'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Observation_Result'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Observation_Result_Qualifier'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Observation_Result_Range'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Observation_Result_Set'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Observation_Result_Set_Item'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Observation_Stage'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Observation_Treatment_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Observation_Tree'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Observation_Tree_Root'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Observation_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Office'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Owner'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Package'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Patient_material'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Patient_material_category'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Preference'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Preference_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Preferred_Provider'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Prescription_Format'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Privilege'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Procedure'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Procedure_Category'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Procedure_Coding'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Procedure_Extra_Charge'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Procedure_Material'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Procedure_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Property'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Property_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Property_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Qualifier'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Qualifier_Domain'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Qualifier_Domain_Category'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Recommended_Observation'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Report_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Report_Category'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Report_Definition'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Report_Params'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Report_Recipient'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Report_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Risk_Factor'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Role'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Room_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Specialty'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Specialty_Assessment_Category'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Specialty_Drug_Category'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Specialty_Observation_Category'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Specialty_Procedure_Category'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Specimen_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Stream'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Table_Altkey'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Table_Fkey'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Table_Update'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Therapy_Model'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Treatment_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Treatment_Type_List'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Treatment_Type_List_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Treatment_Type_List_Def'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Treatment_Type_Progress_Key'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Treatment_Type_Progress_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Treatment_Type_Service'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Treatment_Type_Service_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Treatment_Type_Workplan'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Unit'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Unit_Conversion'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Unit_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_User'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_User_Progress'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_User_Role'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Vaccine'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Vaccine_Disease'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Vaccine_Maker'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Vaccine_Schedule'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Vial_Schedule'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Vial_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Workplan'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Workplan_Item'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Workplan_Item_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Workplan_Selection'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Workplan_Step'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Workplan_Step_Room'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_Workplan_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_XML_Class'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_XML_Class_Selection'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_XML_Code'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_XML_Code_Domain'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'c_XML_Code_Domain_Item'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'dtproperties'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'em_Category'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'em_Component'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'em_Component_Level'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'em_Component_Rule'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'em_Component_Rule_Item'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'em_Documentation_Guide'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'em_Element'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'em_Observation_Element'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'em_Risk'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'em_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'em_Type_Level'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'em_Type_Rule'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'em_Type_Rule_Item'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'em_Visit_Code_Group'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'em_Visit_Code_Item'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'em_Visit_Level'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'em_Visit_Level_Rule'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'em_Visit_Level_Rule_Item'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'icd10cm_codes_2018_tabdel'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'icd10pcs_codes_2019_tabdel'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'jmc_display_stuff'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Active_Services'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_box'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Component_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Component_Base_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Component_Computer_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Component_Preference'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Component_Selection'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Computer_External_Source'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Computer_Printer'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Computer_Printer_Office'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Computers'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Event_Component_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Event_Component_Trigger'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Event_Queue'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Event_Queue_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_External_Source_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Group_Rooms'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Groups'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Log'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_menu_selection'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Message_Log'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Message_Subscription'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_office'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Preferences'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_printer'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Report_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Report_Printer'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Report_Trigger'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Rooms'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Server_Component'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Service'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Service_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Service_Schedule'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Service_Schedule_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Service_Trigger'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Treatment_Service'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Treatment_Type_Default_Mode'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_User_Logins'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_User_Privilege'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_User_Service'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_User_Service_Lock'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'o_Users'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Assessment'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_assessment_Progress'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Assessment_Treatment'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Attachment'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Attachment_Progress'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Chart_Alert'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Chart_Alert_Progress'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Classification_Set_Item'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Encounter_Assessment'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Encounter_Assessment_Charge'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Encounter_Charge'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Encounter_Charge_Modifier'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Family_History'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Family_Illness'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Lastkey'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Letter'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Maintenance_Class'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Material_Used'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Object_Security'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Objective_Location'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Observation'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Observation_Comment_Save'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Observation_Location'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Observation_Result'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Observation_Result_Progress'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Observation_Result_Qualifier'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Patient'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Patient_Alias'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Patient_Authority'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Patient_Encounter'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Patient_Encounter_Progress'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Patient_Guarantor'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Patient_Progress'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Patient_Relation'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Patient_WP'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Patient_WP_Archive'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Patient_WP_Item'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Patient_WP_Item_Archive'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Patient_WP_Item_Attribute'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Patient_WP_Item_Attribute_Archive'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Patient_WP_Item_Progress'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Patient_WP_Item_Progress_Archive'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Treatment_Item'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'p_Treatment_Progress'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'pbcatcol'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'pbcatedt'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'pbcatfmt'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'pbcattbl'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'pbcatvld'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'r_Assessment_Treatment_Efficacy'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'r_Efficacy_Data'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'tmp_xml_permissions'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'tmprelease_display_scripts'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'tmprelease_menus'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'tmprelease_prefs'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'tmprelease_workplans'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'u_assessment_treat_def_attrib'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'u_assessment_treat_definition'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'u_Chart_Selection'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'u_Display_Format_Selection'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'u_Display_Script_Selection'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'u_Exam_Default_Results'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'u_Exam_Definition'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'u_Exam_Selection'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'u_Top_20'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'x'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'x_document_mapping'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'x_encounterpro_Arrived'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'x_External_Application'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'x_External_Application_Message'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'x_ID_Lists'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'x_Integration_Operation'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'x_Integration_Operation_Tree'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'x_Integrations'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'x_MedMan_Arrived'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'x_Message_Type'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'x_Performance_Log'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'x_Property_Exception'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'x_Translate_A'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'x_Translate_P'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'x_Translation_Rule'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
sqlcmd -Q "exec sys.sp_table_privileges 'x_Translation_Set'" -S DESKTOP-GU15HUD\ENCOUNTERPRO -d encounterpro_os -E >> ../check.txt
