IF  EXISTS (SELECT * FROM sys.objects 
where object_id = OBJECT_ID(N'fn_ug_dosage_form') AND type in (N'FN'))
DROP FUNCTION dbo.fn_ug_dosage_form
GO

CREATE FUNCTION dbo.fn_ug_dosage_form (@ug_df varchar(1000))
RETURNS varchar(1000) -- epro_df 
AS 
BEGIN
-- Guesswork as to what the Uganda dosage form column really means. It is in general very poorly chosen.
-- When using this function, if it returns something with "Solution" then if you are looking for 
-- potential matches you should always try the same with "Suspension" substituted.
RETURN  CASE
		WHEN @ug_df = 'LUNG ADMINISTRATION CFC-FREE METERED- DOSE INHALER' THEN 'Metered Dose Inhaler'
		WHEN @ug_df = 'LUNG ADMINISTRATION INHALER CAPSULES' THEN 'Inhalant Powder'
		WHEN @ug_df = 'LUNG ADMINISTRATION LIQUID FOR INHALATION' THEN 'Inhalant Solution'
		WHEN @ug_df = 'LUNG ADMINISTRATION METERED-DOSE INHALER' THEN 'Metered Dose Inhaler'
		WHEN @ug_df = 'LUNG ADMINISTRATION METERED-DOSE LIQUIDS' THEN 'Metered Dose Inhaler'
		WHEN @ug_df = 'LUNG ADMINISTRATION METERED-DOSE POWDER INHALER' THEN 'Dry Powder Inhaler'
		WHEN @ug_df = 'NASAL SYSTEMIC DROPS' THEN 'Nasal Solution'
		WHEN @ug_df = 'NASAL SYSTEMIC METERED-DOSE LIQUIDS' THEN 'Metered Dose Nasal Spray'
		WHEN @ug_df = 'NASAL SYSTEMIC UNIT DOSE AEROSOLS' THEN 'Metered Dose Nasal Spray'
		WHEN @ug_df = 'NASAL TOPICAL DROPS' THEN 'Nasal Solution'
		WHEN @ug_df = 'NASAL TOPICAL METERED DOSE AEROSOLS' THEN 'Metered Dose Nasal Spray'
		WHEN @ug_df = 'NASAL TOPICAL METERED-DOSE LIQUIDS' THEN 'Metered Dose Nasal Spray'
		WHEN @ug_df = 'NASAL TOPICAL SPRAYS WITHOUT GAS' THEN 'Nasal Spray'
		WHEN @ug_df = 'OPHTHALMIC DROPS' THEN 'Ophthalmic Solution'
		WHEN @ug_df = 'OPHTHALMIC LIQUIDS' THEN 'Ophthalmic Solution'
		WHEN @ug_df = 'OPHTHALMIC OINTMENTS' THEN 'Ophthalmic Ointment'
		WHEN @ug_df = 'OPHTHALMIC SUSPENSIONS' THEN 'Ophthalmic Suspension'
		WHEN @ug_df = 'OPHTHALMIC VIALS' THEN 'Ophthalmic Solution' -- possibly also 'Ophthalmic Suspension'
		WHEN @ug_df = 'ORAL LIQUID ORDINARY COMBINATION PACK POWDERS/GRANULES' THEN 'Granules for Oral Solution' -- possibly also 'Granules for Oral Suspension'
		WHEN @ug_df = 'ORAL LIQUID ORDINARY DROPS' THEN 'Oral Solution'
		WHEN @ug_df = 'ORAL LIQUID ORDINARY DRY SUSPENSIONS/SYRUP S/DROPS' THEN 'Oral Suspension'
		WHEN @ug_df = 'ORAL LIQUID ORDINARY EFFERVESCENT POWDERS/GRANULES' THEN 'Granules for Oral Solution'
		WHEN @ug_df = 'ORAL LIQUID ORDINARY EMULSIONS' THEN 'Oral Suspension'
		WHEN @ug_df = 'ORAL LIQUID ORDINARY LIQUIDS' THEN 'Oral Solution'
		WHEN @ug_df = 'ORAL LIQUID ORDINARY OTHER LIQUIDS' THEN 'Oral Solution'
		WHEN @ug_df = 'ORAL LIQUID ORDINARY OTHER POWDERS/GRANULES' THEN 'Granules for Oral Solution' -- possibly also 'Granules for Oral Suspension'
		WHEN @ug_df = 'ORAL LIQUID ORDINARY SOLUBLE POWDERS' THEN 'Powder for Oral Solution' -- possibly also 'Powder for Oral Suspension'
		WHEN @ug_df = 'ORAL LIQUID ORDINARY SUSPENSIONS' THEN 'Oral Suspension'
		WHEN @ug_df = 'ORAL LIQUID ORDINARY SYRUPS' THEN 'Oral Solution'
		WHEN @ug_df = 'ORAL LIQUID ORDINARY UNIT DOSE POWDERS' THEN 'Powder for Oral Solution'
		WHEN @ug_df = 'ORAL SOLID ORDINARY CAPSULES' THEN 'Oral Capsule'
		WHEN @ug_df = 'ORAL SOLID ORDINARY CHEWABLE COATED TABLETS' THEN 'Chewable Tablet'
		WHEN @ug_df = 'ORAL SOLID ORDINARY CHEWABLE TABLETS' THEN 'Chewable Tablet'
		WHEN @ug_df = 'ORAL SOLID ORDINARY COATED TABLETS' THEN 'Oral Tablet'
		WHEN @ug_df = 'ORAL SOLID ORDINARY COMBINATION PACK COATED TABLETS' THEN 'Oral Tablet'
		WHEN @ug_df = 'ORAL SOLID ORDINARY COMBINATION PACK POWDERS/GRANULES' THEN 'Granules for Oral Solution'
		WHEN @ug_df = 'ORAL SOLID ORDINARY COMBINATION PACK TABLETS' THEN 'Oral Tablet'
		WHEN @ug_df = 'ORAL SOLID ORDINARY EFFERVESCENT TABLETS' THEN 'Effervescent Oral Tablet'
		WHEN @ug_df = 'ORAL SOLID ORDINARY ENTERIC- COATED CAPSULES' THEN 'Oral Capsule'
		WHEN @ug_df = 'ORAL SOLID ORDINARY ENTERIC- COATED TABLETS' THEN 'Oral Tablet'
		WHEN @ug_df = 'ORAL SOLID ORDINARY FILM- COATED TABLETS' THEN 'Oral Tablet'
		WHEN @ug_df = 'ORAL SOLID ORDINARY GELATIN- COATED TABLETS' THEN 'Oral Tablet'
		WHEN @ug_df = 'ORAL SOLID ORDINARY GRANULES' THEN 'Oral Granules'
		WHEN @ug_df = 'ORAL SOLID ORDINARY LAYERED TABLETS' THEN 'Oral Tablet'
		WHEN @ug_df = 'ORAL SOLID ORDINARY LOZENGES' THEN 'Oral Lozenge'
		WHEN @ug_df = 'ORAL SOLID ORDINARY ORALLY DISINTEGRATING TABLETS' THEN 'Disintegrating Oral Tablet'
		WHEN @ug_df = 'ORAL SOLID ORDINARY OTHER CAPSULES' THEN 'Oral Capsule'
		WHEN @ug_df = 'ORAL SOLID ORDINARY OTHER COATED TABLETS' THEN 'Oral Tablet'
		WHEN @ug_df = 'ORAL SOLID ORDINARY OTHER SPECIAL FORMS' THEN 'Pack'
		WHEN @ug_df = 'ORAL SOLID ORDINARY OTHER TABLETS' THEN 'Oral Tablet'
		WHEN @ug_df = 'ORAL SOLID ORDINARY POWDERS' THEN 'Powder for Oral Suspension'
		WHEN @ug_df = 'ORAL SOLID ORDINARY SOLUBLE TABLETS' THEN 'Disintegrating Oral Tablet'
		WHEN @ug_df = 'ORAL SOLID ORDINARY SUBLINGUAL TABLETS' THEN 'Sublingual Tablet'
		WHEN @ug_df = 'ORAL SOLID ORDINARY TABLETS' THEN 'Oral Tablet'
		WHEN @ug_df = 'ORAL SOLID RETARD CAPSULES' THEN 'Delayed Release Oral Capsule'
		WHEN @ug_df = 'ORAL SOLID RETARD COATED TABLETS' THEN 'Delayed Release Oral Tablet'
		WHEN @ug_df = 'ORAL SOLID RETARD ENTERIC-COATED TABLETS' THEN 'Delayed Release Oral Tablet'
		WHEN @ug_df = 'ORAL SOLID RETARD FILM-COATED TABLETS' THEN 'Delayed Release Oral Tablet'
		WHEN @ug_df = 'ORAL SOLID RETARD LAYERED TABLETS' THEN 'Delayed Release Oral Tablet'
		WHEN @ug_df = 'ORAL SOLID RETARD TABLETS' THEN 'Delayed Release Oral Tablet'
		WHEN @ug_df = 'ORAL TOPICAL DROPS' THEN 'Oral Suspension'
		WHEN @ug_df = 'ORAL TOPICAL GELS / SOLS' THEN 'Oral Gel'
		WHEN @ug_df = 'ORAL TOPICAL LIQUIDS' THEN 'Mucous Membrane Topical Solution'
		WHEN @ug_df = 'ORAL TOPICAL SPRAYS WITHOUT GAS' THEN 'Oral Spray'
		WHEN @ug_df = 'ORAL TOPICAL SUSPENSIONS' THEN 'Oral Suspension'
		WHEN @ug_df = 'ORAL TOPICAL UNIT DOSE GELS/SOLS' THEN 'Oral Gel'
		WHEN @ug_df = 'OTHER SYSTEMIC LIQUID INHALATIONS' THEN 'Inhalant Solution'
		WHEN @ug_df = 'OTHER SYSTEMIC LIQUIDS' THEN '???'
		WHEN @ug_df = 'OTHER SYSTEMIC SPECIAL SOLIDS' THEN '???'
		WHEN @ug_df = 'OTIC DROPS' THEN 'Otic Solution'
		WHEN @ug_df = 'PARENTERAL ORDINARY AMPOULES' THEN '???'
		WHEN @ug_df = 'PARENTERAL ORDINARY CARTRIDGES' THEN '???'
		WHEN @ug_df = 'PARENTERAL ORDINARY COMBINATION PACK VIALS' THEN 'Injection'
		WHEN @ug_df = 'PARENTERAL ORDINARY DRY AMPOULES' THEN 'Injection'
		WHEN @ug_df = 'PARENTERAL ORDINARY DRY PRE- FILLED PENS' THEN 'Pen Injector'
		WHEN @ug_df = 'PARENTERAL ORDINARY DRY VIALS' THEN 'Injection'
		WHEN @ug_df = 'PARENTERAL ORDINARY I M PRE- FILLED SYRINGES' THEN 'Prefilled Syringe'
		WHEN @ug_df = 'PARENTERAL ORDINARY I V AMPOULES' THEN 'Injection'
		WHEN @ug_df = 'PARENTERAL ORDINARY I V VIALS' THEN 'Injection'
		WHEN @ug_df = 'PARENTERAL ORDINARY IM AMPOULES' THEN 'Injection'
		WHEN @ug_df = 'PARENTERAL ORDINARY IM VIALS' THEN 'Injection'
		WHEN @ug_df = 'PARENTERAL ORDINARY INFUSION AMPOULES' THEN 'Injectable Solution' -- possibly also 'Injectable Suspension'
		WHEN @ug_df = 'PARENTERAL ORDINARY INFUSION BAGS' THEN 'Injectable Solution' -- possibly also 'Injectable Suspension'
		WHEN @ug_df = 'PARENTERAL ORDINARY INFUSION DRY VIALS/BOTTLES' THEN 'Injection'
		WHEN @ug_df = 'PARENTERAL ORDINARY INFUSION VIALS/BOTTLES' THEN 'Injection'
		WHEN @ug_df = 'PARENTERAL ORDINARY OTHER INFUSIONS' THEN 'Injection'
		WHEN @ug_df = 'PARENTERAL ORDINARY OTHER VIALS' THEN 'Injectable Solution'
		WHEN @ug_df = 'PARENTERAL ORDINARY PRE- FILLED PENS' THEN 'Pen Injector'
		WHEN @ug_df = 'PARENTERAL ORDINARY PRE- FILLED SYRINGES' THEN 'Prefilled Syringe'
		WHEN @ug_df = 'PARENTERAL ORDINARY S C VIALS' THEN 'Injectable Solution'
		WHEN @ug_df = 'PARENTERAL ORDINARY VIALS' THEN 'Injectable Solution'
		WHEN @ug_df = 'PARENTERAL RETARD AMPOULES' THEN 'Injectable Solution'
		WHEN @ug_df = 'PARENTERAL RETARD DRY VIALS' THEN 'Injection'
		WHEN @ug_df = 'PARENTERAL RETARD IM AMPOULES' THEN 'Injection'
		WHEN @ug_df = 'PARENTERAL RETARD IMPLANTS' THEN 'Drug Implant'
		WHEN @ug_df = 'PARENTERAL RETARD OTHER VIALS' THEN '???'
		WHEN @ug_df = 'PARENTERAL RETARD PRE-FILLED SYRINGES' THEN 'Prefilled Syringe'
		WHEN @ug_df = 'PESSARIES' THEN 'Vaginal Insert'
		WHEN @ug_df = 'RECTAL SYSTEMIC ADULT SUPPOSITORIES' THEN 'Rectal Suppository'
		WHEN @ug_df = 'RECTAL SYSTEMIC ENEMA LIQUIDS' THEN 'Enema'
		WHEN @ug_df = 'RECTAL SYSTEMIC PAEDIATRIC SUPPOSITORIES' THEN 'Rectal Suppository'
		WHEN @ug_df = 'RECTAL SYSTEMIC SUPPOSITORIES' THEN 'Rectal Suppository'
		WHEN @ug_df = 'SUPPOSITORIES' THEN 'Rectal Suppository'
		WHEN @ug_df = 'TOPICAL EXTERNAL ADULT SUPPOSITORIES' THEN 'Rectal Suppository'
		WHEN @ug_df = 'TOPICAL EXTERNAL CREAMS' THEN 'Topical Cream'
		WHEN @ug_df = 'TOPICAL EXTERNAL DUSTING POWDERS' THEN 'Topical Powder'
		WHEN @ug_df = 'TOPICAL EXTERNAL EMULSION GELS' THEN 'Topical Gel'
		WHEN @ug_df = 'TOPICAL EXTERNAL EMULSIONS' THEN 'Topical Lotion'
		WHEN @ug_df = 'TOPICAL EXTERNAL GELS / SOLS' THEN 'Topical Gel'
		WHEN @ug_df = 'TOPICAL EXTERNAL INSTILLATION VIALS' THEN '???'
		WHEN @ug_df = 'TOPICAL EXTERNAL LIQUID SOAPS/WASHES' THEN 'Medicated Shampoo'
		WHEN @ug_df = 'TOPICAL EXTERNAL LIQUIDS' THEN 'Medicated Liquid Soap'
		WHEN @ug_df = 'TOPICAL EXTERNAL LOTIONS' THEN 'Topical Lotion'
		WHEN @ug_df = 'TOPICAL EXTERNAL OINTMENTS' THEN 'Topical Ointment'
		WHEN @ug_df = 'TOPICAL EXTERNAL OTHER CREAMS' THEN 'Topical Cream'
		WHEN @ug_df = 'TOPICAL EXTERNAL OTHER GELS/SOLS' THEN 'Topical Gel'
		WHEN @ug_df = 'TOPICAL EXTERNAL OTHER OINTMENTS' THEN 'Topical Ointment'
		WHEN @ug_df = 'TOPICAL EXTERNAL PASTES' THEN 'Oral Paste'
		WHEN @ug_df = 'TOPICAL EXTERNAL POWDERS' THEN 'Topical Powder'
		WHEN @ug_df = 'TOPICAL EXTERNAL PRESSURISED AEROSOLS' THEN 'Topical Spray'
		WHEN @ug_df = 'TOPICAL EXTERNAL SPIRITS' THEN 'Topical Solution'
		WHEN @ug_df = 'TOPICAL EXTERNAL SPRAYS WITHOUT GAS' THEN 'Topical Spray'
		WHEN @ug_df = 'TOPICAL EXTERNAL SUPPOSITORIES' THEN 'Rectal Suppository'
		WHEN @ug_df = 'TOPICAL EXTERNAL SUSPENSIONS' THEN 'Medicated Shampoo'
		WHEN @ug_df = 'TOPICAL EXTERNAL TABLETS' THEN '???'
		WHEN @ug_df = 'VAGINAL COMBINATION PACK TABLETS' THEN 'Pack'
		WHEN @ug_df = 'VAGINAL CREAMS' THEN 'Vaginal Cream'
		WHEN @ug_df = 'VAGINAL GELS / SOLS' THEN 'Vaginal Gel'
		WHEN @ug_df = 'VAGINAL INTRA UTERINE DEVICES' THEN 'Intrauterine System'
		WHEN @ug_df = 'VAGINAL OTHER SPECIAL FORMS' THEN 'Vaginal Ring'
		WHEN @ug_df = 'VAGINAL SUPPOSITORIES' THEN 'Vaginal Suppository'
		WHEN @ug_df = 'VAGINAL TABLETS' THEN 'Vaginal Tablet'
		ELSE 'huh?' END
END
