CREATE TABLE [dbo].[c_Component_Version] (
    [component_id]             VARCHAR (24)     NOT NULL,
    [version]                  INT              NOT NULL,
    [description]              VARCHAR (80)     NOT NULL,
    [version_description]      TEXT             NULL,
    [component_type]           VARCHAR (24)     NOT NULL,
    [component_class]          VARCHAR (128)    NULL,
    [component_location]       VARCHAR (255)    NULL,
    [component_data]           VARCHAR (255)    NULL,
    [owner_id]                 INT              NOT NULL,
    [created]                  DATETIME         NOT NULL,
    [created_by]               VARCHAR (24)     NOT NULL,
    [status]                   VARCHAR (12)     NOT NULL,
    [status_date_time]         DATETIME         NOT NULL,
    [release_status]           VARCHAR (12)     NULL,
    [release_status_date_time] DATETIME         NULL,
    [min_build]                INT              NOT NULL,
    [min_modification_level]   INT              NOT NULL,
    [objectdata]               IMAGE            NULL,
    [id]                       UNIQUEIDENTIFIER NOT NULL,
    [installer]                VARCHAR (24)     DEFAULT ('NA') NOT NULL,
    [independence]             VARCHAR (24)     DEFAULT ('Unknown') NOT NULL,
    [system_id]                NVARCHAR (48)    DEFAULT ('Unknown') NOT NULL,
    [build]                    INT              DEFAULT ((0)) NOT NULL,
    [build_name]               NVARCHAR (128)   DEFAULT ('Unknown') NOT NULL,
    [compile]                  INT              DEFAULT ((0)) NOT NULL,
    [compile_name]             NVARCHAR (128)   DEFAULT ('Unknown') NOT NULL,
    [test_begin_date]          DATETIME         NULL,
    [beta_begin_date]          DATETIME         NULL,
    [release_date]             DATETIME         NULL,
    [build_status]             VARCHAR (12)     DEFAULT ('Unknown') NOT NULL,
    [notes]                    TEXT             NULL,
    [max_modification_level]   INT              NULL,
    [last_updated]             DATETIME         DEFAULT (getdate()) NOT NULL
);



