CREATE TABLE [dbo].[c_Treatment_Type] (
    [treatment_type]               VARCHAR (24)     NOT NULL,
    [component_id]                 VARCHAR (24)     NULL,
    [description]                  VARCHAR (80)     NULL,
    [in_office_flag]               CHAR (1)         NULL,
    [define_title]                 VARCHAR (20)     NULL,
    [button]                       VARCHAR (64)     NULL,
    [icon]                         VARCHAR (64)     NULL,
    [sort_sequence]                INT              NULL,
    [workplan_id]                  INT              NULL,
    [followup_flag]                CHAR (1)         NULL,
    [observation_type]             VARCHAR (24)     NULL,
    [soap_display_rule]            VARCHAR (24)     NULL,
    [composite_flag]               CHAR (1)         NULL,
    [workplan_close_flag]          CHAR (1)         NULL,
    [workplan_cancel_flag]         CHAR (1)         NULL,
    [referral_specialty_id]        VARCHAR (24)     NULL,
    [attachment_folder]            VARCHAR (40)     NULL,
    [display_format]               VARCHAR (40)     NULL,
    [risk_level]                   INT              NULL,
    [complexity]                   INT              NULL,
    [status]                       VARCHAR (12)     NULL,
    [id]                           UNIQUEIDENTIFIER NOT NULL,
    [display_script_id]            INT              NULL,
    [dashboard_datawindow_config_object_id]            UNIQUEIDENTIFIER              NULL,
    [update_flag]                  CHAR (1)         NOT NULL,
    [owner_id]                     INT              NOT NULL,
    [last_updated]                 DATETIME         NOT NULL,
    [open_menu_id]                 INT              NULL,
    [closed_menu_id]               INT              NULL,
    [past_treatment_menu_id]       INT              NULL,
    [bill_procedure]               BIT              NOT NULL,
    [bill_observation_collect]     BIT              NOT NULL,
    [bill_observation_perform]     BIT              NOT NULL,
    [bill_children_collect]        BIT              NOT NULL,
    [bill_children_perform]        BIT              NOT NULL,
    [default_duplicate_check_days] INT              NULL,
    [epro_object]                  VARCHAR (24)     NULL
);



