CREATE TABLE [dbo].[o_Active_Services] (
    [patient_workplan_id]      INT          NOT NULL,
    [patient_workplan_item_id] INT          NOT NULL,
    [in_office_flag]           CHAR (1)     NOT NULL,
    [cpr_id]                   VARCHAR (12) NULL,
    [encounter_id]             INT          NULL,
    [problem_id]               INT          NULL,
    [treatment_id]             INT          NULL,
    [observation_sequence]     INT          NULL,
    [attachment_id]            INT          NULL,
    [ordered_service]          VARCHAR (24) NULL,
    [followup_workplan_id]     INT          NULL,
    [description]              VARCHAR (80) NULL,
    [ordered_by]               VARCHAR (24) NOT NULL,
    [ordered_for]              VARCHAR (24) NULL,
    [priority]                 SMALLINT     NULL,
    [dispatch_date]            DATETIME     NULL,
    [owned_by]                 VARCHAR (24) NULL,
    [begin_date]               DATETIME     NULL,
    [status]                   VARCHAR (12) NULL,
    [room_id]                  VARCHAR (12) NULL,
    [escalation_date]          DATETIME     NULL,
    [expiration_date]          DATETIME     NULL,
    [user_id]                  VARCHAR (24) NULL,
    [computer_id]              INT          NULL,
    [patient_location]         VARCHAR (12) NULL,
    [office_id]                VARCHAR (4)  NULL,
    [observation_id]           VARCHAR (24) NULL,
    [result_sequence]          SMALLINT     NULL,
    [result]                   VARCHAR (80) NULL,
    [result_date_time]         DATETIME     NULL,
    [location]                 VARCHAR (24) NULL,
    [location_description]     VARCHAR (80) NULL,
    [result_value]             VARCHAR (40) NULL,
    [result_unit]              VARCHAR (12) NULL,
    [result_amount_flag]       CHAR (1)     NULL,
    [print_result_flag]        CHAR (1)     NULL,
    [print_result_separator]   VARCHAR (8)  NULL,
    [abnormal_flag]            CHAR (1)     NULL,
    [abnormal_nature]          VARCHAR (8)  NULL,
    [severity]                 SMALLINT     NULL,
    [unit_preference]          VARCHAR (24) NULL,
    [display_mask]             VARCHAR (40) NULL
);



