CREATE TABLE [dbo].[p_Patient_Authority] (
    [cpr_id]                   VARCHAR (12)     NOT NULL,
    [authority_type]           VARCHAR (24)     NOT NULL,
    [authority_sequence]       SMALLINT         NOT NULL,
    [authority_id]             VARCHAR (24)     NOT NULL,
    [notes]                    VARCHAR (80)     NULL,
    [status]                   VARCHAR (8)      NULL,
    [status_change_date]       DATETIME         NULL,
    [insurance_plan_id]        VARCHAR (24)     NULL,
    [group_number]             VARCHAR (24)     NULL,
    [plan_type]                VARCHAR (12)     NULL,
    [insureds_middle_name]     VARCHAR (16)     NOT NULL,
    [insureds_suffix]          VARCHAR (8)      NOT NULL,
    [insureds_prefix]          VARCHAR (8)      NULL,
    [coverage_type]            VARCHAR (1)      NULL,
    [cpr_id_insured]           VARCHAR (24)     NULL,
    [insureds_last_name]       VARCHAR (16)     NOT NULL,
    [insureds_first_name]      VARCHAR (16)     NOT NULL,
    [workers_comp_flag]        CHAR (1)         NULL,
    [health_coverage_flag]     CHAR (1)         NULL,
    [laboratory_coverage_flag] CHAR (1)         NULL,
    [insureds_degree]          VARCHAR (20)     NULL,
    [insureds_date_of_birth]   DATETIME         NULL,
    [pm_insureds_id]           VARCHAR (24)     NOT NULL,
    [insureds_ssn]             VARCHAR (9)      NOT NULL,
    [insurance_priority]       SMALLINT         NULL,
    [created]                  DATETIME         NULL,
    [created_by]               VARCHAR (24)     NULL,
    [modified_by]              VARCHAR (24)     NULL,
    [id]                       UNIQUEIDENTIFIER NOT NULL
);

