CREATE TABLE [dbo].[p_Patient_Encounter] (
    [cpr_id]                 VARCHAR (12)     NOT NULL,
    [encounter_id]           INT              IDENTITY (1, 1) NOT NULL,
    [encounter_type]         VARCHAR (24)     NULL,
    [encounter_status]       VARCHAR (8)      NULL,
    [encounter_date]         DATETIME         NULL,
    [encounter_description]  VARCHAR (80)     NULL,
    [patient_workplan_id]    INT              NULL,
    [indirect_flag]          CHAR (1)         NULL,
    [patient_class]          CHAR (1)         NULL,
    [patient_location]       VARCHAR (12)     NULL,
    [next_patient_location]  VARCHAR (12)     NULL,
    [admission_type]         CHAR (1)         NULL,
    [attending_doctor]       VARCHAR (24)     NULL,
    [referring_doctor]       VARCHAR (24)     NULL,
    [supervising_doctor]     VARCHAR (24)     NULL,
    [ambulatory_status]      VARCHAR (2)      NULL,
    [vip_indicator]          CHAR (1)         NULL,
    [charge_price_ind]       VARCHAR (2)      NULL,
    [courtesy_code]          VARCHAR (2)      NULL,
    [discharge_disp]         VARCHAR (8)      NULL,
    [discharge_date]         DATETIME         NULL,
    [admit_reason]           VARCHAR (12)     NULL,
    [attachment_id]          INT              NULL,
    [new_flag]               CHAR (1)         NULL,
    [billing_note]           TEXT             NULL,
    [encounter_billing_id]   INT              NULL,
    [billing_posted]         CHAR (1)         NULL,
    [bill_flag]              CHAR (1)         NULL,
    [billing_hold_flag]      CHAR (1)         NULL,
    [office_id]              VARCHAR (4)      NULL,
    [end_date]               DATETIME         NULL,
    [stone_flag]             CHAR (1)         NULL,
    [created]                DATETIME         NULL,
    [created_by]             VARCHAR (24)     NULL,
    [appointment_time]       DATETIME         NULL,
    [est_appointment_length] SMALLINT         NULL,
    [workers_comp_flag]      CHAR (1)         NULL,
    [coding_component_id]    VARCHAR (24)     NULL,
    [billing_calc_date]      DATETIME         NULL,
    [id]                     UNIQUEIDENTIFIER NOT NULL,
    [default_grant]          BIT              NOT NULL,
    [billing_provider_id]    VARCHAR (24)     NULL,
    [encounter_location]     VARCHAR (24)     NULL
);



