CREATE TABLE [dbo].[p_Patient] (
    [cpr_id]                 VARCHAR (12)     NOT NULL,
    [race]                   VARCHAR (24)     NULL,
    [date_of_birth]          DATETIME         NULL,
    [sex]                    VARCHAR (1)      NULL,
    [primary_language]       VARCHAR (12)     NULL,
    [marital_status]         VARCHAR (1)      NULL,
    [billing_id]             VARCHAR (24)     NULL,
    [ssn]                    VARCHAR (24)     NULL,
    [first_name]             VARCHAR (20)     NULL,
    [last_name]              VARCHAR (40)     NULL,
    [degree]                 VARCHAR (12)     NULL,
    [name_prefix]            VARCHAR (12)     NULL,
    [middle_name]            VARCHAR (20)     NULL,
    [name_suffix]            VARCHAR (12)     NULL,
    [maiden_name]            VARCHAR (40)     NULL,
    [attachment_id]          INT              NULL,
    [primary_provider_id]    VARCHAR (24)     NULL,
    [secondary_provider_id]  VARCHAR (24)     NULL,
    [last_update]            DATETIME         NULL,
    [phone_number]           VARCHAR (32)     NULL,
    [patient_id]             INT              NULL,
    [date_of_conception]     DATETIME         NULL,
    [patient_status]         VARCHAR (24)     NOT NULL,
    [created]                DATETIME         NULL,
    [created_by]             VARCHAR (24)     NULL,
    [modified_by]            VARCHAR (24)     NULL,
    [office_id]              VARCHAR (4)      NULL,
    [locked_by]              VARCHAR (24)     NULL,
    [attachment_location_id] INT              NULL,
    [attachment_path]        VARCHAR (128)    NULL,
    [referring_provider_id]  VARCHAR (24)     NULL,
    [address_line_1]         VARCHAR (40)     NULL,
    [address_line_2]         VARCHAR (40)     NULL,
    [state]                  VARCHAR (2)      NULL,
    [zip]                    VARCHAR (10)     NULL,
    [country]                VARCHAR (2)      NULL,
    [secondary_phone_number] VARCHAR (16)     NULL,
    [email_address]          VARCHAR (40)     NULL,
    [religion]               VARCHAR (12)     NULL,
    [nationality]            VARCHAR (12)     NULL,
    [financial_class]        VARCHAR (40)     NULL,
    [city]                   VARCHAR (40)     NULL,
    [employer]               VARCHAR (40)     NULL,
    [employeeID]             VARCHAR (24)     NULL,
    [department]             VARCHAR (10)     NULL,
    [shift]                  VARCHAR (10)     NULL,
    [job_description]        VARCHAR (24)     NULL,
    [start_date]             DATETIME         NULL,
    [termination_date]       DATETIME         NULL,
    [employment_status]      VARCHAR (24)     NULL,
    [id]                     UNIQUEIDENTIFIER NOT NULL,
    [default_grant]          BIT              NOT NULL,
    [nickname]               VARCHAR (20)     NULL,
    [phone_number_7digit]    VARCHAR (8)      NULL,
    [test_patient]           BIT              DEFAULT ((0)) NOT NULL
);

